### ISSUE TITLE
Add option to skip pairing

### ISSUE THREAD

**Issue by jkosinski** [KosinskiLab/AlphaPulldown#101]

**Comment by dingquanyu** [comment]
This has been addressed by: https://github.com/KosinskiLab/AlphaPulldown/blob/e96d395b11a4f96863b885a11060b377049f0a04/alphapulldown/run_multimer_jobs.py#L54

and https://github.com/KosinskiLab/AlphaPulldown/blob/e96d395b11a4f96863b885a11060b377049f0a04/alphapulldown/objects.py#L572
