### ISSUE TITLE
Add ability of skipping templates

### ISSUE THREAD

**Issue by jkosinski** [KosinskiLab/AlphaPulldown#103]

**Comment by DimaMolod** [comment]
@jkosinski what do you mean by 'skipping'? run predictions without templates if (a new flag) --skip-templates is set to True for run_multimer_jobs.py?

**Comment by DimaMolod** [comment]
https://github.com/KosinskiLab/AlphaPulldown/blob/main/alphapulldown/folding_backend/alphafold_backend.py#L353-L354
