### ISSUE TITLE
ValueError when calculating some PI-scores

### ISSUE THREAD

**Issue by EricLMiller** [KosinskiLab/AlphaPulldown#106]
Thank you for providing this program for the community to use. I am screening a large number of target, and I am having an issue with the summary, singularity step. This is the command that I am running:

singularity exec --no-home --bind /home/eric/afp_Genes/step2/${gene}:/mnt /home/eric/alpha-analysis.sif run_get_good_pae.sh --output_dir=/mnt --cutoff=500

The alpha-analysis.sif file was downloaded on 31January, so it contains the corrected qDock calculations. 

This script terminates early after extended calculations. In looking at the logged output, 7 targets (out of ~700) have this error:

*****Calculating pisa *****
*****Writing CSV file with features *****
*****Calculating PI-score*****
Traceback (most recent call last):
  File "/software/pi_score/run_piscore_wc.py", line 242, in <module>
    main()
  File "/software/pi_score/run_piscore_wc.py", line 240, in main
    outfle=args.results)
  File "/software/pi_score/utils.py", line 309, in make_predictions
    pred_em = clf_m.predict(topredict_1)
  File "/opt/conda/envs/pi_score/lib/python2.7/site-packages/sklearn/svm/base.py", line 576, in predict
    y = super(BaseSVC, self).predict(X)
  File "/opt/conda/envs/pi_score/lib/python2.7/site-packages/sklearn/svm/base.py", line 325, in predict
    X = self._validate_for_predict(X)
  File "/opt/conda/envs/pi_score/lib/python2.7/site-packages/sklearn/svm/base.py", line 458, in _validate_for_predict
    accept_large_sparse=False)
  File "/opt/conda/envs/pi_score/lib/python2.7/site-packages/sklearn/utils/validation.py", line 573, in check_array
    allow_nan=force_all_finite == 'allow-nan')
  File "/opt/conda/envs/pi_score/lib/python2.7/site-packages/sklearn/utils/validation.py", line 56, in _assert_all_finite
    raise ValueError(msg_err.format(type_err, X.dtype))
ValueError: Input contains NaN, infinity or a value too large for dtype('float64').
I0130 06:51:33.093644 139825670079680 get_good_inter_pae.py:65] pi_score output for {next target protein}

The script continues calculating the pi_scores for all targets but crashes out after attempting to compute the pi_score calculations for all and move them into the predictions_with_good_interpae.csv file (which it does not end up writing). It terminates with this error:

*****Writing CSV file with features *****
*****Calculating PI-score*****
Traceback (most recent call last):
  File "/app/programme_notebook/get_good_inter_pae.py", line 149, in <module>
    app.run(main)
  File "/opt/conda/lib/python3.9/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/opt/conda/lib/python3.9/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/app/programme_notebook/get_good_inter_pae.py", line 138, in main
    pi_score_df = run_and_summarise_pi_score(FLAGS.output_dir,good_jobs,FLAGS.surface_thres)
  File "/app/programme_notebook/get_good_inter_pae.py", line 91, in run_and_summarise_pi_score
    filtered_df=pd.merge(filtered_df,pi_score,on='jobs')
  File "/opt/conda/lib/python3.9/site-packages/pandas/core/reshape/merge.py", line 107, in merge
    op = _MergeOperation(
  File "/opt/conda/lib/python3.9/site-packages/pandas/core/reshape/merge.py", line 700, in __init__
    ) = self._get_merge_keys()
  File "/opt/conda/lib/python3.9/site-packages/pandas/core/reshape/merge.py", line 1097, in _get_merge_keys
    right_keys.append(right._get_label_or_level_values(rk))
  File "/opt/conda/lib/python3.9/site-packages/pandas/core/generic.py", line 1840, in _get_label_or_level_values
    raise KeyError(key)
KeyError: 'jobs'

I believe that the first ValueError is causing this issue, as when I look at the individual filter_intf_features for these problematic seven files within the created pi_score_outputs folder, I see this:
pdb,interface,Num_intf_residues,Polar,Hydrophobhic,Charged,contact_pairs, sc, hb, sb, int_solv_en, int_area, pvalue
ranked_0,C_B,7,0.143,0.571,0.0,5,0.283,

(so, a csv file with 8 entries)

For the targets that ran without error, I see this in the filter_intf_features file:
pdb,interface,Num_intf_residues,Polar,Hydrophobhic,Charged,contact_pairs, sc, hb, sb, int_solv_en, int_area, pvalue
ranked_0,C_B,28,0.214,0.571,0.071,42,0.067,4,0,-16.68,711.92,0.20

(csv file with the correct 13 entries)

The GPU-heavy second step of AlphaPulldown appears to have run successfully for these problematic seven proteins-protein models, i.e. 5 multimer models, ranked .pdb files, and the two .json files.

Do you have any thoughts on this, or perhaps a fix which prevents the initial ValueError?

Cheers,
Eric

**Comment by henrywotton** [comment]
Hi Eric,

Since all your predictions on the GPUs are finished without errors, it's very likely that the cutoff value in the singularity command is too strict that none of your models satisfied. Please try the command again but this time change the cutoff value to some higher one, such as 100, and I believe it should solve it.

Cheers

**Comment by EricLMiller** [comment]
Hello Dingquan,Thank you for looking at this, but I am encountering this problem with a cutoff of 500; here is the command that I am using:singularity exec --no-home --bind /home/eric/afp_Genes/step2/${gene}:/mnt /home/eric/alpha-analysis.sif run_get_good_pae.sh --output_dir=/mnt --cutoff=500I read about others having a similar error due to too small of cutoff value, but (if I am understanding the cutoff correctly), the issue I am encountering appears to be a unique. Cheers,EricOn 2 Feb 2023, at 04:56, Dingquan Yu ***@***.***> wrote:﻿
Hi Eric,
Since all your predictions on the GPUs are finished without errors, it's very likely that the cutoff value in the singularity command is too strict that none of your models satisfied. Please try the command again but this time change the cutoff value to some higher one, such as 100, and I believe it should solve it.
Cheers

**Comment by henrywotton** [comment]
Hi Eric,

I see. Then it's likely that you have mounted the folder one level above. Could you try ```-bind /home/eric/afp_Genes/step2:/mnt```? BTW the singularity image was updated a couple of days ago. Could you also make sure that you have got the latest version.

**Comment by EricLMiller** [comment]
Hello,

I am using the Singularity image from 2023-01-27.

I am quite certain that this is not a folder structure issue. I am running alphaPulldown across multiple baits and candidates, with a structure like:
/home/eric/afp_Genes/step2/{bait_A}/{bait_A_and_candidate1}/
/home/eric/afp_Genes/step2/{bait_A}/{bait_A_and_candidate2}/
/home/eric/afp_Genes/step2/{bait_A}/{bait_A_and_candidate3}/
..
/home/eric/afp_Genes/step2/{bait_A}/{bait_A_and_candidate700}/
/home/eric/afp_Genes/step2/{bait_B}/{bait_B_and_candidate1}/
..
/home/eric/afp_Genes/step2/{bait_Z}/{bait_Z_and_candidate700}/


Running --bind /home/eric/afp_Genes/step2:/mnt would either have alphaPulldown not find the GPU result folders, or would take a single processor a large amount of time to crunch through all of them; I have about 10,000 bait/candidiate combinations so far. 


Going down the rabbit hole a bit further, the core issue seems to be with the sklearn library, which is part of alphaFold and not alphaPulldown, with the error being:
File "/opt/conda/envs/pi_score/lib/python2.7/site-packages/**sklearn**/utils/validation.py", line 56, in _assert_all_finite
raise ValueError(msg_err.format(type_err, X.dtype))
ValueError: Input contains NaN, infinity or a value too large for dtype('float64').


Would it be possible to add error handling to alphaPulldown so that the analysis pipeline continues and writes out the predictions_with_good_interpae.csv file, even if some of the individual bait/candidate intf_features_XXXX.csv files are incomplete? I did notice that problematic bait/candidate intf_features_XXX.csv files have only 8 comma-delimited entries and not the normal 13 comma-delimited entries. I am uncertain on who to contact about the underlying alphaFold issue, sadly.

Cheers,

Eric

**Comment by henrywotton** [comment]
Hi Eric,

I see and well spotted that the source error came from this line: ```ValueError: Input contains NaN, infinity or a value too large for dtype('float64').``` Unfortunately, this step belongs to PI-score software developed by another group and has nothing to do with AlphaFold itself. Thanks for reporting this error and I will keep in mind and handle this kind of error in the later version. 

To be fair, the PI-score programme took all the output from sc calculations done by CCP4 so in other words, the real cause of your error report may even lie with CCP4 suite programme.  I'm not sure who to contact, either. 

Cheers

**Comment by EricLMiller** [comment]
Hello,
Just an update on this issue for others who may encounter the same issue. When running the singularity step, there appears to be a random chance at getting either of the two following errors:

```
File "/opt/conda/envs/pi_score/lib/python2.7/site-packages/Selkirk/utils/validation.py", line 56, in _assert_all_finite
raise ValueError(msg_err.format(type_err, X.dtype))
ValueError: Input contains NaN, infinity or a value too large for dtype('float64').
```

or this error:

```
*****Writing CSV file with features *****
*****Calculating PI-score*****
All features could not be calculated successfully for atleast one of the interfaces!
Exiting
Traceback (most recent call last):
  File "/app/alpha-analysis/get_good_inter_pae.py", line 150, in <module>
    app.run(main)
  File "/opt/conda/lib/python3.9/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/opt/conda/lib/python3.9/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/app/alpha-analysis/get_good_inter_pae.py", line 139, in main
    pi_score_df = run_and_summarise_pi_score(FLAGS.output_dir,good_jobs,FLAGS.surface_thres)
  File "/app/alpha-analysis/get_good_inter_pae.py", line 75, in run_and_summarise_pi_score
    filtered_df = pd.read_csv(os.path.join(subdir,csv_files[0]))
IndexError: list index out of range

```
This second error can appear if the threshold cutoff is too low, but I also received this error with --cutoff=500 with candidates below this threshold. 

These errors appear to be at random on my setup, as I have had identical runs succeed or fail (even with deleting the resulting pi_score folders between runs). The chance of getting this error increases with the number of candidate proteins processed: I was unable to complete runs of 700 candidate proteins; runs of 14 candidate proteins always finished without error; runs of 60-90 finished successfully about 70% of the time. Successful runs produced identical resulting .csv files. Good luck to anyone dealing with this issue; it was a difficult one to de-bug.
