### ISSUE TITLE
Generating the MSAs by Colabfold

### ISSUE THREAD

**Issue by Pooryamb** [KosinskiLab/AlphaPulldown#111]
Hi,

Thanks for your amazing project. 
I have generated the MSA profile for a set of proteins using ColabFold and want to use your program's pulldown mode on them. 
I was wondering what the needed parameters are for running the ColabFold locally. More specifically, should we use env_db for MSA generation? Or do we just need to use UniRef for making the profiles?

I have generated the MSA profiles by selecting the env_db database. I got two a3m files for my proteins named: 

- bfd.mgnify30.metaeuk30.smag30.a3m
- uniref.a3m

Which a3m file should be used for downstream steps?

Thanks in advance

**Comment by henrywotton** [comment]
Hi @Pooryamb,

Thanks for your interest in our package but unfortunately, how to run colabfold locally is beyond the scope of this package. Please refer to colabfold's page for detailed istructions: https://github.com/sokrypton/ColabFold

I have installed mmseqs, colaba_search, and colabfold databases locally myself then it finished with 1 a3m for each protein. I think the env_db directories are created if you choose to run mmseqs2 remotely using their server. When you run remotely, AlphaPulldown will take care of the a3m files and generate features automatically for you. When I myself run colab_search locally, I did not see these files or env_db

I hope this may be helpful.

Cheers

**Comment by henrywotton** [comment]
Hi, just writing to check if this has been solved?

**Comment by Pooryamb** [comment]
Thanks for the follow up.
I generated my MSAs using both EnvDB and UniRef. I don't know which database is used by the ColabFold by default, when it predicts PPI. Yet, as selecting the EnvDB maskes the MSAs more comprehensive, I used UniRef too.
Yet, I am a little bit confused. Because ColabFold first generates the MSA by searching against UniRef, and then against EnvDB. So, I expected to see Env MSAs are larger than UniRef alignments. Yet, the file sizes tell the opposite. I have asked my question on github of ColabFold. Waiting for their reply.
[Link to my question](https://github.com/sokrypton/ColabFold/issues/425#issue-1647882579)
As my question is more related to ColabFold, feel free to close this thread.

**Comment by henrywotton** [comment]
Hi,

Really sorry I'm not familiar with the databases used by ColabFold and I couldn't help you with this here. AlphaPulldown only integrated their codes as an alternative. I hope colabfold guys will provide you with more detailed explanations.

Cheers

**Comment by fourier20laplace** [comment]
may I ask the command for colabfold_search? something like this?
`MMSEQS_IGNORE_INDEX=1 colabfold_search \
  --use-env 1 \
  --use-templates 1 \
  --db-load-mode 2 \
  --db2 pdb100_230517 \
  --mmseqs ${MMSEQS_PATH}/bin/mmseqs \
  --threads 48 \
  ${INPUTFILE} \
  ${DATABASE_PATH} \
  ${OUTPUTDIR}`

 > bfd.mgnify30.metaeuk30.smag30.a3m

however with that, I can't find the > bfd.mgnify30.metaeuk30.smag30.a3m in the results.
I’d really appreciate any guidance on this.
