### ISSUE TITLE
About reduced db

### ISSUE THREAD

**Issue by Aaronro16** [KosinskiLab/AlphaPulldown#112]
Hi, sorry but this is not an issue report, I just want to ask if AlphaPulldown can run with reduced db of AlphaFold? Cause I want to run it for a little project in my desktop PC.

Thanks a lot, but I didn't find where ask this in another section.

**Comment by henrywotton** [comment]
Hi @Aaronro16 ,

AlphaPulldown inherits all flags from AlphaFold. I think you could add ```--db_preset=reduced_dbs``` in your commands and it should use reduced db instead.

Cheers

**Comment by henrywotton** [comment]
Hi @Aaronro16 just writing to double check if this has been solved?

**Comment by Aaronro16** [comment]
Hi, yes... sorry I forget to close it (new on this)
