### ISSUE TITLE
Recommend more specific version of `PDBfixer`

### ISSUE THREAD

**Issue by deniskristak** [KosinskiLab/AlphaPulldown#123]
Hello,
as part of the [Easybuild](https://easybuild.io) project, I am attempting to install this software from source (without using Conda).
Putting this aside, I still think your Readme could use a small tweak. I've read the requirements listed in your `Readme` file. There, it is explicitely stated that `OpenMM` version 7.5.1 should be used.
However, `pdbfixer` does not have an exact version, implying that any should work. This is not the case, however.
I installed `OpenMM 7.5.1`, where the python command `import openmm` is not available, but `pdbfixer` tries to use this command starting from version `1.8`.
I would therefore recommend setting maximum required version of `pdbfixer` to `1.7`.
Attaching screenshots from `OpenMM` and `pdbfixer` release notes.
Thanks, have a good day.
![Screenshot from 2023-04-17 14-27-05](https://user-images.githubusercontent.com/35582739/232486403-be64491c-a7f2-47e4-bb8d-16d399100cd3.png)
![Screenshot from 2023-04-17 14-27-39](https://user-images.githubusercontent.com/35582739/232486415-9ed11eb0-377f-4aa2-9cb4-34eea0187324.png)

**Comment by henrywotton** [comment]
Hi @deniskristak 

Many thanks for your advice. We'll update the instructions later.

Cheers
