### ISSUE TITLE
How to evaluate interaction for more than two proteins

### ISSUE THREAD

**Issue by SchwarzMarek** [KosinskiLab/AlphaPulldown#125]
Hello,
thanks again for very nice pipeline.

I would like to ask a question about how to evaluate prediction for proteins in style of A-A-B.
After processing with the singularity image I have "predictions_with_good_interpae.csv" file where I have multiple rows for one prediction (pi_scores and others). 
Are there any guidelines on how to evaluate the prediction?

I'm confused about the "interface" vs "chains" description, as I've thought that chains must be part of interface (compare rows 1, 2, and 4). 
Secondly, why I have so many rows? I would expect that I' would get one row per prediction, or per protein pair. But there is more of them (Should the output be one row per extracted interface, if so, why I see some rows apparently duplicated?).

I hope that the attached file is uploaded correctly (.csv format). 

[example_AAB_output.csv](https://github.com/KosinskiLab/AlphaPulldown/files/11294704/example_AAB_output.csv)

I'm aware that I'm using old version of evaluation image (wanted to use it until end of the project).
I can share the actual prediction data privately, if needed. 

Thank you

**Comment by henrywotton** [comment]
Hi @SchwarzMarek 
Sorry for the confusions and thanks for your comments, I should update the singularity image.

Regarding your first question, "interface" was detected by CCP4 suite and "chains" was detected by PI-score programme. Sorry I'm not very sure how these 2 are different in your case but I guess there may be a mistake in the labelling codes. "interface" and "chains" should be identical in your case. 

As for the second question, if there are more than 2 chains in the PDB file, then it will duplicate the rows. In other words, the programme treats A-B and B-A as 2 different interfaces, even though in reality, they are the same. There is a permutation step at the beginning to generate all possible chain pairs before starting the analysis. It looks like a combination step should be used instead.

I'll look into the codes and hopefully publish a newer version of the image later. 

Yours 
Dingquan

**Comment by SchwarzMarek** [comment]
Hi @henrywotton ,
Thank you for the response. I now understand why there are two chain-specification columns.

I'll try to use more recent evaluation code to see if anything changed.
Thank you

**Comment by SchwarzMarek** [comment]
Hello @henrywotton 
Sure, I can share the files, can you write me an e-mail to marek.schwarz <at> biomed.cas.cz, so I can share them privately?

Thank you

**Comment by SchwarzMarek** [comment]
Thanks the authors for support.
