### ISSUE TITLE
How to run Pulldown on defined "candidates" list without AlphaFold Directory

### ISSUE THREAD

**Issue by HollyAnd** [KosinskiLab/AlphaPulldown#127]
Hello!

Thank you so much for this pipeline. I was wondering if there was a way to run the Pulldown mode without having to use the AlphaFold directory. I my bait protein sequence and a list of candidate protein sequences to test it against, so I don't need the program to search through the directory for candidates. Sorry, my coding skills are limited so troubleshooting has been challenging. 

Thank you,
Holly

**Comment by henrywotton** [comment]
I'm sorry but your description is really confusing. What do you mean by AlphaFold directory? Pulldown mode does not go through the whole directory for candidates but rather follow the instructions give by the ```protein_lists``` argument. I don't really get the question.
