### ISSUE TITLE
np.int and np.object error

### ISSUE THREAD

**Issue by remybonnav** [KosinskiLab/AlphaPulldown#129]
Am I the only one that get the "np.int" deprecated error and "np.object" deprecated error?
I had to change np.int by int and np.object by object in some .py scripts from alphafold library.

I could not find any mentio nof the issue in alphafold github or here.

**Comment by henrywotton** [comment]
Sorry I haven't seen anything like this. Maybe you could paste the full error report here? I think these are only warning rather than errors.

**Comment by remybonnav** [comment]
I don't have the report, I need to make a new install to rerun because I didi not save the .py files that I modified to make the script run. It was really blocking the script, I had to modify np.int to int and np.object to object in the .py files from alphafold to make it work.

**Comment by henrywotton** [comment]
Hi,

Just checking if there's any followups?

**Comment by henrywotton** [comment]
Hi,

Just checking if it's solved for you?

**Comment by remybonnav** [comment]
Haven't tried yet,

The machine

I reinstalled in a new environment using jax-cpu but i did not have time to
try.. Let see if it works when I can have access again to the machine on
which I have the alphafold database.

**Comment by henrywotton** [comment]
Hi @remybonnav 

Just checking if it's solved?

**Comment by henrywotton** [comment]
Hi @remybonnav

Just checking if it's solved?

**Comment by remybonnav** [comment]
I did not try to reinstall.
You can clos the issue as this can be solved by modifying some scripts as
written in my first post.

Best
