### ISSUE TITLE
Independently run MSA prediction?

### ISSUE THREAD

**Issue by remybonnav** [KosinskiLab/AlphaPulldown#130]
Hi,

Can we run MSA prediction on some targets without specifying a bait?
For example I already run MSA prediction for my bait with some targets but now I want new targets.

Also maybe you should open a Discussion section on the repo to avoid people like me to flood your "issue" section with some questions. ;)

**Comment by henrywotton** [comment]
Hi @remybonnav 

Naturally running MSA doesn't require any baits or candidate information. As written in our manual, for msa feature calculations, you only need to provide a fasta file with all the proteins of your interest. 

Cheers

**Comment by remybonnav** [comment]
Thank you :)
