### ISSUE TITLE
Running on low VRAM (8GB) GPU

### ISSUE THREAD

**Issue by remybonnav** [KosinskiLab/AlphaPulldown#132]
I am trying to run pulldown on a 8GB GPU.
but I get an error (see below).
By checking AkphaFold github, it seems oen could reduce VRAM usage using arguments for JAx found here
https://jax.readthedocs.io/en/latest/gpu_memory_allocation.html#gpu-memory-allocation

But I cannot use these arguments with AlphaPulldown.

Is there a way to run pulldown on low VRAM?

Here is the error

I0514 12:24:47.452025 139740990670656 xla_bridge.py:353] Unable to initialize backend 'tpu_driver': NOT_FOUND: Unable to find driver in registry given worker:
I0514 12:24:47.737356 139740990670656 xla_bridge.py:353] Unable to initialize backend 'rocm': NOT_FOUND: Could not find registered platform with name: "rocm". Available platform names are: CUDA Interpreter Host
I0514 12:24:47.737852 139740990670656 xla_bridge.py:353] Unable to initialize backend 'tpu': module 'jaxlib.xla_extension' has no attribute 'get_tpu_client'
I0514 12:24:47.738004 139740990670656 xla_bridge.py:353] Unable to initialize backend 'plugin': xla_extension has no attributes named get_plugin_device_client. Compile TensorFlow with //tensorflow/compiler/xla/python:enable_plugin_device set to true (defaults to false) to enable this.
2023-05-14 12:24:49.060530: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:767] failed to alloc 17178951680 bytes unified memory; result: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2023-05-14 12:24:50.177186: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:767] failed to alloc 15461056512 bytes unified memory; result: CUDA_ERROR_OUT_OF_MEMORY: out of memory

**Comment by henrywotton** [comment]
I'm sorry but XLA arguments are set by yourself as environmental arguments in your bash scripts. It has nothing to do with AlphaFold or AlphaPulldown. I'd recommend checking the documents on how XLA works and communicate with relevant IT support.  We really cannot help you with your IT infrastructure.
