### ISSUE TITLE
Adding pulldown mode running on CPU

### ISSUE THREAD

**Issue by remybonnav** [KosinskiLab/AlphaPulldown#133]
AlphaFold can run on CPU using  the FLAG --use_gpu=False

The flag does not work for run_multimer_jobs.py
Is it possible to add this feature? We don't have a GPU biffy enough and I would like to try to run on CPU.

Thanks in advance.

**Comment by henrywotton** [comment]
Hi,

Just checking if it's solved for you?

**Comment by remybonnav** [comment]
Hi, so on the same machine I reinstalled in a new environnment but using 
pip install --upgrade "jax[cpu]"
and pip install tensorflow-cpu==2.9.0 
And it is now working on the CPU. First prediction is running now ;)
