### ISSUE TITLE
af2plots missing and not installed?

### ISSUE THREAD

**Issue by jkosinski** [KosinskiLab/AlphaPulldown#137]
It seems af2plots are misising now in the repo. Here:
https://github.com/KosinskiLab/AlphaPulldown/tree/main/alphapulldown/analysis_pipeline
There are two folders named af2plots and none can be accessed. They are both empty when cloning locally.

Also it seems af2plots is not installed when installing with pip, can't find them in site-packages and notebook crashes for me with ModuleNotFoundError: No module named 'af2plots'

**Comment by remybonnav** [comment]
The jupyter notebook created does not work because I get the error "analysis_pipeline not found".
Did I miss an install somewhere?

**Comment by jkosinski** [comment]
"analysis_pipeline not found" sounds like sth different as I don't get that error (I do get analysis_pipeline installed but without af2plots). Let's see whether you still get this error after @henrywotton fixes this one.

**Comment by henrywotton** [comment]
Dear both @jkosinski  @remybonnav 

I've re-organised the folder structure of the submodules and published a new realease. Version 0.30.6 now should resolve the af2plots problem you saw when exeucuting the jupyter notebook

Cheers
