### ISSUE TITLE
seq_index Error

### ISSUE THREAD

**Issue by mbaddoo** [KosinskiLab/AlphaPulldown#140]
Hello, as per the example provided for running AlphaPulldown on a computer cluster in parallel, I submitted the SLURM script with the following line:

create_individual_features.py --fasta_paths=baits.fasta,candidates.fasta --data_dir=/${HPC_ALPHAFOLD_REF}/  --save_msa_files=False --output_dir=/PATH/TO/features --use_precomputed_msas=False --max_template_date=2050-01-01 --skip_existing=True --seq_index=$SLURM_ARRAY_TASK_ID

This job failed, however with the error message below:

FATAL Flags parsing error: flag --seq_index=: invalid literal for int() with base 10: ''
Pass --helpshort or --helpfull to see help on flags.

Can you please advise on the proper input for '--seq_index'?

Thank you!

**Comment by henrywotton** [comment]
Hi,

It's likely that you have forgotten to add ```#SBATCH --array=1-10```  for example if there are 10 sequences in your fasta file(s). Could you show us the full bash script you used? 

Cheers

**Comment by henrywotton** [comment]
Hi @mbaddoo 
Just checking if this has been solved?

**Comment by mbaddoo** [comment]
Hello-

Thank you for your reply and my apologies for the delay.  Indeed, that line was missing from by SLURM script. Below is the script I used.  I will make the edit and give it a try.

#!/bin/bash
#SBATCH --account=account
#SBATCH --qos=account-b
#SBATCH --job-name=AlphaPulldown
#SBATCH --time=48:00:00
#SBATCH -e create_individual_features_%A_%a_ErrorLog.txt
#SBATCH -o create_individual_features_%A_%a_OutputLog.txt
#SBATCH ***@***.***
#SBATCH --mail-type=ALL
#SBATCH --nodes=1
#SBATCH --ntasks=8
#SBATCH --cpus-per-task=10
#SBATCH --mem=64000

#######ABOUT THE JOB#######
#This script uses fasta files to compute MSA and template features
module load alphapulldown/0.30.5

create_individual_features.py --fasta_paths=baits.fasta,candidates.fasta --data_dir=/${HPC_ALPHAFOLD_REF}/  --save_msa_files=False --output_dir=/PATH/TO/mbaddoo/features --use_precomputed_msas=False --max_template_date=2050-01-01 --skip_existing=True

Thank you!

Melody Cunningham Baddoo
Sr. Research Scientist
Tulane Cancer Center
Cancer Crusaders NGS Analysis Core/UF-Tulane NIH P01 core B
1700 Tulane Avenue, Room 810
New Orleans, LA 70112
504-988-1345
***@***.***

________________________________________

**Comment by mbaddoo** [comment]
> Hi @mbaddoo Just checking if this has been solved?

Hello. Yes, this issue has been solved.  

Thanks!

**Comment by mbaddoo** [comment]
Thanks so much!  Issue solved.  Needed to include 

> 

Thanks so much!  This solves the issue. 

mbaddoo
