### ISSUE TITLE
The jupyter notebook created does not work because I get the error "analysis_pipeline not found".

### ISSUE THREAD

**Issue by mbaddoo** [KosinskiLab/AlphaPulldown#144]
The jupyter notebook created does not work because I get the error "analysis_pipeline not found".
Did I miss an install somewhere?

_Originally posted by @remybonnav in https://github.com/KosinskiLab/AlphaPulldown/issues/137#issuecomment-1556265441_

**Comment by henrywotton** [comment]
> Hello!  
> 
> 
> 
> Did you ever get this resolved?  I am met with the same error "analysis_pipeline not found", specifically, 
> 
> ModuleNotFoundError: No module named 'analysis_pipeline'.
> 
> 
> 
> I appreciate any advice you can offer. 
> 
> Best-
> 
> mbaddoo
> 
> 

Hi @mbaddoo 

Sorry it persists but I've released an update to fix this after this issue was reported. Could you install the latest version and give it another try? 

Cheers

**Comment by henrywotton** [comment]
Hi, 
No not at all. Once you've updated the package and you could just restart the jupyter lab and run the cells within the notebook.

Hope it helps.

Cheers

**Comment by mbaddoo** [comment]
Hello-
This is very helpful! Thanks so much!
Best-
mbaddoo

**Comment by mbaddoo** [comment]
Hello again-

I requested the most recent version of AlphaPulldown be installed and then executed the following command in the models directory:

module load alphapulldown/0.30.6

create_notebook.py --cutoff=5.0 --output_dir=/PATH/TO/mbaddoo/models

I then downloaded output.ipynb file to my local computer ('models' folder had already been downloaded following attempt with v. 0.30.5).  When I next attempted 'jupyter notebook output.ipynb', I was still met with the aforementioned error (see attached screenshot).  I appreciate any help you could offer.

Thanks!

mbaddoo


_______________________________________

**Comment by mbaddoo** [comment]
Hello-
I followed the instructions to install AlphaPulldown locally and am not able to get it working.  Might you be able to offer any advice? I attempted install on 2 different MacBook Pro computers, one with an intel chip and the other with an M1 chip.  (See attached terminal output.)
I ran AlphaPulldown on a compute cluster, downloaded the output, and now need to view the results in the created jupyter notebook.  
I appreciate any assistance you could offer.

**Comment by henrywotton** [comment]
Hi,

sorry these conflicts from your output file are really overwhelming and I've never seen such a thing. This issue with your installation might be caused by your gcc libraries configuration on your Macbook Pro.  I'm afraid this is beyond our expertise and what this package can handle. 

Perhaps you could check out [mamba](https://github.com/mamba-org/mamba)? It does the same thing as anaconda except it goes easy on these environment conflicts. 

Cheers

**Comment by mbaddoo** [comment]
Hello-
Thanks so much for all your help!  I appreciate it.  Will check out mamba.
Best-
mbaddoo
