### ISSUE TITLE
Updating AlphaPulldown

### ISSUE THREAD

**Issue by mpm896** [KosinskiLab/AlphaPulldown#147]
Hi,

Rather simple question, but to update to the latest version is it necessary to reinstall from scratch? Or is there a simpler way to update? Thanks.

Best,
Matt

**Comment by henrywotton** [comment]
Hi Matt,

I don't think reinstalling from scratch is necessary and you could, within the created conda env, firstly ```pip uninstall alphapulldown``` just in case some files might be messed up, then ```pip install alphapulldown```in the next step.
