### ISSUE TITLE
Add info to the manual that relax is not run

### ISSUE THREAD

**Issue by jkosinski** [KosinskiLab/AlphaPulldown#15]

**Comment by dingquanyu** [comment]
Relaxation do run. That's how those ranked_xx.pdb are created. 
https://github.com/KosinskiLab/AlphaPulldown/blob/2443672127ef31e32fcf2353c6f4784a37a1d9f3/alphapulldown/predict_structure.py#L236-L252

**Comment by jkosinski** [comment]
Sorry, I wanted to say that "add info that **by default** relax is not run"
