### ISSUE TITLE
Alphafold databases when running mmseqs2 locally 

### ISSUE THREAD

**Issue by susiegriggo** [KosinskiLab/AlphaPulldown#152]
Thanks for developing AlphaPulldown! I'm excited to try using it 

I would like to use mmseqs2 locally as outlined in the mmseqs2_manual, as I have already used colab_search to generate lots of .a3m files for the proteins I'm interested in, and it doesn't make sense to compute them again. I've been able to run the rename_colab_search_a3m.py script fine and rename my a3m files. 

I notice that when I try running the **create_individual_features.py** script I still need to specify a path to the alphafold databases **(--data_dir=<path to alphafold databases>**)  but this doesn't really make sense to me as I've already generated my .a3m files using the colabfold databases. Plus, the colabfold databases are different to the AlphaFold databases. 

Would it be possible to run  **create_individual_features.py**  without the alphafold databases if mmseqs2 has been run locally?

**Comment by dingquanyu** [comment]
Hi @susiegriggo 

Thanks for your interests in our package. I'm sorry currently, under mmseqs2 mode, the PDB70 database is still required for calculating template alignments so that's why the data_dir was required. Would you mind downloading just the pdb70 to your data_dir for now if downloading the entire Alphafold datasets takes too much time and space?

Yours
Dingquan

**Comment by susiegriggo** [comment]
Hi Dingquan, 

I'm happy to give that a go. 

I've downloaded just the PDB70 database and placed it in a directory (alphafold_db_reduced) which I then parse to data_dir when running the create_individual_features.py script. When I run this I get the error: 

raise ValueError(f'Could not find CIFs in {self._mmcif_dir}') 
ValueError: Could not find CIFs in ~/alphafold_db_reduced/pdb_mmcif/mmcif_files


my data_dir has a structure 
-> alphafold_db_reduced 
     -> pdb70
          -> <files in pdb70 database> 
         

and this was command: 
create_individual_features.py  --fasta_paths=example_1_sequences.fasta --data_dir=alphafold_db_reduced --output_dir=output_dir/ --skip_existing=False --use_mmseqs2=True --max_template_date=2023-01-01

Thanks!

**Comment by dingquanyu** [comment]
Hi,

I see. I guess under your pdb70 folder, there's a pdf_mmcif subfolder? It looks like this pdb_mmcif folder should be moved directly under your alphaFold_db_reduced folder.

Cheers

**Comment by susiegriggo** [comment]
There isn't a pdb_mmcif folder but there is a pdb70_from_mmcif_200401.tar.gz  file 

This is whats in the pdb70 folder:
- md5sum 
- pdb70_cs219.ffdata
- pdb70_hhm.ffdata
- pdb70_a3m.ffdata
- pdb70_cs219.ffindex
- pdb70_hhm.ffindex
- pdb70_a3m.ffindex
- pdb70_from_mmcif_200401.tar.gz 
- pdb_filter.dat
- pdb70_clu.tsv 
- pdb70_from_mmcif_200401.tar.gz.aria2

Alphafold say though that pbd_mmcif is a separate directory that contains 199,000 .cif files 
(https://github.com/deepmind/alphafold)

**Comment by dingquanyu** [comment]
I see. Sorry I was wrong about pdb70. As instructed by AlphaFold repo, it should be the pdb_mmcif. Could you follow their instructions and download pdb_mmcif?

**Comment by susiegriggo** [comment]
Great, I just tried that and it seems to be working now. Thanks! 

Are there any plans to eventually be able to run AlphaPulldown using only mmseqs/colabfold?

**Comment by jkosinski** [comment]
@dingquanyu I think we should at some point! @susiegriggo could you start a new issue asking for this feature to add it to our to-do list?

**Comment by susiegriggo** [comment]
Sure thing! Thanks, I just started a new issue
