### ISSUE TITLE
Save mmCIF output files

### ISSUE THREAD

**Issue by jkosinski** [KosinskiLab/AlphaPulldown#153]
By updating to the new AlphaFold version:
https://github.com/deepmind/alphafold/commit/6c4d833fbd1c6b8e7c9a21dae5d4ada2ce777e10

The mmCIF files store global metrics in the heading - very convenient!

**Comment by DimaMolod** [comment]
standard output mmCIFs don't store metrics in the heading, but they will after converting to modelCIF format
