### ISSUE TITLE
Run using only mmseqs/colabfold 

### ISSUE THREAD

**Issue by susiegriggo** [KosinskiLab/AlphaPulldown#156]
Run create_individual_features.py and run_multimer_jobs.py using colabfold databases rather than the AlphaFold databases in mmseqs2 mode

**Comment by KeaunAmani** [comment]
I second this, would be far more convenient to have an option to utilize the ColabFold mmseqs2 API.

**Comment by jkosinski** [comment]
For the record, colabfold mmseqs2 is already supported for MSA generation (https://github.com/KosinskiLab/AlphaPulldown/blob/main/mmseqs2_manual.md), what is meant here is to also support remote template search using mmseqs2.

**Comment by susiegriggo** [comment]
Yeah. To support remote template search using mmseqs2 and make use of the ColabFold databases for predicting protein structures (run_multimer_jobs.py)

**Comment by Amin-Debabeche** [comment]
Therefore, there is no necessity of adding the argument on local AF database for both create_individual_features and run_multimer_jobs, right?
