### ISSUE TITLE
KeyError: 'P78344.pkl'

### ISSUE THREAD

**Issue by RogerLang** [KosinskiLab/AlphaPulldown#161]
Hi, when I was running script
`run_multimer_jobs.py --mode=pulldown \
    --num_cycle=3 \
    --num_predictions_per_model=1 \
    --output_path=result_dir2 \
    --data_dir=$PROGRAM/data  \
    --protein_lists=baits.txt,candidates_shorter.txt \
    --monomer_objects_dir= $workDR/step1/result_dir`, 
An error occurs, and the program stopped. 
`target_path = monomer_dir_dict[f"{protein_name}.pkl"]
KeyError: 'P78344.pkl'`
And there is no other errors.

I was repeating  the example the shorter one you provided, and all files were placed correctly. 
And step 1 run successfully.

**Comment by dingquanyu** [comment]
Hi,

Could you find the corresponding P78344.pkl in your $workDR/step1/result_dir ? Maybe feature calculation failed for this protein at some point. Plus perhaps you could remove the space between ```=``` and your ```$workDR/step1/result_dir``` in the command.

Cheers

**Comment by RogerLang** [comment]
Hi, 

I found that the error is cause by the blank space between `=` and `$workDR/step1/result_dir`.

Thanks
