### ISSUE TITLE
"af2_plots @ b5b96c8" seems inaccessible

### ISSUE THREAD

**Issue by kimcho452** [KosinskiLab/AlphaPulldown#164]
Hi, and thank you for the wonderful program.

I've been trying to follow the installation and developing process but it seems that I can't download the 'af2_plots' directory.

After entering "git clone --recurse-submodules git@github.com:KosinskiLab/AlphaPulldown.git", 
instllation fails with the following error messages;

###
Cloning into '/home/gistxray/AlphaPulldown/alphapulldown/analysis_pipeline/af2_plots'...
git@git.embl.de: Permission denied (publickey).
fatal: Could not read from remote repository.
###

I tried clicking the 'af2_plots' link on github depository too and it's also not accessible.

I have checked my SSH agent running and other submodules ([alphafold @ 7422507], [ColabFold @ 2267166]) are readily accesible.

Could you give it a look please?

Thank you in advance.

Kim

----------------------Added--------------
I managed to clone the [alphafold] and [ColabFold] repositories manually.

I found an old directory of [af2_plots] in local and it seems to work fine.

Still, the [af2_plots] repository from your github is not accesible for me...(probably because it's in git.embl.de)

**Comment by dingquanyu** [comment]
Thanks for your suggestion and I will make this repo availiable to public later on and let you know. 

Yours
Dingquan

**Comment by jx-soong** [comment]
Hi. I'm facing the same issue as Kim too. I tried to get af2plots from another resource (https://gitlab.com/gchojnowski/af2plots/-/tree/main?ref_type=heads) and it failed as well.

Can you please take a look at it?

Thank you for your time.

Soong

**Comment by dingquanyu** [comment]
Hi @jx-soong 

Sorry this module hasn't been made available to the public yet. I aim to move it to github asap. The Af2Plot package is only used in the jupyternotebook so please feel free to modify other parts of the programme. 

Yours
Dingquan

**Comment by dingquanyu** [comment]
Hi @kimcho452 and @jx-soong

I have update the .gitmodule with the newer https links. Could you freshly clone AlphaPulldown repo and update the submodules? Now all submodules should be cloned after you git submodule update 

Yours
Dingquan

**Comment by jx-soong** [comment]
Hi Dingquan,

Everything is okay now. 

Thank you so much.

Soong
