### ISSUE TITLE
error encountered with alpha-analysis.sif

### ISSUE THREAD

**Issue by mbaddoo** [KosinskiLab/AlphaPulldown#169]
Hello!  
Thanks so much for this package!  I am enjoying learning and using it.  Recently, I was granted gpu access and was able to run the program(v0.30.7) with a very large aa sequence (>2000aa).  However, I encountered an error when attempting to run the singularity image to generate the CSV table.  At first we thought that the issue was due to the copy of the .sif that I downloaded with the previous version (0.30.5) of the program, but after downloading another copy of the .sif, it resulted in the same error.  

Is this something you can help us resolve, please? My error log is attached.  

Kind regards-
mbaddoo
[analysis_sif_7549469_4294967294_ErrorLog.txt](https://github.com/KosinskiLab/AlphaPulldown/files/12443606/analysis_sif_7549469_4294967294_ErrorLog.txt)

**Comment by dingquanyu** [comment]
Hi @mbaddoo,
It looks like your jax wasn't correctly installed. Could you check your jax version within you alphapulldown conda env? 

Yours
Dingquan

**Comment by dingquanyu** [comment]
Hi,

Just checking if it's solved?

**Comment by mbaddoo** [comment]
Hello-

Thanks for your email. Not yet. This instance is maintained on an HPC at UFL and they are dealing with a hurricane.

Thanks-

mbaddoo

On Aug 30, 2023, at 05:41, Dingquan Yu ***@***.***> wrote:

﻿
External Sender. Be aware of links, attachments and requests.

Hi,

Just checking if it's solved?

**Comment by mbaddoo** [comment]
Hello-

Issue is resolved.  I was informed that it required a new install of alphapulldown that includes jax version 0.3.25
as specified in the documentation. I had to re-run the predict structures step (run_multimer_jobs.py).  
 
Thanks again for this software.

Best-

mbaddoo

**Comment by tclin422** [comment]
I got the same issue, my jax version is 0.3.25. 

Any suggestions?
[analysis_sif.txt](https://github.com/KosinskiLab/AlphaPulldown/files/12565784/analysis_sif.txt)

**Comment by mbaddoo** [comment]
Hello tclin422-
This issue was not resolved by me but by the HPC team.  A new install of alphapulldown with jax version 0.3.25 fixed the issue but required that I re-run the run_multimer_jobs.py script.  
I hope this helps. 
mbaddoo
