### ISSUE TITLE
Output.ipynb does not work

### ISSUE THREAD

**Issue by Amin-Debabeche** [KosinskiLab/AlphaPulldown#170]
When running the cells of the jupyter notebook, the display_pae_plots function works properly for every complexes but **parse_results** return an error that I am not able to resolve. Same for **parse_results_colour_chains**

`RuntimeError                              Traceback (most recent call last)
Cell In[18], line 1
----> 1 parse_results('[/home/debabech/Pizza/peptide_docking/AFPull/output_prediction/Chain_1_and_Sequence_36](https://vscode-remote+ssh-002dremote-002bslater.vscode-resource.vscode-cdn.net/home/debabech/Pizza/peptide_docking/AFPull/output_prediction/Chain_1_and_Sequence_36)')

File [~/miniconda3/envs/AlphaPulldown/lib/python3.8/site-packages/analysis_pipeline/af2_3dmol.py:65](https://vscode-remote+ssh-002dremote-002bslater.vscode-resource.vscode-cdn.net/home/debabech/Pizza/peptide_docking/AFPull/output_prediction/~/miniconda3/envs/AlphaPulldown/lib/python3.8/site-packages/analysis_pipeline/af2_3dmol.py:65), in parse_results(output, color, models, multimer)
     63 _ph, _symm = read_ph(fn)
     64 if len(ph_array) > 0:
---> 65     _s = superpose.least_squares_fit(
     66         ph_array[0].atoms().extract_xyz(),
     67         _ph.atoms().extract_xyz(),
     68         method=["kearsley", "kabsch"][0],
     69     )
     70     rtmx = matrix.rt((_s.r, _s.t))
     71     _ph.atoms().set_xyz(new_xyz=rtmx * _ph.atoms().extract_xyz())

File [~/miniconda3/envs/AlphaPulldown/lib/python3.8/site-packages/scitbx/math/superpose.py:63](https://vscode-remote+ssh-002dremote-002bslater.vscode-resource.vscode-cdn.net/home/debabech/Pizza/peptide_docking/AFPull/output_prediction/~/miniconda3/envs/AlphaPulldown/lib/python3.8/site-packages/scitbx/math/superpose.py:63), in least_squares_fit.__init__(self, reference_sites, other_sites, method)
     61 self.r = None
     62 if method == "kearsley":
---> 63   self.r = kearsley_rotation(
     64     reference_sites-self.reference_shift,
     65     other_sites-self.other_shift)
     66 if method == "kabsch":
     67   self.r = kabsch_rotation(
     68     reference_sites-self.reference_shift,
...
---> 19   return matrix.sqr(superpose_kearsley_rotation(
     20     reference_sites=reference_sites,
     21     other_sites=other_sites))

RuntimeError: scitbx array_family range error
Output is truncated. View as a [scrollable element](command:cellOutput.enableScrolling?28bccb39-c3e9-49cd-b939-f9e3d7122ece) or open in a [text editor](command:workbench.action.openLargeOutput?28bccb39-c3e9-49cd-b939-f9e3d7122ece). Adjust cell output [settings](command:workbench.action.openSettings?%5B%22%40tag%3AnotebookOutputLayout%22%5D)...`

**Comment by DimaMolod** [comment]
Not relevant anymore because superpose functions have been changing. Closing...
