### ISSUE TITLE
Database description difference APD vs. AF

### ISSUE THREAD

**Issue by SchwarzMarek** [KosinskiLab/AlphaPulldown#175]
Hi,
the database description in the AlphaPulldown readme doesn't match the database description in the AlphaFold link.

Found differeces:
- mgy_clusters_2018_12 vs mgy_clusters_2022_05
- uniclust30 vs uniref30

Should I use the AF databases or the APD described (with latest APD 0.30.7 release)?

Thank you
Best
Marek

**Comment by dingquanyu** [comment]
Hi,

Sorry we haven't update the layouts in our README but please stick with the requirements in the AlphaFold directory. 

Yours
Dingquan

**Comment by SchwarzMarek** [comment]
Thanks for the info.
