### ISSUE TITLE
Add mmseqs2 info

### ISSUE THREAD

**Issue by jkosinski** [KosinskiLab/AlphaPulldown#177]
Add:
- in mmseqs2_manual.md, warning that mmseqs2 should be use only for small number of sequences to not overload the remote mmseqs2 server
- in mmseqs2_manual.md, request the ColabFold paper https://www.nature.com/articles/s41592-022-01488-1
- at https://www.embl-hamburg.de/AlphaPulldown/, request the ColabFold paper https://www.nature.com/articles/s41592-022-01488-1
- add request to cite ColabFold paper to log when using mmseqs2 server

**Comment by DimaMolod** [comment]
convert a3m to a2m with treformat.pl (hhsuite) to make it readable for hmmer

**Comment by dingquanyu** [comment]
by 
at https://www.embl-hamburg.de/AlphaPulldown/, request the ColabFold paper https://www.nature.com/articles/s41592-022-01488-1

You mean add ColabFold as one of the references on AlphaPulldown's EMBL website?

**Comment by dingquanyu** [comment]
"add request to cite ColabFold paper to log when using mmseqs2 server" already solved here: https://github.com/KosinskiLab/AlphaPulldown/blob/2443672127ef31e32fcf2353c6f4784a37a1d9f3/alphapulldown/objects.py#L187

**Comment by dingquanyu** [comment]
"In mmseqs2_manual.md, request the ColabFold paper https://www.nature.com/articles/s41592-022-01488-1" fixed in [2d5a7b6](https://github.com/KosinskiLab/AlphaPulldown/commit/2d5a7b6e2056dac69b76939d89e1cb35e5cf19f6)

**Comment by jkosinski** [comment]
> by at https://www.embl-hamburg.de/AlphaPulldown/, request the ColabFold paper https://www.nature.com/articles/s41592-022-01488-1
> 
> You mean add ColabFold as one of the references on AlphaPulldown's EMBL website?

Yes, sorry missed a word in the sentence

**Comment by dingquanyu** [comment]
Done updating the webpage.
