### ISSUE TITLE
Duplicated to_bio?

### ISSUE THREAD

**Issue by jkosinski** [KosinskiLab/AlphaPulldown#179]
You seem to invoke to_bio twice in this function, here:
https://github.com/KosinskiLab/AlphaPulldown/blob/fed7fc3b0d70925e86c3ef56eff378ead5f7fef1/alphapulldown/create_fake_template_db.py#L184
and within extract_seqs_from_cif().
Possibly more efficient to create structure once and pass structure object to extract_seqs_from_cif

**Comment by DimaMolod** [comment]
not really since we need to parse seqres from file anyway. There is also a bug that seqres is not currently parsed from pdb, so I'd change the function to smth like this:
`
def extract_seqs(template, chain_id):
    """
    Extract sequences from PDB/CIF file, if SEQRES records are not present,
    extract from atoms
    o chain id - chain id
    o file_path - path to the PDB/CIF file
    Return:
        o list of tuples: (chain_id, sequence)
    """
    seqs = []
    # Parsing SEQRES
    if template.endswith('.pdb'):
        file_type = 'pdb'
    elif template.endswith('.cif'):
        file_type = 'cif'
    else:
        logging.error(f'Unknown file type for {template}!')
        sys.exit(1)
    for record in SeqIO.parse(template, f"{file_type}-seqres"):
        if record.id == chain_id:
            seqs.append((chain_id, str(record.seq)))

    # Parsing from atoms if SEQRES records are not found
    if len(seqs) == 0:
        logging.warning(f'No SEQRES records found in {template}! Parsing from atoms!')
        model = to_bio(template, chain_id)[0]
        for chain in model:
            seq_chain = ''
            for resi in chain:
                try:
                    one_letter = three_to_one(resi.resname)
                    seq_chain += one_letter
                except KeyError:
                    logging.warning(f'Skipping {resi.resname} with id {resi.id}')
            seqs.append((chain_id, seq_chain))
    return seqs`

**Comment by DimaMolod** [comment]
and move the checks (only 1 model, chain id is present within the biopython structure) to to_bio()

**Comment by DimaMolod** [comment]
done. Also restructured, all functions moved to methods of BioStructure class (need a better name)
