### ISSUE TITLE
Save full cif file in a temporary pathname

### ISSUE THREAD

**Issue by jkosinski** [KosinskiLab/AlphaPulldown#181]
https://github.com/KosinskiLab/AlphaPulldown/blob/2438c92ce99a6e231055f738721ce7dc323b8786/alphapulldown/create_fake_template_db.py#L108C38-L108C38

So it does not overwrite user files and also is not susceptible to convert_pdb_to_mmcif reading existing cif files instead of generating new ones. Alternatively save it in fake_template_db directory.

Ofc. delete the temporary pathname with try: finally: statements or sth like that.

**Comment by DimaMolod** [comment]
https://github.com/KosinskiLab/AlphaPulldown/commit/7c90d573c52edad2822a5b35266331acfeb77253
Closing...
