### ISSUE TITLE
Output notebook: models ranking and coloring

### ISSUE THREAD

**Issue by gilep** [KosinskiLab/AlphaPulldown#185]
Models coloring is different from the standards (left: notebook coloring, central: chimeraX coloring, right: AlphaFoldDB coloring):
<img width="80" alt="image" src="https://github.com/KosinskiLab/AlphaPulldown/assets/82955438/d7037a17-60c4-40a1-90fe-db30ed8e88c4"><img width="60" alt="image" src="https://github.com/KosinskiLab/AlphaPulldown/assets/82955438/038bbf1d-850c-4866-926e-4e1c097a3977"><img width="76" alt="image" src="https://github.com/KosinskiLab/AlphaPulldown/assets/82955438/678ec111-d6df-45bc-bfe2-afbc3979b5f3">
Functions parse_results() and parse_results_colour_chains() parse 5 models in alphabetic order rather than numeric (display_pae_plots() also should be checked):
<img width="740" alt="image" src="https://github.com/KosinskiLab/AlphaPulldown/assets/82955438/0edb54a9-98e9-4fcb-a922-7234e522e6c0">

**Comment by dingquanyu** [comment]
parse_results are from Grzegs package. Do we have to change anything here?

**Comment by jkosinski** [comment]
ok, I re-assigned to him. BTW. which af2plots the submodule links to?
https://git.embl.de/gchojnowski/af2plots
or
https://gitlab.com/gchojnowski/af2plots
?

**Comment by gchojnowski** [comment]
it's on gitlab, wiill have a look at this

**Comment by jkosinski** [comment]
Sorry, wanted to ask:
@dingquanyu the af2plots submodule points to git.embl.de or gitlab.com? It should to gitlab.com

**Comment by jkosinski** [comment]
> https://github.com/KosinskiLab/AlphaPulldown/blob/main/.gitmodules#L11

ok, we're using the latest version then.

**Comment by jkosinski** [comment]
> parse_results are from Grzegs package. Do we have to change anything here?

is the sorting in @gchojnowski part or the AP part?

**Comment by gchojnowski** [comment]
on AP side

**Comment by dingquanyu** [comment]
> on AP side
> 
> https://github.com/KosinskiLab/AlphaPulldown/blob/2443672127ef31e32fcf2353c6f4784a37a1d9f3/alphapulldown/analysis_pipeline/af2_3dmol.py#L52

Grzeg's right. The sorting error is on AP part and I'll fix this sorting problem. I guess @gchojnowski will work on the colouring part in?

**Comment by jkosinski** [comment]
I reopen as @gchojnowski still needs to fix the coloring?

**Comment by dingquanyu** [comment]
> I reopen as @gchojnowski still needs to fix the coloring?

Oh yea you're right. @gchojnowski could you pull the changes before working on the colouring fix?

**Comment by gchojnowski** [comment]
sure!

**Comment by gchojnowski** [comment]
can you test?
