### ISSUE TITLE
Questions about the mpDockQ/pDockQ column in csv table

### ISSUE THREAD

**Issue by teaninja** [KosinskiLab/AlphaPulldown#189]
Dear colleagues,

I wonder could you please explain more about the mpDockQ/pDockQ column in csv table?
Does value in "mpDockQ/pDockQ" column means "mpDock" value divided by "pDockQ" value?
Also, does mpDockQ use the same cutoffs of pDockQ (0.23, 0.49 and 0.80)?

Thank you!

Best regards,

Bing

**Comment by dingquanyu** [comment]
Hi Bing,

Sorry the column name is a bit misleading. It means the scores in this column is either a pDockQ score, should it be a dimeric model, or an mPDockQ score, should it have more than 2 subunits. As for the cutoffs, I recommend you referring to the pDockQ paper and mPDockQ paper. They are in AlphaPuldown paper's references. 

Hope this helps.

Yours
Dingquan

**Comment by teaninja** [comment]
Hi @dingquanyu 

Thank you for your response!
I didn't find any mention of cutoff issues in their paper. I'll reach out to the authors for additional guidance.
Additionally, I would like to confirm if the final CSV table was generated solely based on the "ranked_0" model.

Thanks once again for your assistance!

Best regards,

Bing

**Comment by dingquanyu** [comment]
Hi Bing,

Yep you're right. The CSV table was created solely based on ranked_0 model. 

Yours sincerely,
Dingquan Yu

**Comment by dingquanyu** [comment]
Close the issue as it's been answered
