### ISSUE TITLE
create_individual_features.py specify number of cpu

### ISSUE THREAD

**Issue by jflucier** [KosinskiLab/AlphaPulldown#194]
Hi,

I was wandering if there is an option we can provide to create_individual_features.py that specifies how much thread can be used by process.

I see in run that jackhmmer is called and this software as an option --cpu that specifies the number of threads.

Thanks for your help
JF

**Comment by dingquanyu** [comment]
Hi @jflucier 

Thanks for your interest in our package but the number of cpus used in the alignment programmes was hard-coded by Deepmind as in: https://github.com/google-deepmind/alphafold/blob/f715f016d875e2fd8515457af2b12277a716b9b0/alphafold/data/tools/jackhmmer.py#L38 We decided not to expose this parameter to the users of AlphaPulldown after discussion but you could in principle fork AlphaFold from Deepmind and modify it yourself. Just make sure export PYTHONPATH after your modifications on AlphaFold's fork are finished. 

Hope this helps.

Yours
Dingquan Yu
