### ISSUE TITLE
Pickle file size 

### ISSUE THREAD

**Issue by matthieu-haudiquet** [KosinskiLab/AlphaPulldown#195]
Hello, 

Thank you for this excellent tool ! A few questions: 

- How to I limit the number of models to e.g. 3, instead of the default 5 ?

- I have very large (>1.5gb) pickle files for each models after running `run_multimer_jobs.py` and from what I understand only the best model pickle file is used to output the final csv table. Is there an option to only keep the best one ? The issue is that, if I have to re-run after removing the pickle files (for example after adding new sequences), it doesnt detect that this model is done and re-computes it. 

Cheers, 
Matthieu

**Comment by joshtburdick** [comment]
Related idea: would it be worthwhile to compress the .pkl files? E.g. for 10 proteins, gzip took 4:36 to compress them, fairly well:
```
...$ srun1 time gzip --best --keep --force --verbose *.pkl
[...srun stuff omitted...]
P06576_ATPB.pkl:         93.2% -- created P06576_ATPB.pkl.gz
P17844_DDX5.pkl:         95.4% -- created P17844_DDX5.pkl.gz
P25705_ATPA.pkl:         93.3% -- created P25705_ATPA.pkl.gz
```
If computing MSAs takes hours, this seems possibly useful.
Clearly, this could be done outside of the actual code. But it seems like integrating it into AlphaPulldown might be convenient. I don't know how hard that would be, though.

Thanks for a great tool!
Josh

**Comment by dingquanyu** [comment]
Hi @joshtburdick and @matthieu-haudiquet 

Thank you very much for the suggestions! It indeed will be a wonderful feature to have. I will add a zipping step at the end of the process in the new release.

Yours
Dingquan
