### ISSUE TITLE
Compute multiple sequence alignment (MSA) using multiple pbd templates

### ISSUE THREAD

**Issue by jflucier** [KosinskiLab/AlphaPulldown#196]
Hi,

curious to see if it is possible to use multiple pdb templates for modeling. For example, if I look at pdb for pcna, I find multiple pdbs available for human: 

https://files.rcsb.org/download/3JA9.cif.gz
https://files.rcsb.org/download/1VYM.cif.gz
https://files.rcsb.org/download/1W60.cif.gz
https://files.rcsb.org/download/6FCM.cif.gz
https://files.rcsb.org/download/3VKX.cif.gz
https://files.rcsb.org/download/1AXC.cif.gz

Of course I can pick one of them as my template, but is it possible to specify all of them in the file `description.csv`?
```
/nfs3_ib/nfs-ip34/home/def-marechal/analysis/20230922_fold/alphapulldown_runs/fastas/pcna.fasta, 3L4Q.cif....., pcna
```
Thanks for your help

JF

**Comment by DimaMolod** [comment]
Hi,
thanks for you interest in AlphaPulldown.
Even though this feature is not widely tested yet, it is already available. Just add all the templates you want to the description.csv using the same *.fasta file. AP will group the templates and add them all to the fake database -> to the features, so they can be used for modeling. 
Please let me know about your progress.
Best regards,
Dima
