### ISSUE TITLE
get_good_inter_pae.py fails at pDockQ

### ISSUE THREAD

**Issue by grandrea** [KosinskiLab/AlphaPulldown#198]
I ran alphapuldown in pulldown mode, successfully. The ipython notebook displays the pae plots and structures. I am now trying to run get_good_inter_pae.py to get the csv table of pDockQ and iptm. Currently, I cannot run the singularity container (our AF is 2.3.1 and this uses jax to generate the pkl files, which is incompatible with the container, so i am running the script directly.

I run the following giving the path of the directory with all model subdirectories

    python ../AlphaPulldown/alphapulldown/analysis_pipeline/get_good_inter_pae.py --output_dir=/scratch/alphapulldown/output_data/models --cutoff=5 --surface_thres=2
    
I get the following output

```
I1107 18:20:02.406669 23456247920448 get_good_inter_pae.py:110] now processing BAIT_and_PREY1
I1107 18:20:03.382363 23456247920448 xla_bridge.py:170] Remote TPU is not linked into jax; skipping remote TPU.
I1107 18:20:03.382472 23456247920448 xla_bridge.py:353] Unable to initialize backend 'tpu_driver': Could not initialize backend 'tpu_driver'
I1107 18:20:03.382547 23456247920448 xla_bridge.py:353] Unable to initialize backend 'cuda': module 'jaxlib.xla_extension' has no attribute 'GpuAllocatorConfig'
I1107 18:20:03.382595 23456247920448 xla_bridge.py:353] Unable to initialize backend 'rocm': module 'jaxlib.xla_extension' has no attribute 'GpuAllocatorConfig'
I1107 18:20:03.383205 23456247920448 xla_bridge.py:353] Unable to initialize backend 'tpu': module 'jaxlib.xla_extension' has no attribute 'get_tpu_client'
I1107 18:20:03.383305 23456247920448 xla_bridge.py:353] Unable to initialize backend 'plugin': xla_extension has no attributes named get_plugin_device_client. Compile TensorFlow with //tensorflow/compiler/xla/python:enable_plugin_device set to true (defaults to false) to enable this.
W1107 18:20:03.383360 23456247920448 xla_bridge.py:360] No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
Traceback (most recent call last):
  File "../AlphaPulldown/alphapulldown/analysis_pipeline/get_good_inter_pae.py", line 149, in <module>
    app.run(main)
  File "/home/miniconda3/envs/openfold_venv/lib/python3.7/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/home/miniconda3/envs/openfold_venv/lib/python3.7/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "../AlphaPulldown/alphapulldown/analysis_pipeline/get_good_inter_pae.py", line 125, in main
    mpDockq_score = obtain_mpdockq(os.path.join(FLAGS.output_dir,job))
  File "../AlphaPulldown/alphapulldown/analysis_pipeline/get_good_inter_pae.py", line 43, in obtain_mpdockq
    mpDockq_or_pdockq = calc_pdockq(chain_coords,plddt_per_chain,t=8)
  File "/scratch/alphapulldown/AlphaPulldown/alphapulldown/analysis_pipeline/calculate_mpdockq.py", line 164, in calc_pdockq
    avg_if_plddt = np.average(np.concatenate([plddt1[np.unique(contacts[:,0])], plddt2[np.unique(contacts[:,1])]]))
IndexError: index 1870 is out of bounds for axis 0 with size 440

```

as if the lookup of the length of the 2 proteins is wrong... any clues?

**Comment by dingquanyu** [comment]
Hi,

Sorry this error occurred. Could you let me know when you downloaded the singularity image? It happened before and got fixed in the new version of the singularity image released on July 31st. If you downloaded it before that date, could you download the newer version using the same link? 

Yours
Dingquan

**Comment by grandrea** [comment]
thanks or the prompt reply. I am not running the singularity image at all, i am directly calling the get_good_inter_pae.py with python from command line

**Comment by dingquanyu** [comment]
Hi,

I'm really sorry that I forgot to push the updates to the github repo. Could you checkout this commit on the main:  00f2a5b I hope the fixes should solve the issue for you.

**Comment by grandrea** [comment]
thanks - that error is gone but i think the files have some hardcoded paths

https://github.com/KosinskiLab/AlphaPulldown/blob/00f2a5b8ff6c274b1ed6f711957578b73275bdb9/alphapulldown/analysis_pipeline/get_good_inter_pae.py#L67

Does this only work from the singularity image? where is the script run_piscore_wc.py?

**Comment by grandrea** [comment]
I see it is from https://gitlab.com/sm2185/ppi_scoring and it's written in python2... i'll see if i can get the singularity image to run

**Comment by dingquanyu** [comment]
Yea sorry that's true. Somehow the analysis script they wrote was in python2 and used a lot of ccp4 suite software and that's why I containerised it. 

Since the previous error is gone, I will close this issue but please feel free to create another one if there's something wrong with the singularity.
