### ISSUE TITLE
Unable to create Jupyter notebook due too compression of pickle files

### ISSUE THREAD

**Issue by B0r1sD** [KosinskiLab/AlphaPulldown#211]
I'm testing AlphaPulldown on an HPC cluster, and after updating to 1.0.1 (and 1.0.2 right after), I was not able to create the Jupyter notebook as shown at Step 3 in [example_1](https://github.com/KosinskiLab/AlphaPulldown/blob/main/manuals/example_1.md). 

In this version, the 2 new options `--compress_result_pickles=True` and `--remove_result_pickles=True` have been introduced so I've been using them since. However the compression of the pickle results (specifically the result model output files  e.g. **result_model_1_multimer_v3_pred_0.pkl**) gave the following error:
```
I1208 10:02:56.028748 139723418175296 create_notebook.py:98] now processing P78344_and_P08240
Traceback (most recent call last):
  File "/home/VIB.LOCAL/boris.depoortere/.conda/envs/AlphaPulldown_1.0.1_2/bin/create_notebook.py", line 142, in <module>
    app.run(main)
  File "/home/VIB.LOCAL/boris.depoortere/.conda/envs/AlphaPulldown_1.0.1_2/lib/python3.10/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/home/VIB.LOCAL/boris.depoortere/.conda/envs/AlphaPulldown_1.0.1_2/lib/python3.10/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/home/VIB.LOCAL/boris.depoortere/.conda/envs/AlphaPulldown_1.0.1_2/bin/create_notebook.py", line 106, in main
    seqs = pickle.load(open(result_path, "rb"))["seqs"]
_pickle.UnpicklingError: invalid load key, '\x1f'.
```

Gunzipping the pickle files solved the problem, but I believe you might want to add this little step to the tutorial or probably even beter incorporate a permanent fix in the **create_notebook.py** script. 

Also, the remove_result_pickles option made my slurm logs end with the following error:
```
rm: cannot remove 'result_model_1_multimer_v3_pred_0.pkl': No such file or directory
```
because after compressing them, they have the additional .gz extension and therefor unable to find the pickle file I assume.

Hope this is of use and I thank you for the tool!

**Comment by dingquanyu** [comment]
Hi @B0r1sD 

Many thanks for spotting it. Indeed the script for creating the notebook should be updated. We're now working on it. 

Yours
Dingquan

**Comment by jkosinski** [comment]
Hi Geoffrey,
Just could you make sure that it works on BOTH compressed and uncompressed files? 
Thanks.
Jan
