### ISSUE TITLE
Move analysis installation instruction to the main readme?

### ISSUE THREAD

**Issue by jkosinski** [KosinskiLab/AlphaPulldown#220]
https://github.com/KosinskiLab/AlphaPulldown/blob/13c42db1aee57d8689b3dfdc3317a656439f621a/manuals/example_1.md?plain=1#L291

This way we would not need to repeat on every page and update in multiple places whenever we change urls. Also we could write there the command to download from command line, which requires --no-check-certificate:

```
wget --no-check-certificate https://www.embl-hamburg.de/AlphaPulldown/downloads/alpha-analysis_jax_0.4.sif
```

**Comment by DimaMolod** [comment]
Fix in d78dea338a35c71c0e645027173b276fb7b48fef
