### ISSUE TITLE
Add how to install analysis_pipeline in developer mode

### ISSUE THREAD

**Issue by jkosinski** [KosinskiLab/AlphaPulldown#226]
https://github.com/KosinskiLab/AlphaPulldown/blob/60b52180ece9b2b74dc1199a7d1b5418f7cbf323/manuals/Developing.md?plain=1#L9

If I follow these steps, the notebook would crash with:

```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[2], line 1
----> 1 from analysis_pipeline.af2_3dmol import parse_results,parse_results_colour_chains

ModuleNotFoundError: No module named 'analysis_pipeline'
```

**Comment by DimaMolod** [comment]
since analysis_pipeline doesn't appear to be a python package, the easiest solution is to change
`from analysis_pipeline.af2_3dmol import parse_results,parse_results_colour_chains`
to
`from alphapulldown.analysis_pipeline.af2_3dmol import parse_results,parse_results_colour_chains`
in the notebooks

**Comment by DimaMolod** [comment]
The new instructions work. For the reference, I refer here to the CI/CD:
https://github.com/KosinskiLab/AlphaPulldown/blob/main/.github/workflows/github_actions.yml#L42C1-L48C45
