### ISSUE TITLE
alpha_analysis_jax_0.4.sif python issue

### ISSUE THREAD

**Issue by BobCoelingh** [KosinskiLab/AlphaPulldown#243]
I'm having some trouble with executing the singularity alpha_analysis_jax_0.4.sif and after consulting with the people from our HPC ,they adviced me to contact you. The python command in run_get_good_pae.sh fails for me and it seems to be python3. I was wondering if this is a problem specific to our set-up or something wrong with the container. I would greatly appreciate any advice on how to solve this!

**Comment by dingquanyu** [comment]
Hi @BobCoelingh 
Sorry it didn't work for you. Could you also attach the full error report? It will be easier for us to investigate the issue. Thanks 

Yours
Dingquan

**Comment by BobCoelingh** [comment]
Hi @dingquanyu,
This happens when I run the code:
(AlphaPulldown) [bcoelingh@int5 models]$ singularity exec --no-home --bind /projects/0/einf398/alphapulldown/output/models:/mnt /projects/0/einf398/alphapulldown/output/models/alpha-analysis_jax_0.4.sif run_get_good_pae.sh --output_dir=/projects/0/einf398/alphapulldown/output/models/mnt --cutoff=10
/app/run_get_good_pae.sh: line 7: python: command not found
(AlphaPulldown) [bcoelingh@int5 models]$ 

This is the advice from the HPC people:
The "python" command is not available  in the container:

singularity exec alpha-analysis_jax_0.4.sif python --version
FATAL:   "python": executable file not found in $PATH 
The correct command is 

singularity exec alpha-analysis_jax_0.4.sif python3 --version
Python 3.9.2 

Thank you for your fast response!

**Comment by dingquanyu** [comment]
Hi,

I see. The correct command should be 
```bash
singularity exec --no-home --bind /projects/0/einf398/alphapulldown/output/models:/mnt /projects/0/einf398/alphapulldown/output/models/alpha-analysis_jax_0.4.sif run_get_good_pae.sh --output_dir=/mnt --cutoff=10
```
instead but this shouldn't cause the python not found error. I'll look into the issue.

Cheers

**Comment by BobCoelingh** [comment]
Thank you very much for the help!

**Comment by Resram** [comment]
Hello AlphaPulldown team,

Thank you for your support so far. My latest issue is with Jupyter Notebook. I am working on the server, and I can load the notebook successfully. **However, the only issue is that the inter
![Screenshot from 2024-01-21 10-35-20](https://github.com/KosinskiLab/AlphaPulldown/assets/88697232/eb73316e-7135-447e-8204-c15bff28953a)
active plots are not loading at all.** Tthe static plots are showing up correctly. Additionally, when I run "%autosave 0," I get the following error: "Javascript Error: IPython is not defined. Autosave disabled." I have attached a screenshot of my notebook. Thank you in advance.
![Screenshot from 2024-01-21 10-35-20](https://github.com/KosinskiLab/AlphaPulldown/assets/88697232/770eb9c6-8964-441f-81e2-23cf5a26cab9)

**Comment by dingquanyu** [comment]
Hi @Resram 

Regarding the issue with the interactive plots,  it may be because the browser you used does not support the javascript plugins that are required. I myself am not an expert in this but this error can happen because of this.

As for the default cutoff of 5, it was only an example to demonstrate how the command line should look like. As far as I'm concerned, there has been no paper on the relation between the cutoff and sensitivity/specificity but feel free to correct me on this point. 

Hope it helps.

Yours
Dingquan

**Comment by BobCoelingh** [comment]
Hi @dingquanyu,

In the end I managed to change the line in run_get_good_pae.sh and rebuild the singularity. This made it work, thank you for the support!

**Comment by dingquanyu** [comment]
Hi @BobCoelingh 

I see sorry I couldn't help you in this case and thanks for reporting it : D I will close it for now.
