### ISSUE TITLE
maxres and maxfilt flags not working

### ISSUE THREAD

**Issue by BelminLeiden** [KosinskiLab/AlphaPulldown#245]
Dear developers,

I was trying to run the individual features script for two proteins. One of them consistently fails to produce a .pkl file.

The process keeps being interrupted after starting the following line:

- 12:42:00.914 INFO: Realigning 100000 HMM-HMM alignments using Maximum Accuracy algorithm
slurmstepd: error: Detected 72 oom-kill event(s) in StepId=2295791.batch cgroup. Some of your processes may have been killed by the cgroup out-of-memory handler

I am not sure if this is related to it, but the error output file contained the following warnings:

E0117 13:04:49.452801 46912500000576 hhblits.py:141] - 09:37:07.119 WARNING: database contains sequences that exceed maximum allowed size (maxres = 20001). Max sequence length can be increased with parameter -maxres.
E0117 13:04:49.452401 46912500000576 hhblits.py:141] - 09:35:31.884 WARNING: Number of hits passing 2nd prefilter (reduced from 243203 to allowed maximum of 100000).
E0117 13:04:49.452483 46912500000576 hhblits.py:141] You can increase the allowed maximum using the -maxfilt <max> option.

- 13:47:27.037 WARNING: maximum number of residues 32763 exceeded in sequence UniRef100_A0A5A9P0L4 Peptidylprolyl isomerase n=1 Tax=Triplophysa tibetana TaxID=1572043 RepID=A0A5A9P0L4_9TELE
- 13:47:27.039 WARNING: Number of match columns too large. Only first 19999 match columns will be kept!

Adding maxfilt or maxres as flags to the individual features script did not seem to be recognised.

Am I doing something wrong?

The script runs well for other proteins. This is the first time I encounter an issue.

Best wishes and many thanks,
Belmin 
Leiden University

**Comment by dingquanyu** [comment]
Hi Belmin,

Sorry this error occurred. It seems that this ```slurmstepd: error: Detected 72 oom-kill event(s) in StepId=2295791.batch cgroup. Some of your processes may have been killed by the cgroup out-of-memory handler``` indicated you might not have reserved enough memory for  this job on your cluster. Could you maybe try it again after allocating more mem for this job?

Yours
Dingquan

**Comment by dingquanyu** [comment]
Hi,

Just checking if it's solved?

Yours
Dingquan

**Comment by dingquanyu** [comment]
Closed due to inactivity
