### ISSUE TITLE
May I know how to execute run_multimer_jobs.py with CPU

### ISSUE THREAD

**Issue by herman-einstein** [KosinskiLab/AlphaPulldown#251]
I learned that your script offers an option of running prediction without GPU. However, it did not work when I ran it without GPU.
While I tried running it with GPU, a similar error also occurred. I will very much appreciate if you could help me address this problem.

Command:

run_multimer_jobs.py --mode=pulldown --num_cycle=3 --num_predictions_per_model=1 --output_path=/home/Analysis/alphafold_analysis/output/alphapulldown/pull --data_dir=/home/Analysis/alphafold_analysis/alphafold_database --protein_lists=/home/Analysis/alphafold_analysis/output/alphapulldown/baits.txt,/home/Analysis/alphafold_analysis/output/alphapulldown/candidates.txt --monomer_objects_dir=/home/Analysis/alphafold_analysis/output/alphapulldown/output --job_index=1 --compress_result_pickles=True --remove_result_pickles=True

Error:

/home/anaconda3/envs/AlphaPulldown/lib/python3.10/site-packages/Bio/Data/SCOPData.py:18: BiopythonDeprecationWarning: The 'Bio.Data.SCOPData' module will be deprecated in a future release of Biopython in favor of 'Bio.Data.PDBData.
  warnings.warn(
2024-02-01 11:07:38.120817: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-02-01 11:07:38.120873: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-02-01 11:07:38.122323: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-02-01 11:07:39.447468: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
I0201 11:07:41.248603 139702582228800 utils.py:271] checking if output_dir exists /home/Analysis/alphafold_analysis/output/alphapulldown/pull
I0201 11:07:41.250349 139702582228800 run_multimer_jobs.py:229] All pickle files have been found
Traceback (most recent call last):
  File "/home/anaconda3/envs/AlphaPulldown/bin/run_multimer_jobs.py", line 462, in <module>
    app.run(main)
  File "/home/anaconda3/envs/AlphaPulldown/lib/python3.10/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/home/anaconda3/envs/AlphaPulldown/lib/python3.10/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/home/anaconda3/envs/AlphaPulldown/bin/run_multimer_jobs.py", line 433, in main
    multimers = create_multimer_objects(data, FLAGS.monomer_objects_dir, not FLAGS.no_pair_msa)
  File "/home/anaconda3/envs/AlphaPulldown/bin/run_multimer_jobs.py", line 235, in create_multimer_objects
    multimer = MultimericObject(interactors=interactors,pair_msa=pair_msa, multimeric_mode = FLAGS.multimeric_mode)
  File "/home/anaconda3/envs/AlphaPulldown/lib/python3.10/site-packages/alphapulldown/objects.py", line 452, in __init__
    self.create_all_chain_features()
  File "/home/anaconda3/envs/AlphaPulldown/lib/python3.10/site-packages/alphapulldown/objects.py", line 583, in create_all_chain_features
    self.feature_dict = self.pair_and_merge(
  File "/home/anaconda3/envs/AlphaPulldown/lib/python3.10/site-packages/alphapulldown/objects.py", line 553, in pair_and_merge
    np_example = feature_processing.process_final(np_example)
  File "/home/anaconda3/envs/AlphaPulldown/lib/python3.10/site-packages/alphafold/data/feature_processing.py", line 167, in process_final
    np_example = _make_msa_mask(np_example)
  File "/home/anaconda3/envs/AlphaPulldown/lib/python3.10/site-packages/alphafold/data/feature_processing.py", line 191, in _make_msa_mask
    np_example['msa_mask'] *= seq_mask[None]
ValueError: operands could not be broadcast together with shapes (4095,1276) (1,1545) (4095,1276)

**Comment by dingquanyu** [comment]
Hi @herman-einstein 

Really sorry this error occurred. It seems that ```msa_mask``` feature of one of your proteins is correct and this error has nothing to do with GPU or CPU. Could you let us know how you created the pickles in the ``create_individual_features.py```? I wonder if it's also related to ``mmseqs2``` mode. Thank you.

Yours
Dingquan

**Comment by herman-einstein** [comment]
I successfully created the pickles by running the following command

export HHLIB=/home/anaconda3/envs/AlphaPulldown
export HMMER=/home/Analysis/alphafold_analysis/hmmer-3.4
create_individual_features.py --fasta_paths=/home/Analysis/alphafold_analysis/output/alphapulldown/baits.fasta --data_dir=/home/Analysis/alphafold_analysis/alphafold_database --output_dir=/home/Analysis/alphafold_analysis/output/alphapulldown/output --skip_existing=False --use_mmseqs2=True --max_template_date=$(date +"%Y-%m-%d") --seq_index=1 

However, it stopped at line 191 like the following. I do not know whether it is completed or not.
![image](https://github.com/KosinskiLab/AlphaPulldown/assets/144147113/ba39d0d4-0f19-4bf0-9af2-ae245d8223b2)

**Comment by herman-einstein** [comment]
In addition, I came across this error while running alpha-analysis.sif to calculate the pi score. Is it because the panda version?
![image](https://github.com/KosinskiLab/AlphaPulldown/assets/144147113/ea7825d5-6390-41c0-9759-ec7427eb252a)

**Comment by dingquanyu** [comment]
> In addition, I came across this error while running alpha-analysis.sif to calculate the pi score. Is it because I only have one pull-down group? And it assumes more than one pull-down group for pi score calculation?
> 
> ![image](https://private-user-images.githubusercontent.com/144147113/302501700-ea7825d5-6390-41c0-9759-ec7427eb252a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyMjE0ODAsIm5iZiI6MTcwNzIyMTE4MCwicGF0aCI6Ii8xNDQxNDcxMTMvMzAyNTAxNzAwLWVhNzgyNWQ1LTYzOTAtNDFjMC05NzU5LWVjNzQyN2ViMjUyYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwNlQxMjA2MjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMGI4ZGYzOGUzMWU4YTEzZDg1ZGQwZTZmODAxMGU0Njg1ZTM4Y2JjYTllN2I4MDFkMzdmZjNlZWNlYWI2OWJlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8zcPFbx-IjTela_bfiZJGDP6YwrQmY2xKft9HaaQmB0)

Hi @herman-einstein ,

According to your screenshot, it should be caused by mounting a wrong directory. You should in this case mount one level above.

Yours
Dingquan

**Comment by herman-einstein** [comment]
> > In addition, I came across this error while running alpha-analysis.sif to calculate the pi score. Is it because I only have one pull-down group? And it assumes more than one pull-down group for pi score calculation?
> > ![image](https://private-user-images.githubusercontent.com/144147113/302501700-ea7825d5-6390-41c0-9759-ec7427eb252a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyMjE0ODAsIm5iZiI6MTcwNzIyMTE4MCwicGF0aCI6Ii8xNDQxNDcxMTMvMzAyNTAxNzAwLWVhNzgyNWQ1LTYzOTAtNDFjMC05NzU5LWVjNzQyN2ViMjUyYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwNlQxMjA2MjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMGI4ZGYzOGUzMWU4YTEzZDg1ZGQwZTZmODAxMGU0Njg1ZTM4Y2JjYTllN2I4MDFkMzdmZjNlZWNlYWI2OWJlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8zcPFbx-IjTela_bfiZJGDP6YwrQmY2xKft9HaaQmB0)
> 
> Hi @herman-einstein ,
> 
> According to your screenshot, it should be caused by mounting a wrong directory. You should in this case mount one level above.
> 
> Yours Dingquan

Hi @dingquanyu 

Thank you for your quick reply.

I tried mounting the directory that is one level above. However, there is the same issue

![image](https://github.com/KosinskiLab/AlphaPulldown/assets/144147113/3d6a0160-d6aa-47dc-a1ed-dc32e2467eb8)

This is the command I executed:

"singularity exec --no-home --bind /home/Desktop/pulldown/pull2:/mnt /media/data/alpha-analysis_jax_0.4.sif run_get_good_pae.sh --output_dir=/mnt --cutoff=10"

**Comment by herman-einstein** [comment]
> > In addition, I came across this error while running alpha-analysis.sif to calculate the pi score. Is it because I only have one pull-down group? And it assumes more than one pull-down group for pi score calculation?
> > ![image](https://private-user-images.githubusercontent.com/144147113/302501700-ea7825d5-6390-41c0-9759-ec7427eb252a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyMjE0ODAsIm5iZiI6MTcwNzIyMTE4MCwicGF0aCI6Ii8xNDQxNDcxMTMvMzAyNTAxNzAwLWVhNzgyNWQ1LTYzOTAtNDFjMC05NzU5LWVjNzQyN2ViMjUyYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwNlQxMjA2MjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMGI4ZGYzOGUzMWU4YTEzZDg1ZGQwZTZmODAxMGU0Njg1ZTM4Y2JjYTllN2I4MDFkMzdmZjNlZWNlYWI2OWJlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8zcPFbx-IjTela_bfiZJGDP6YwrQmY2xKft9HaaQmB0)
> 
> Hi @herman-einstein ,
> 
> According to your screenshot, it should be caused by mounting a wrong directory. You should in this case mount one level above.
> 
> Yours Dingquan


Hi, @dingquanyu 

Thank you for your quick reply,

I tried mounting the directory one level above. However, there is the same issue.

![image](https://github.com/KosinskiLab/AlphaPulldown/assets/144147113/8a93cccc-45b4-4415-ab28-5975308c896a)

This is the command I ran:

"singularity exec --no-home --bind /home/Desktop/pulldown/pull2:/mnt /media/data/alpha-analysis_jax_0.4.sif run_get_good_pae.sh --output_dir=/mnt --cutoff=10"

**Comment by dingquanyu** [comment]
> > > In addition, I came across this error while running alpha-analysis.sif to calculate the pi score. Is it because I only have one pull-down group? And it assumes more than one pull-down group for pi score calculation?
> > > ![image](https://private-user-images.githubusercontent.com/144147113/302501700-ea7825d5-6390-41c0-9759-ec7427eb252a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyMjE0ODAsIm5iZiI6MTcwNzIyMTE4MCwicGF0aCI6Ii8xNDQxNDcxMTMvMzAyNTAxNzAwLWVhNzgyNWQ1LTYzOTAtNDFjMC05NzU5LWVjNzQyN2ViMjUyYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwNlQxMjA2MjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMGI4ZGYzOGUzMWU4YTEzZDg1ZGQwZTZmODAxMGU0Njg1ZTM4Y2JjYTllN2I4MDFkMzdmZjNlZWNlYWI2OWJlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8zcPFbx-IjTela_bfiZJGDP6YwrQmY2xKft9HaaQmB0)
> > 
> > 
> > Hi @herman-einstein ,
> > According to your screenshot, it should be caused by mounting a wrong directory. You should in this case mount one level above.
> > Yours Dingquan
> 
> Hi, @dingquanyu
> 
> Thank you for your quick reply,
> 
> I tried mounting the directory one level above. However, there is the same issue.
> 
> ![image](https://private-user-images.githubusercontent.com/144147113/302876885-8a93cccc-45b4-4415-ab28-5975308c896a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczMDI2MjgsIm5iZiI6MTcwNzMwMjMyOCwicGF0aCI6Ii8xNDQxNDcxMTMvMzAyODc2ODg1LThhOTNjY2NjLTQ1YjQtNDQxNS1hYjI4LTU5NzUzMDhjODk2YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwN1QxMDM4NDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZjJhYzdhNWRjNGFmNTVmNTQ5NDlkMjRhNDBmM2JhNWY5NmE5NWRjNDk2OGM2ODBjMDRjYTJkMWE4ZmMxNTljJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.oPKklw9OUIIkKFrLrH91I9POPYCjEh4nVg51jZ1oQjE)
> 
> This is the command I ran:
> 
> "singularity exec --no-home --bind /home/Desktop/pulldown/pull2:/mnt /media/data/alpha-analysis_jax_0.4.sif run_get_good_pae.sh --output_dir=/mnt --cutoff=10"

Hi @herman-einstein ,

Sorry this still persisted. I suspected that this model quality wasn't good enough to pass the cutoff. Could you change the cutoff to 100 and run again?

Yours
Dingquan

**Comment by herman-einstein** [comment]
> > > > In addition, I came across this error while running alpha-analysis.sif to calculate the pi score. Is it because I only have one pull-down group? And it assumes more than one pull-down group for pi score calculation?
> > > > ![image](https://private-user-images.githubusercontent.com/144147113/302501700-ea7825d5-6390-41c0-9759-ec7427eb252a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyMjE0ODAsIm5iZiI6MTcwNzIyMTE4MCwicGF0aCI6Ii8xNDQxNDcxMTMvMzAyNTAxNzAwLWVhNzgyNWQ1LTYzOTAtNDFjMC05NzU5LWVjNzQyN2ViMjUyYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwNlQxMjA2MjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMGI4ZGYzOGUzMWU4YTEzZDg1ZGQwZTZmODAxMGU0Njg1ZTM4Y2JjYTllN2I4MDFkMzdmZjNlZWNlYWI2OWJlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8zcPFbx-IjTela_bfiZJGDP6YwrQmY2xKft9HaaQmB0)
> > > 
> > > 
> > > Hi @herman-einstein ,
> > > According to your screenshot, it should be caused by mounting a wrong directory. You should in this case mount one level above.
> > > Yours Dingquan
> > 
> > 
> > Hi, @dingquanyu
> > Thank you for your quick reply,
> > I tried mounting the directory one level above. However, there is the same issue.
> > ![image](https://private-user-images.githubusercontent.com/144147113/302876885-8a93cccc-45b4-4415-ab28-5975308c896a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczMDI2MjgsIm5iZiI6MTcwNzMwMjMyOCwicGF0aCI6Ii8xNDQxNDcxMTMvMzAyODc2ODg1LThhOTNjY2NjLTQ1YjQtNDQxNS1hYjI4LTU5NzUzMDhjODk2YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwN1QxMDM4NDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZjJhYzdhNWRjNGFmNTVmNTQ5NDlkMjRhNDBmM2JhNWY5NmE5NWRjNDk2OGM2ODBjMDRjYTJkMWE4ZmMxNTljJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.oPKklw9OUIIkKFrLrH91I9POPYCjEh4nVg51jZ1oQjE)
> > This is the command I ran:
> > "singularity exec --no-home --bind /home/Desktop/pulldown/pull2:/mnt /media/data/alpha-analysis_jax_0.4.sif run_get_good_pae.sh --output_dir=/mnt --cutoff=10"
> 
> Hi @herman-einstein ,
> 
> Sorry this still persisted. I suspected that this model quality wasn't good enough to pass the cutoff. Could you change the cutoff to 100 and run again?
> 
> Yours Dingquan

It works!!!! very much appreciate your help!

May I know what the cutoff means in this calculation?

**Comment by herman-einstein** [comment]
> > > > In addition, I came across this error while running alpha-analysis.sif to calculate the pi score. Is it because I only have one pull-down group? And it assumes more than one pull-down group for pi score calculation?
> > > > ![image](https://private-user-images.githubusercontent.com/144147113/302501700-ea7825d5-6390-41c0-9759-ec7427eb252a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyMjE0ODAsIm5iZiI6MTcwNzIyMTE4MCwicGF0aCI6Ii8xNDQxNDcxMTMvMzAyNTAxNzAwLWVhNzgyNWQ1LTYzOTAtNDFjMC05NzU5LWVjNzQyN2ViMjUyYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwNlQxMjA2MjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMGI4ZGYzOGUzMWU4YTEzZDg1ZGQwZTZmODAxMGU0Njg1ZTM4Y2JjYTllN2I4MDFkMzdmZjNlZWNlYWI2OWJlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8zcPFbx-IjTela_bfiZJGDP6YwrQmY2xKft9HaaQmB0)
> > > 
> > > 
> > > Hi @herman-einstein ,
> > > According to your screenshot, it should be caused by mounting a wrong directory. You should in this case mount one level above.
> > > Yours Dingquan
> > 
> > 
> > Hi, @dingquanyu
> > Thank you for your quick reply,
> > I tried mounting the directory one level above. However, there is the same issue.
> > ![image](https://private-user-images.githubusercontent.com/144147113/302876885-8a93cccc-45b4-4415-ab28-5975308c896a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczMDI2MjgsIm5iZiI6MTcwNzMwMjMyOCwicGF0aCI6Ii8xNDQxNDcxMTMvMzAyODc2ODg1LThhOTNjY2NjLTQ1YjQtNDQxNS1hYjI4LTU5NzUzMDhjODk2YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwN1QxMDM4NDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZjJhYzdhNWRjNGFmNTVmNTQ5NDlkMjRhNDBmM2JhNWY5NmE5NWRjNDk2OGM2ODBjMDRjYTJkMWE4ZmMxNTljJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.oPKklw9OUIIkKFrLrH91I9POPYCjEh4nVg51jZ1oQjE)
> > This is the command I ran:
> > "singularity exec --no-home --bind /home/Desktop/pulldown/pull2:/mnt /media/data/alpha-analysis_jax_0.4.sif run_get_good_pae.sh --output_dir=/mnt --cutoff=10"
> 
> Hi @herman-einstein ,
> 
> Sorry this still persisted. I suspected that this model quality wasn't good enough to pass the cutoff. Could you change the cutoff to 100 and run again?
> 
> Yours Dingquan

It works!!!! very much appreciate your help!

May I know what the cutoff means in this calculation?

**Comment by dingquanyu** [comment]
Hi @herman-einstein ,

Glad it worked for you! cutoff is to check if any residues has a PAE value below the specified cutoff in the PAE plot between 2 or more chains. For the details about what PAE means, please refer to AlphaFold Multimer paper. In short, the lower the value, the more strict the selection. 

Yours
Dingquan
