### ISSUE TITLE
Link to an existing AlphaFold2 installation

### ISSUE THREAD

**Issue by nmarounina** [KosinskiLab/AlphaPulldown#252]
I am working on the installation of AlphaPulldown on our university cluster, and I was wondering if it was possible to link it to an existing installation of AlphaFold 2.3.2, instead of re-downloading it as a sub-module ?
Would modifying paths in setup.cfg be enough ?

**Comment by dingquanyu** [comment]
Hi,
AlphaFold submodule is part of the tar files on pypi so pip will still install it when you run ``pip install```. However, you can still use your local version of AlphaFold by modifying ```PYTHONPATH```  when you run export PYTHONPATH=/path/you/want:$PYTHONPATH

Hope it helps.
Yours
Dingquan

**Comment by dingquanyu** [comment]
Hi,

Just checking if this issue has been solved?
