### ISSUE TITLE
CPU part silently failing for a particular protein

### ISSUE THREAD

**Issue by sroet** [KosinskiLab/AlphaPulldown#253]
Dear,

Thank you for this nice package. We used it successfully for many proteins in pulldown mode.
Unfortunately, we are running into an issue where we can't complete the CPU part for a couple problematic proteins

Problematic fasta:
```
>Q9HCK4
SRLRQEDFPPRIVEHPSDVIVSKGEPTTLNCKAEGRPTPTIEWYKDGERVETDKDDPRSHRMLLPSGSLFFLRIVHGRRSKPDEGSYVCVARNYLGEAVSRNASLEVALLRDDFRQNPTDVVVAAGEPAILECQPPRGHPEPTIYWKKDKVRIDDKEERISIRGGKLMISNTRKSDAGMYTCVGTNMVGERDSDPAELTVFERPTFLRRPINQVVLEEEAVEFRCQVQGDPQPTVRWKKDDADLPRGRYDIKDDYTLRIKKTMSTDEGTYMCIAENRVGKMEASATLTVRAPPQFVVRPRDQIVAQGRTVTFPCETKGNPQPAVFWQKEGSQNLLFPNQPQQPNSRCSVSPTGDLTITNIQRSDAGYYICQALTVAGSILAKAQLEVTDVLTDRPPPIILQGPANQTLAVDGTALLKCKATGDPLPVISWLKEGFTFPGRDPRATIQEQGTLQIKNLRISDTGTYTCVATSSSGETSWSAVLDVTESGATISKNYDLSDLPGPPSKPQVTDVTKNSVTLSWQPGTPGTLPASAYIIEAFSQSVSNSWQTVANHVKTTLYTVRGLRPNTIYLFMVRAINPQGLSDPSPMSDPVRTQDISPPAQGVDHRQVQKELGDVLVRLHNPVVLTPTTVQVTWTVDRQPQFIQGYRVMYRQTSGLQATSSWQNLDAKVPTERSAVLVNLKKGVTYEIKVRPYFNEFQGMDSESKTVRTTEEAPSAPPQSVTVLTVGSYNSTSISVSWDPPPPDHQNGIIQEYKIWCLGNETRFHINKTVDAAIRSVIIGGLFPGIQYRVEVAASTSAGVGVKSEPQPIIIGRRNEVVITENNNSITEQITDVVKQPAFIAGIGGACWVILMGFSIWLYWRRKKRKGLSNYAVTFQRGDGGLMSNGSRPGLLNAGDPSYPWLADSWPATSLPVNNSNSGPNEIGNFGRGDVLPPVPGQGDKTATMLSDGAIYSSIDFTTKTSYNSSSQITQATPYATTQILHSNSIHELAVDLPDPQWKSSIQQKTDLMGFGYSLPDQNKGNNGGKGGKKKKNKNSSKPQKNNGSTWANVPLPPPPVQPLPGTELEHYAVEQQENGYDSDSWCPPLPVQTYLHQGLEDELEEDDDRVPTPPVRGVASSPAISFGQQSTATLTPSPREEMQPMLQAHLDELTRAYQFDIAKQTWHIQSNNQPPQPPVPPLGYVSGALISDLETDVADDDADDEEEALEIPRPLRALDQTPGSSMDNLDSSVTGKAFTSSQRPRPTSPFSTDSNTSAALSQSQRPRPTKKHKGGRMDQQPALPHRREGMTDEEALVPYSKPSFPSPGGHSSSGTASSKGSTGPRKTEVLRAGHQRNASDLLDIGYMGSNSQGQFTGEL
```
Running this with the following command in a fresh install:
```
create_individual_features.py  --fasta_paths=problem.fasta  --data_dir=/databases/alphafold_data --save_msa_files=True  --output_dir=CPU_output  --use_precomputed_msas=False   --max_template_date=2023-04-30 --skip_existing=False
```
(old template date is there due to an old AF database on the HPC)

This results in a massive warning log, that gets cut off mid-sentence and I end up without the expected `pkl` file (most other files are there)

The log in my terminal as far as I could read back [terminal_log.txt](https://github.com/KosinskiLab/AlphaPulldown/files/14241239/terminal_log.txt)

Complete log from a more complete run on version 0.30.7 running in the same issue: [sub3k_cpu.log](https://github.com/KosinskiLab/AlphaPulldown/files/14241154/sub3k_cpu.log)

This is run on a machine with `64 GB` RAM and a `64 GB` swap file. Do you have any pointers on how to solve this issue?

**Comment by dingquanyu** [comment]
Hi @sroet 

Thanks for your interest in our package! Sorry this error stems from hhblits problem and we have experiences it as well. We cannot find a concrete solution and there has been many discussion under AlphaFold repo regarding hhblits issue. For example here: https://github.com/google-deepmind/alphafold/issues/164 They are also now waiting for HHsuite people to fix this kind of issues. I'm afraid there's nothing we could do here.

Yours
Dingquan

**Comment by sroet** [comment]
Hey @dingquanyu , 
thanks for your swift reply. 
Will see if I can reproduce in pure alphafold and will link any issues I open back to here to keep track of the issue.
