### ISSUE TITLE
Addition of flag (-save-pae-json) resulting in output of seperate pae.json files linked to predicted structures

### ISSUE THREAD

**Issue by jkosinski** [KosinskiLab/AlphaPulldown#257]
### Discussed in https://github.com/KosinskiLab/AlphaPulldown/discussions/248

<div type='discussions-op-text'>

<sup>Originally posted by **MHvegholm** January 30, 2024</sup>
The option to output separate pae.json files removes post-processing before custom visualization of pae plots when using tools like [paeviewer](http://www.subtiwiki.uni-goettingen.de/v4/paeViewerDemo).

This feature is already present in alphafold2 as `_save_pae_json_file()` which is [defined](https://github.com/google-deepmind/alphafold/blob/main/run_alphafold.py#L213) and [applied](https://github.com/google-deepmind/alphafold/blob/main/run_alphafold.py#L306-L312) in [`run_alphafold.py`](https://github.com/google-deepmind/alphafold/blob/main/run_alphafold.py) </div>

**Comment by DimaMolod** [comment]
the pae.json files are saved now by default as turned out that they are small (several MBs).

**Comment by jkosinski** [comment]
Great!
