### ISSUE TITLE
check_predict_structure.py not passing

### ISSUE THREAD

**Issue by jkosinski** [KosinskiLab/AlphaPulldown#264]
Because of these lines:
https://github.com/KosinskiLab/AlphaPulldown/blob/dc7701c089bedf29cfd8196ea43240f84547c3be/test/check_predict_structure.py#L78
they do not work anymore after the metadata update because now the folder contains also a json file which sometimes gets index [0] in the listdir output. Maybe replace with sth like?:

```
dirname = next(subdir for subdir in os.listdir(self.output_dir) if os.path.isdir(os.path.join(self.output_dir, subdir)))
```

**Comment by DimaMolod** [comment]
This has been fixed in commits 0676faa55507c2e2a2bec1d9f9d336b19a6fd73d and 3b2b4741286e20cf36f2162428cb143454067d3f
