### ISSUE TITLE
create_individual_features.py: command not found

### ISSUE THREAD

**Issue by sophiaaredas** [KosinskiLab/AlphaPulldown#267]

**Comment by sophiaaredas** [comment]
source activate AlphaPulldown
create_individual_features.py \
  --fasta_paths=pcdgG.fasta,sven_proteins.fasta \
  --data_dir=/local/workdir/sna49/Gallagher_Rotation/AlphaPullDown/proteins \
  --save_msa_files=False \
  --output_dir=/local/workdir/sna49/Gallagher_Rotation/AlphaPullDown/proteins/output \ 
  --use_precomputed_msas=False \
  --max_template_date=<2050-01-01> \
  --skip_existing=TRUE \
  --seq_index=$SLURM_ARRAY_TASK_ID

sorry I am really inexperienced with python so I am unsure if there is an error with my code but i am trying to compare my bait protein to a list of proteins and when I run this chunk I get an error message saying: create_individual_features.py: command not found. Any help is appreciated!

**Comment by DimaMolod** [comment]
Hi @sophiaaredas ! Seems like smth is wrong with your installation. All AP executable scripts incl. create_individual_features.py should be available in your path after `pip install alphapulldown==1.0.4`
Could you try deleting your conda environment and try installing it anew?
