### ISSUE TITLE
The 'Bio.Data.SCOPData' module will be deprecated in a future release of Biopython in favor of 'Bio.Data.PDBData

### ISSUE THREAD

**Issue by sophiaaredas** [KosinskiLab/AlphaPulldown#269]
hello! I am trying to run the code and I am working on an HPC server and the specific server that I am working on has Alphafold downloaded but I am unsure of how to call it into my code and may be getting errors as a result of the computer not understanding that there is Alphafold on the server I am currently working on if that makes sense?

anyways this is what I have so far:
(AlphaPulldown) [sna49@cbsugpu03 proteins]$ source activate AlphaPulldown
create_individual_features.py \
  --fasta_paths=gene.fasta,sven_proteins.fasta \
  --data_dir=/local/workdir/sna49/Gallagher_Rotation/AlphaPullDown/proteins \
  --save_msa_files=False \
  --output_dir=/local/workdir/sna49/Gallagher_Rotation/AlphaPullDown/proteins \ 
  --use_precomputed_msas=False \
  --max_template_date=2024-02-26 \
  --skip_existing=TRUE \
  --seq_index=None

This is the error message I get despite trying to force install biopython 1.81:
/programs/miniconda3/envs/AlphaPulldown/lib/python3.10/site-packages/Bio/Data/SCOPData.py:18: BiopythonDeprecationWarning: The 'Bio.Data.SCOPData' module will be deprecated in a future release of Biopython in favor of 'Bio.Data.PDBData.
  warnings.warn(
2024-02-26 14:14:11.041053: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-02-26 14:14:11.041107: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-02-26 14:14:11.042521: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-02-26 14:14:13.493357: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
FATAL Flags parsing error: flag --max_template_date=None: Flag --max_template_date must have a value other than None.
Pass --helpshort or --helpfull to see help on flags.
bash: --use_precomputed_msas=False: command not found...

**Comment by Qrouger** [comment]
Hi @sophiaaredas , it's not an error with Biopython.

BiopythonDeprecationWarning: The 'Bio.Data.SCOPData' module will be deprecated in a future release of Biopython in favor of 'Bio.Data.PDBData.
warnings.warn(

This line is just a warning  not an error.

2024-02-26 14:14:11.041053: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-02-26 14:14:11.041107: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-02-26 14:14:11.042521: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-02-26 14:14:13.493357: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT

These lines are same, is just a warning about librairy from cuda. For create _individual_features;py you can ignore them.

FATAL Flags parsing error: flag --max_template_date=None: Flag --max_template_date must have a value other than None.
Pass --helpshort or --helpfull to see help on flags.
bash: --use_precomputed_msas=False: command not found...

But these lines are an error about the command you entered.

I think you have write properly your command just with one space between Flags. Like that :
create_individual_features.py --fasta_paths=gene.fasta,sven_proteins.fasta -- data_dir=/local/workdir/sna49/Gallagher_Rotation/AlphaPullDown/proteins --save_msa_files=False --output_dir=/local/workdir/sna49/Gallagher_Rotation/AlphaPullDown/proteins --use_precomputed_msas=False --max_template_date=2024-02-26
--skip_existing=TRUE --seq_index=None

or with backslash : 
create_individual_features.py \
--fasta_paths=gene.fasta,sven_proteins.fasta \
--data_dir=/local/workdir/sna49/Gallagher_Rotation/AlphaPullDown/proteins \
--save_msa_files=False \
--output_dir=/local/workdir/sna49/Gallagher_Rotation/AlphaPullDown/proteins \
--use_precomputed_msas=False \
--max_template_date=2024-02-26 \
--skip_existing=TRUE \
--seq_index=None

I hope that help you.

Quentin Rouger.

**Comment by dingquanyu** [comment]
Thanks a lot for your comments and help @Qrouger ! This is indeed not caused by Bio.Data.PDBData but rather the format of the command line. @sophiaaredas Could you check your commands as suggested by Quentin?

**Comment by jkosinski** [comment]
@Qrouger you can also add "\" after each line - just do not put space character after the "\|
https://superuser.com/questions/508507/linux-bash-script-single-command-but-multiple-lines

**Comment by sophiaaredas** [comment]
hello thank you so much for everyone's help! unfortunately I have retried this for days and its still not working completely? Here is my code:
BASE_PATH=/workdir/sna49
create_individual_features.py \
  --fasta_paths=${BASE_PATH}.fasta \
  --data_dir=/local_data/alphafold-2.3.2 \ 
  --save_msa_files=False \
  --output_dir=${BASE_PATH}/alpha_out \
  --use_precomputed_msas=False \
  --max_template_date=2050-01-01 \
  --skip_existing=False \
  --seq_index=1 \

When I entered these lines and I added the "\" I made sure to not put a space character after the "\" but I am still getting similar errors and I have tried everything to fix it but still nothing successfully works here are the messages:

FATAL Flags parsing error:
  flag --output_dir=None: Flag --output_dir must have a value other than None.
  flag --max_template_date=None: Flag --max_template_date must have a value other than None.

I have written the output_dir and my fasta_paths to be really similar so I am unsure why exactly output_dir is throwing me an error of "none". Similarly with the max_template_date I have literally copied and pasted the exact date from the example and it still seems to not work and I have no clue what is going wrong. Thank you so much for your time I am so excited to get this running!

**Comment by Qrouger** [comment]
Hi, it seems that there is still a problem writing the command with a space that must be lying around.

Please can you try to write your command like this one, just with space before the double dash :

create_individual_features.py --fasta_paths=/workdir/sna49.fasta -- data_dir=/local_data/alphafold-2.3.2 --save_msa_files=False --output_dir=/workdir/sna49/alpha_out --use_precomputed_msas=False --max_template_date=2050-01-01--skip_existing=False --seq_index=1

I think It's easier to avoid increment errors like this.

Quentin Rouger

**Comment by DimaMolod** [comment]
Hi @sophiaaredas! Just checking if I can close this issue?

**Comment by sophiaaredas** [comment]
Hi @DimaMolod Yes you can close this issue ! I was able to make it work thank you so much for your help!
