### ISSUE TITLE
Consider removing extra information from model pkl immediately before saving them

### ISSUE THREAD

**Issue by jkosinski** [KosinskiLab/AlphaPulldown#276]
In principle, to save storage space, we could remove:
```aligned_confidence_probs,distogram,masked_msa```
items from the output pkls before saving them in run_multimer_jobs.py. 

Maybe even this should be the default, as most users do not look at them.

**Comment by DimaMolod** [comment]
We can easily add a command to run truncate_pickles.py in alphafold_backend.postprocessing() step, but isn't it better to keep the coping separate?

**Comment by jkosinski** [comment]
I think for situations where storage is an issue or in a cloud it’d be beneficial to avoid saving that at all and save users an extra manual step. Perhaps would also save time on IO.
