### ISSUE TITLE
KeyError when executing run_get_good_pae.sh

### ISSUE THREAD

**Issue by maurerv** [KosinskiLab/AlphaPulldown#279]
## Problem Description

When running run_get_good_pae.sh from within the analysis singularity container, the script may fail at get_good_inter_pae.py:146 when none of the jobs suffice the specified cutoff (see [log.txt](https://github.com/KosinskiLab/AlphaPulldown/files/14472703/log.txt)).

## Expected Behaviour

Rather than exiting on a KeyError, get_good_inter_pae.py could inform the user that none of the provided jobs met the quality criterions and therefore the script exists and writes out an empty predictions_with_good_interpae.csv file.

Alternatively, one could get rid of the cutoff all together and mention it in the generated table instead. This would allow for filtering in post.

## Reproducible Example

Either fold Q8I2G6 and Q8I5K4 in custom mode with 3 recycles and one prediction per model on the most recent release of AlphaPulldown using the specified conda environment and run_get_good_pae.sh using a cutoff of 5.0, or take an arbitratry better scoring fold and reduce the cutoff to a small number, e.g. 0.1

**Comment by dingquanyu** [comment]
Issue solved by: https://github.com/KosinskiLab/AlphaPulldown/blob/51135b5a992b8b11dfb73656e3cc325a4d9fb6ad/alphapulldown/analysis_pipeline/get_good_inter_pae.py#L143-L145
