### ISSUE TITLE
Setting tensorflow>=2.14.0 leads to incompatible cuda

### ISSUE THREAD

**Issue by kashyapchhatbar** [KosinskiLab/AlphaPulldown#296]
Hi AlphaPulldown developers,

Having the requirements for tensorflow>=2.14.0 leads to a tensorflow 2.16.1 install which does not support cuda11 versions. Because majority of the clusters do not have support for cuda12 and anaconda installs cudatoolkit==11.8.0 anyways, this leads to an issue where the GPU is not used. 

Once I reverted to 2.14.0, everything worked.

Thanks.

**Comment by dingquanyu** [comment]
Thanks a lot for the suggestion! Will change it in the config file.
