### ISSUE TITLE
database setup - HHblits reference

### ISSUE THREAD

**Issue by WardDeb** [KosinskiLab/AlphaPulldown#310]
Hi,

I'm trying to set up the alphapulldown, and have followed the instructions to create the database.
Upon trying the test files, I received an error regarding the uniref30 / HHBlits database:
`
ValueError: Could not find HHBlits database REDACTED/uniref30/UniRef30_2023_02`

The default "uniref30/UniRef30_2023_02" string is hardcoded in create_individual_features.py.
The download link under the alphafold repository points to a version from 2021.

Should the link be updated to one from 2023 ? Or should the default be changed to the 2021 version ?

Thanks 

WardDeb

**Comment by dingquanyu** [comment]
Hi,

Sorry we forgot to update the link in the readme. You're correct. Please use the 2023 version.

Yours
Dingquan

**Comment by WardDeb** [comment]
Great, thanks for the confirmation !
