### ISSUE TITLE
pi-score outputs

### ISSUE THREAD

**Issue by salomonssonj** [KosinskiLab/AlphaPulldown#329]
Hi,

In the previous version of AlphaPulldown we obtained a folder with outputs from pi-score, such as interface residues and interface chain contacts. Is it possible to get these files for AP2.0 as well? We find them quite useful when evaluating the predications.

Kindly,
Johannes

**Comment by dingquanyu** [comment]
Hi Johannes,

Sorry in the new version I moved this step to be done within a temporary directory, which will remove the intermediate files after the calculations. You still can find these parameters in the final csv table. 

Yours
Dingquan

**Comment by jkosinski** [comment]
Hmm, I think Johannes means *lists* of "interface residues and interface chain contacts", which are not in the table. If that info is there, I think we should keep those folders indeed!

**Comment by dingquanyu** [comment]
I see. I will change it so it keeps the output folder.

**Comment by salomonssonj** [comment]
Great, much appreciated. Thank you!

**Comment by DimaMolod** [comment]
@maurerv then we need to revert back snakemake file. Can we move the files only if they are available so that it doesn't lead to crash?

**Comment by dingquanyu** [comment]
> @maurerv then we need to revert back snakemake file. Can we move the files only if they are available so that it doesn't lead to crash?

@DimaMolod maybe it's better that you create an issue in the snakemake repo and refers to this issue, otherwise this one will be closed once the #330 PR is merged and you may lose the track
