### ISSUE TITLE
Update documentation request

### ISSUE THREAD

**Issue by Clockris** [KosinskiLab/AlphaPulldown#338]
Hi,

I am trying to install Alphapulldown2.0 following your documentation. Unfortunately, I am still not able to run a single test because every time I get an error about something missing in my database setup even though it is identical to the configuration you describe in your documentation. So I was wondering if you could update the documentation to make it clear to me and to everyone who want to use your tool how to install and run it.
I even found some problems with your documentation in terms of broken links and errors.

Following I try to summarize the problems:

1 - in your documentation, you suggest to have the following folder structure as input:

> alphafold_database/                             # Total: ~ 2.2 TB (download: 438 GB)
>    bfd/                                   # ~ 1.7 TB (download: 271.6 GB)
>        # 6 files.
>    mgnify/                                # ~ 64 GB (download: 32.9 GB)
>        mgy_clusters_2018_12.fa
>    params/                                # ~ 3.5 GB (download: 3.5 GB)
>        # 5 CASP14 models,
>        # 5 pTM models,
>        # 5 AlphaFold-Multimer models,
>        # LICENSE,
>        # = 16 files.
>    pdb70/                                 # ~ 56 GB (download: 19.5 GB)
>        # 9 files.
>    pdb_mmcif/                             # ~ 206 GB (download: 46 GB)
>        mmcif_files/
>            # About 180,000 .cif files.
>        obsolete.dat
>    pdb_seqres/                            # ~ 0.2 GB (download: 0.2 GB)
>        pdb_seqres.txt
>    small_bfd/                             # ~ 17 GB (download: 9.6 GB)
>        bfd-first_non_consensus_sequences.fasta
>    uniclust30/                            # ~ 86 GB (download: 24.9 GB)
>        uniclust30_2018_08/
>            # 13 files.
>    uniprot/                               # ~ 98.3 GB (download: 49 GB)
>        uniprot.fasta
>    uniref90/                              # ~ 58 GB (download: 29.7 GB)

but actually I recive errors like `E0513 14:08:14.279589 140436706568000 hhblits.py:82] Could not find HHBlits database alphapulldown_db/uniref30/UniRef30_2023_02` (it is not described in your manual the uniref30/UniRef30_2023_02 folder). This is just an example, there are other situations like these.

2 - some links to the examples are broken in the documentation of the Alphapulldown2.0, but they seem to work on 1.0 version (i.e. [example_1_sequences.fasta](https://github.com/KosinskiLab/AlphaPulldown/blob/main/example_data/example_1_sequences.fasta) at https://github.com/KosinskiLab/AlphaPulldown/blob/main/manuals/example_1.md)

3 - I wasn't been able to proceed with the debugging of Example1 until I soft-linked the alphapulldown folder inside the scripts folder.

Thanks,

Cristiano

**Comment by DimaMolod** [comment]
thank you @Clockris for the report! 
We recently updated the documentation so there should be no broken hyperlinks anymore. I also updated the description of the downloaded databases, please feel free to re-open this issue if I missed anything.
Re the last point, could you provide us with more details? All scripts should be accessible and added to the PATH after installation (either `pip install .` or `pip install alphapulldown`), as described in the setup.cfg file:
https://github.com/KosinskiLab/AlphaPulldown/blob/main/setup.cfg#L72-L80

**Comment by bifxcore** [comment]
Got the same issue "Could not find HHBlits database <..>/uniref30/UniRef30_2023_02"  today.

**Comment by heejongkim** [comment]
SOURCE_URL="https://wwwuser.gwdguser.de/~compbiol/uniclust/2023_02/UniRef30_2023_02_hhsuite.tar.gz"

this is working URL as of today.
