### ISSUE TITLE
Running calculate_mpdockq.py with only PDB

### ISSUE THREAD

**Issue by busrasavas** [KosinskiLab/AlphaPulldown#341]
Hi, 
I'm trying to use your calculate_mpdockq.py for the calculation of pdockq scores of complexes with multiple chains. However I only have PDB files with pLDDT scores stored in b-factor column. This might be a silly question, but could you kindly explain to me why we need ranking_debug.json and .pkl files to obtain pLDDT? Also, would it be convenient to update the code so it can find the best pLDDT over the b-factor column?

Best regards, 
Büşra

**Comment by dingquanyu** [comment]
Hi,

It's easier for the programme to reconstruct the numpy matrix by reading from the pickle files given how the pae values are stored in these files. But indeed reading directly from PDB file b-factor column would save the programme from unnecessary reading many files.  I will take a look to see I can improve this step.

Yours
Dingquan
