### ISSUE TITLE
Replace this with non-cctbx solution

### ISSUE THREAD

**Issue by jkosinski** [KosinskiLab/AlphaPulldown#343]
https://github.com/KosinskiLab/AlphaPulldown/blob/fea07b690c311f1b3fa88ac92522ff591e4d9bbe/alphapulldown/analysis_pipeline/af2_3dmol.py#L206

This would greatly facilitate installation through EasyBuild - at the moment preparation of EasyBuild package is stalled due to this independency.

**Comment by gchojnowski** [comment]
I replace all refs to cctbx in this file with biopython. it's slower, but cctbx is not there.

**Comment by boegel** [comment]
Out of curiosity: how much slower when using Biopython?

To be clear: I'm very much in favor of getting rid of `cctbx`, since it's a pretty painful dependency from what I've seen (in terms of getting it installed)...

**Comment by gchojnowski** [comment]
bost is an issue, I guess. that's what make it faster. anyway, not a big deal here; simple code and reltively small structures.
