### ISSUE TITLE
Multiple feature directories

### ISSUE THREAD

**Issue by DimaMolod** [KosinskiLab/AlphaPulldown#352]
run_multimer_jobs.py has a flag --monomer_objects_dir that is converted later to the --features_directory when calling  run_structure_prediction.py. The types of these flags are different, it's DEFINE_list for run_multimer_jobs and DEFINE_multi_string for run_structure_prediction. To avoid unnecessary conversions, we need to unify these flags(use DEFINE_list instead of DEFINE_multi_string in run_structure_prediction.py):

https://github.com/KosinskiLab/AlphaPulldown/blob/main/alphapulldown/scripts/run_structure_prediction.py#L21-L35

**Comment by dingquanyu** [comment]
It was DEFINE_list before: https://github.com/KosinskiLab/AlphaPulldown/blob/86521057fd472083cef95d19a440a3358221376f/alphapulldown/scripts/run_multimer_jobs_refactor.py#L32-L36 but then in this commit you changed it to DEFINE_multistring: https://github.com/KosinskiLab/AlphaPulldown/blob/4ffd35451516ebbbeb38428dc4937948e6ab6667/alphapulldown/scripts/run_structure_prediction.py#L35-L37 I thought there was a reason that you used multi string?

**Comment by DimaMolod** [comment]
yes, the reason was to keep the flags in sync with run_structure_prediction.py. But DEFINE_list seems more appropriate due to back-compatibility reasons, so I suggest we use list elsewhere
