### ISSUE TITLE
Runtime of each prediction

### ISSUE THREAD

**Issue by what-is-what** [KosinskiLab/AlphaPulldown#359]
I am planning to screen approximately 4,000 proteins in pulldown mode. However, there is no way to determine the running time with the current ReadMe or instructions. Could you tell me if the time taken to predict the interaction for a bait-candidate pair is similar to that of AlphaFold2? If you could provide the running time for a single prediction, it would be easy to calculate the total running time.

**Comment by dingquanyu** [comment]
Hi,

Since the programme is based on AlphaFold Multimer, the calculations on GPU should cost similar time. Unfortunately, I cannot find a way of estimating the running time. 

Yours
Dingquan
