### ISSUE TITLE
Use DEFINE_list for model_names flag

### ISSUE THREAD

**Issue by DimaMolod** [KosinskiLab/AlphaPulldown#362]
We need to change 'model_names' flag from DEFINE_string to DEFINE_list here
https://github.com/KosinskiLab/AlphaPulldown/blob/main/alphapulldown/scripts/run_structure_prediction.py#L50-L51

and remove manual splitting in alphafold_backend here:
https://github.com/KosinskiLab/AlphaPulldown/blob/main/alphapulldown/folding_backend/alphafold_backend.py#L180-L183

**Comment by DimaMolod** [comment]
@dingquanyu, why do you need to [split by coma](https://github.com/KosinskiLab/AlphaPulldown/blob/main/alphapulldown/folding_backend/alphafold_backend.py#L181) if DEFINE_list already takes comma-separated strings?

**Comment by dingquanyu** [comment]
oh I thought you mean remove the comma separated string from the manual
