### ISSUE TITLE
'ranking_confidence' is not in the result.pkl file after the update

### ISSUE THREAD

**Issue by DimaMolod** [KosinskiLab/AlphaPulldown#367]
I think after this line:
https://github.com/KosinskiLab/AlphaPulldown/blob/main/alphapulldown/folding_backend/alphafold_backend.py#L542
there is no 'ranking_confidence' in the result.pkl file, after recalculate_confidence

```
result_pkl.keys()
Out[4]: dict_keys(['distogram', 'experimentally_resolved', 'masked_msa', 'num_recycles', 'predicted_aligned_error', 'predicted_lddt', 'structure_module', 'plddt'])
```

**Comment by DimaMolod** [comment]
there is also no 'ptm' and 'iptm' scores, the way it was:
dict_keys(['distogram', 'experimentally_resolved', 'masked_msa', 'predicted_aligned_error', 'predicted_lddt', 'structure_module', 'plddt', 'aligned_confidence_probs', 'max_predicted_aligned_error', 'ptm', 'iptm', 'ranking_confidence'])

**Comment by dingquanyu** [comment]
> there is also no 'ptm' and 'iptm' scores, the way it was: dict_keys(['distogram', 'experimentally_resolved', 'masked_msa', 'predicted_aligned_error', 'predicted_lddt', 'structure_module', 'plddt', 'aligned_confidence_probs', 'max_predicted_aligned_error', 'ptm', 'iptm', 'ranking_confidence'])

I see. It seems 'seqs' was never here anymore. I think create_notebook.py still has to be updated.

**Comment by dingquanyu** [comment]
Actually, I rerun it again and 'seqs' is among the keys
['distogram', 'experimentally_resolved', 'masked_msa', 'predicted_aligned_error', 'predicted_lddt', 'structure_module', 'plddt', 'seqs', 'unrelaxed_protein', 'aligned_confidence_probs', 'max_predicted_aligned_error', 'ranking_confidence']

**Comment by DimaMolod** [comment]
> Actually, I rerun it again and 'seqs' is among the keys ['distogram', 'experimentally_resolved', 'masked_msa', 'predicted_aligned_error', 'predicted_lddt', 'structure_module', 'plddt', 'seqs', 'unrelaxed_protein', 'aligned_confidence_probs', 'max_predicted_aligned_error', 'ranking_confidence']

hmm I just checked a random pkl from the prediction made today using [this branch](https://github.com/KosinskiLab/AlphaPulldown/tree/postprocessing_modelcif) and there is no 'seqs', must be some recent fix?..
['distogram', 'experimentally_resolved', 'masked_msa', 'num_recycles', 'predicted_aligned_error', 'predicted_lddt', 'structure_module', 'plddt']

**Comment by DimaMolod** [comment]
but I didn't update alphafold submodule, so if you introduced some changes there this could be the reason

**Comment by dingquanyu** [comment]
Interesting. Perhaps it's better to update create_notebook.py so that it parses sequences from PDB files directly anyway

**Comment by DimaMolod** [comment]
Yes, you can do this, but we need to have ptm and iptm (as well as the rest of the missing keys) in the result.pkl anyways

**Comment by dingquanyu** [comment]
ah I found where it came from. It's not from the recalculations of metrics but rather here: https://github.com/KosinskiLab/AlphaPulldown/blob/b791e1b65cff7583cd28c9fcb08e188a46db077e/alphapulldown/folding_backend/alphafold_backend.py#L397-L403 the pickle was dumped before the dictionary got updates on the missing keys.

**Comment by dingquanyu** [comment]
Plus the calculation of iptm iptm+ptm etc were moved to post processing after your restructuring

**Comment by DimaMolod** [comment]
Good catch!
