### ISSUE TITLE
Merging individual monomer MSAs for multimer prediction

### ISSUE THREAD

**Issue by denizkavi** [KosinskiLab/AlphaPulldown#373]
I have monomer MSAs generated for each sequence in a complex, how might I combine them to be used in a multimer structure prediction? I saw https://github.com/sokrypton/ColabFold/issues/601 discusses this, where the authors propose using monomer structure predictions as custom templates for the multimer structure prediction. But would prefer to maintain the same methodology as AF-Multimer for consistency.

**Comment by denizkavi** [comment]
Also discussed here: https://github.com/sokrypton/ColabFold/issues/76

**Comment by dingquanyu** [comment]
Hi Deniz,

Certainly it can be achieved in AlphaPulldown. You can use make your selected structures to replace the default template features when running ```run_multimer_jobs.py``` by adding the flags ```--multimeric_template --description_file=/path/to/descrption.csv```

```multimeric_template```is a boolean flag that will inform AlphaPulldown to look for customised template structures and replace the original template features. ``´ description_file.csv```should be in the following format:
```
protein_A,xxx.pdb,C
```
indicating your query sequence ```protein_A```should be mapped to chain C your pdb file ```xxx.pdb```, suppose you already had ```protein_A.pkl```

In addition, the actual sequence of the chain in the PDB does not necessary have to be the same as the protein_A sequence, as AlphaPUlldown will realign the sequences anyway but it will always better if your template covers as many residues as it can.

On the other hand, you can also regenerate the pickle files as described here: https://github.com/KosinskiLab/AlphaPulldown/blob/main/manuals/example_3.md 

Yours
Dingquan

**Comment by DimaMolod** [comment]
Please also refer to the TrueMultimer sections of the new manual:
https://github.com/KosinskiLab/AlphaPulldown?tab=readme-ov-file#14-run-with-custom-templates-truemultimer
https://github.com/KosinskiLab/AlphaPulldown?tab=readme-ov-file#25-run-with-custom-templates-truemultimer
