### ISSUE TITLE
create_notebook doesn't work on AlphaPulldown 2.0b?

### ISSUE THREAD

**Issue by gebauer** [KosinskiLab/AlphaPulldown#385]
Hi, 

first of all, thanks for the great software suite. 

I just update to 2.0b2, however, after I calculated all the neccesary data the "create_notebook.py" does crash with this error:

```
create_notebook.py --cutoff=50.0 --output_dir=/home/gebauer/AF_jobs/XXX/XXXX/all/pulldown3
I0719 14:12:06.239858 133758447294272 create_notebook.py:97] now processing XXXXX_and_YYYYY
Traceback (most recent call last):
  File "/home/gebauer/miniforge3/envs/AlphaPulldown2/bin/create_notebook.py", line 150, in <module>
    app.run(main)
  File "/home/gebauer/miniforge3/envs/AlphaPulldown2/lib/python3.10/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/home/gebauer/miniforge3/envs/AlphaPulldown2/lib/python3.10/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/home/gebauer/miniforge3/envs/AlphaPulldown2/bin/create_notebook.py", line 110, in main
    seqs = pickle.load(gzip.open(result_path, "rb"))["seqs"]
KeyError: 'seqs'
```

Any idea why this happens? The predictions otherwise look fine.

**Comment by dingquanyu** [comment]
Hi

Thanks for your interest in our package and reporting this. We're fixing the issue in the create_notebook.py on a branch now.

Yours
Dingquan

**Comment by gebauer** [comment]
I wonder if I did something wrong here. 
If I compare the two pickle files generated by version 1.0.4 and 2.0.0b2 they are remarkably different:
> python  compare_pickle.py v1.0.4/result_model_1_multimer_v3_pred_0.pkl v2.0.0b/pulldown3/Q00613_and_A0JLT2/result_model_2_multimer_v3_pred_0.pkl.gz
Differences in structure between the two pickle files:
{ 'dictionary_item_removed': [root['aligned_confidence_probs'], root['max_predicted_aligned_error'], root['ptm'], root['iptm'], root['ranking_confidence'], root['seqs']],
  'type_changes': { "root['predicted_aligned_error']": { 'new_type': <class 'dict'>,
                                                         'new_value': { 'asym_id': 'ndarray',
                                                                        'breaks': 'ndarray',
                                                                        'logits': 'ndarray'},
                                                         'old_type': <class 'str'>,
                                                         'old_value': 'ndarray'}}}

The file organisation is also vastly different between this two versions. I haven't found anything about this major changes in output files in the update notes - so I wonder if I am doing something wrong here. Is the create_notebook.py working on your site? Or are you not really using that script for your analysis? How are you evaluating v.2.0.0b2 runs?

Kind regards,
Jan Gebauer

**Comment by dingquanyu** [comment]
Hi @gebauer 
You're right we aimed to get rid of the dependencies in the pickles to avoid crashes during the analysis steps. The create_notebook.py should be fixed now in the new release. Please let me know if the new version works for you. 

Yours
Dingquan

**Comment by gebauer** [comment]
Hi Dinquan,

in the hope you will fix it I am currently running a pulldown on my server, after it is finished I'll update AFP and report back.

Best and thanks for the good work!
Jan

**Comment by gieses** [comment]
@dingquanyu I see that there is a lot going on in the repo so I am not sure if this is helpful to share now (:. Two things that I noticed with a7f6506 release:

1) the af_plot package needs to be installed manually (pip to the local folder worked)
2) the import in [create_notebooks](https://github.com/KosinskiLab/AlphaPulldown/blob/a7f6506a21b27cac5bb33766868d3dbfe2bf0f1b/alphapulldown/analysis_pipeline/create_notebook.py#L17) should possibly start with alphapulldown.analysis_pipeline.

**Comment by dingquanyu** [comment]
> 2\. the import in [create_notebooks](https://github.com/KosinskiLab/AlphaPulldown/blob/a7f6506a21b27cac5bb33766868d3dbfe2bf0f1b/alphapulldown/analysis_pipeline/create_notebook.py#L17) should possibly start with alphapulldown.analysis_pipeline.

Thanks for your suggestions @gieses ! regarding this point, in our config file, analysis_pipeline is actually going to be installed as a package of its own and appended to the PYTHONPATH after the pip install so the conda env is able to import directly the utils from analysis_pipline https://github.com/KosinskiLab/AlphaPulldown/blob/a7f6506a21b27cac5bb33766868d3dbfe2bf0f1b/setup.cfg#L44

**Comment by dingquanyu** [comment]
> 1. the af_plot package needs to be installed manually (pip to the local folder worked)

@gieses  The same thing with the af_plot package. It will be installed as a standalone package and added to the PYTHONPATH. I could import ```from af2plots.plotter import plotter``` directly within the conda env after pip installing AlphaPulldown current beta version.
https://github.com/KosinskiLab/AlphaPulldown/blob/a7f6506a21b27cac5bb33766868d3dbfe2bf0f1b/setup.cfg#L45

**Comment by DimaMolod** [comment]
Closing as this issue has already been solved.
