### ISSUE TITLE
Remove result pickles

### ISSUE THREAD

**Issue by jkosinski** [KosinskiLab/AlphaPulldown#390]
### Discussed in https://github.com/KosinskiLab/AlphaPulldown/discussions/389

<div type='discussions-op-text'>

<sup>Originally posted by **rukibuki** July 30, 2024</sup>
Hi,
As we are planning to scale up our APD projects significantly and move to a HPC center, I have been playing around with the --remove_result_pickles options. I have not been able to get it to work yet. The compress_result_pcikles seems to work, but that is not really what I am after.

So latest test run I used this combo: 

		--compress_result_pickles=False \
		--remove_result_pickles=True \

and in the log I see this:

rm: cannot remove 'result_model_1_multimer_v3_pred_0.pkl': No such file or directory
rm: cannot remove 'result_model_4_multimer_v3_pred_0.pkl': No such file or directory
rm: cannot remove 'result_model_3_multimer_v3_pred_0.pkl': No such file or directory
rm: cannot remove 'result_model_2_multimer_v3_pred_0.pkl': No such file or directory

It does not state where it is trying to remove the files from, but considering it just created the .pkl files in a specified folder, I am assuming it is within the same folder, but it is failing for some reason. 

So the files are present in the corresponding folder inside the pulldown folder.

-rw-rw-r--+ 1 rtk rtk 1.8G Jul 29 15:24 result_model_1_multimer_v3_pred_0.pkl
-rw-rw-r--+ 1 rtk rtk 1.8G Jul 29 15:32 result_model_2_multimer_v3_pred_0.pkl
-rw-rw-r--+ 1 rtk rtk 1.8G Jul 29 15:40 result_model_3_multimer_v3_pred_0.pkl
-rw-rw-r--+ 1 rtk rtk 1.8G Jul 29 15:48 result_model_4_multimer_v3_pred_0.pkl
-rw-rw-r--+ 1 rtk rtk 1.8G Jul 29 15:56 result_model_5_multimer_v3_pred_0.pk

Also, why is it only trying (and failing) to remove 4 .pkl files (model 5 is missing), why not all 5 since that is what is being produced?
How are you guys getting this feature to work?

Ruki</div>

**Comment by DimaMolod** [comment]
On top of this bug, the logic seems corrupted:
https://github.com/KosinskiLab/AlphaPulldown/blob/main/alphapulldown/utils/post_modelling.py#L12-L20
when `--remove_pickles` and `--zip_pickles` are both True, it only removes the pickles, not zipping the 'best_model_result.pkl'.
I would remove --remove-pickle at all since it interferes with --resume_prediction and I would remove pickles only when copying the results with `truncate_pickles.py` @gilep
