### ISSUE TITLE
question: correct pipeline for mmseqs alignments in alphapulldown?

### ISSUE THREAD

**Issue by gieses** [KosinskiLab/AlphaPulldown#391]
Currently, I am not able to combine mmseqs alignments with the most recent alphapulldown code base. I have a few questions to check if I understood correctly from [here](https://github.com/KosinskiLab/AlphaPulldown/blob/main/manuals/mmseqs2_manual.md) and if the information is still correct. 

1) I ran the alignment with colabfold and got the .a3m files (is it correct that these are single alignments, e.g. all baits and the query in individual entries in the fasta or should it always be baits + query separated by ":"?)

**Note**: Colabfold changed the naming to return the full fasta header, replacing most of the unfriendly characters with "_"

2) Is the renaming script still needed here? When I ran it in this directory it renames everything to a single file 101.a3m

3) Proceeding with the FASTA names (without the renaming because it seems to be a valid format), I tried to run

```
(alphapulldown) ➜  AlphaPulldown git:(main) ✗ python alphapulldown/scripts/create_individual_features.py --fasta_paths=example/fasta/all.fasta --data_dir=/data/openfold/ --output_dir=example/aln/af_colab --max_template_date=2025-01-01
```
where example/aln/af_colab pointed to the directory with the a3m files and all.fasta contained all **single** sequences.

4) Running this command starts jackhmmer again which I think should not happen? it says "Will use hmmsearch looking for templates" so maybe that is intended?
5) Trying to follow [Option 2 ](example/aln/af_colab) details for the mmseqs guideline, I run into two issues. 1) the max template date is required and 2) if this is set path_to_mmt is required.

So trying this for example, does not work:
```
python alphapulldown/scripts/create_individual_features.py --fasta_paths=example/fasta/all.fasta --data_dir=/data/openfold/ --output_dir=example/aln/af_colab --skip_existing=False --use_mmseqs2=True --max_template_date=2025-01-01
```

Adding use_precomputed_msas does not help either, it just starts the jackhmmer alignment vs. uniref

This is running with colabfold 1.5.5, AlphaPulldown (30efa3f).

Thanks for any help and comments!

**Comment by DimaMolod** [comment]
Hi @gieses and thanks for your interest in AlphaPulldown!
I am sorry, I wasn't coding this part, but I think you can generate features with mmseqs directly using AlphaPulldown and ColabFold remote API.
Could you please try to install the latest beta release of AP and generate features using a command like this one:

`create_individual_features.py  --fasta_paths=/path/to/fasta.fasta     --data_dir=/path/to/alphafold/databases    --save_msa_files=True     --output_dir=/path/to/output/dir      --max_template_date=2050-01-01   --skip_existing=True (optional) --use_mmseqs2`

Please let me know if it works for you now.

**Comment by jkosinski** [comment]
Dear @gieses, if you still want to use the local colabfold search alignments, this is indeed got broken with the changes in colabfold and we need to fix it. If it starts the jackhmmer alignment vs. uniref it likely means that the renaming script is still needed and to be fixed as apparently use_precomputed_msas does not recognize the MSAs and re-runs the search. 

Regarding the template search - unfortunately, currently, in this mode, the template search still needs to be run locally. 

The ") the max template date is required and 2) if this is set path_to_mmt is required" is unintended and we should fix it.

Thanks for testing this mode and reporting the issues in detail!

**Comment by mat-jones** [comment]
Hi all,
I was wondering if you managed to fix this or know a workaround as I also have locally generated a3m files which I'd like to use.
Thanks! (and thanks for this piece of software!)
Matt

**Comment by jkosinski** [comment]
We will try to fix it this week.

**Comment by jkosinski** [comment]
Dear @gieses, your case is similar to https://github.com/KosinskiLab/AlphaPulldown/issues/378

Could you try this:
1. Copy your directory with colabfold a3m files (just for safety, below procedure is not well tested)
2. Enter the directory
3. Execute the script below like this: 
```
python rename_colab_search_a3m.py path_to_fasta_file_you_used_as_input_for_colabfold_search
```
4. Double check a couple of random files that files were properly renamed.
5. Run the create_individual_features.py again


The script (copy this to a new file and name it rename_colab_search_a3m.py):
```python
#!/usr/bin/env python3
import glob
import os
import sys
from itertools import groupby

def fasta_iter(fh):
    """Return iterator over FASTA file with multiple sequences.

    Modified from Brent Pedersen
    Correct Way To Parse A Fasta File In Python
    given a fasta file. yield tuples of header, sequence

    :param fh: File Handle to the FASTA file

    :return: 2-element tuple with header and sequence strings
    """

    # ditch the boolean (x[0]) and just keep the header or sequence since
    # we know they alternate.
    faiter = (x[1] for x in groupby(fh, lambda line: line[0] == ">"))

    for header in faiter:
        # drop the ">"
        headerStr = header.__next__()[1:].strip()

        # join all sequence lines to one.
        seq = "".join(s.strip() for s in faiter.__next__())

        yield (headerStr, seq)

def fastafn2seqs(fasta_fn):
    """Extract sequences from a FASTA file."""
    seqs = []
    with open(fasta_fn) as f:
        for header_str, seq in fasta_iter(f):
            seqs.append((header_str, seq))
    return seqs

def main(input_fasta_fn=None):
    """Rename all .a3m files in the current directory.

    Old colabfold: Rename all .a3m files to the name of the first sequence in the respective file.
    New colabfold: Rename all .a3m files to the names used in the input fasta file.
    """
    fn_idx = 0
    files = sorted(glob.glob("*.a3m"), key=lambda x: int(os.path.splitext(x)[0]))

    if input_fasta_fn:
        in_seqs = fastafn2seqs(input_fasta_fn)
    
    for file in files:
        this_seqs = fastafn2seqs(file)
        name = this_seqs[0][0]

        if name == '101':  # New colabfold
            if not input_fasta_fn:
                raise ValueError('Please provide the input FASTA file used for colabfold_search')
            name = in_seqs[fn_idx][0]
            this_seqs[0] = (name, this_seqs[0][1])

        outfile = f"{name}.a3m"
        print(f"Renaming {file} to {outfile}")
        with open(outfile, 'w') as f:
            for header, seq in this_seqs:
                f.write(f">{header}\n{seq}\n")
        os.remove(file)

        fn_idx += 1

if __name__ == '__main__':
    if len(sys.argv) == 2:
        main(sys.argv[1])
    else:
        main()
```
