### ISSUE TITLE
Move Databases download to a common installation step for both snakamake and Python CLI modes?

### ISSUE THREAD

**Issue by jkosinski** [KosinskiLab/AlphaPulldown#394]
The snakemake repo does not explain how to install databases so this step should be explained for both, maybe by moving it ealier as a common step?
https://github.com/KosinskiLab/AlphaPulldown/blob/bd1f278ce4c07c7a03916027be2bb89fbb5f12f1/README.md?plain=1#L120

**Comment by DimaMolod** [comment]
Fix in 18d61c99b950509db8301c59ebf498021342542b
