### ISSUE TITLE
jax installation version issue

### ISSUE THREAD

**Issue by jansteinkuehler** [KosinskiLab/AlphaPulldown#398]
I was encountering errors (segfaults or no GPU usage) when following the procedure described in the README section 0.2 with the following command:

`pip install jax==0.4.27 \
            jaxlib==0.4.27+cuda12.cudnn89 \
            -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html`

However, when I followed the instructions on the JAX website (https://jax.readthedocs.io/en/latest/installation.html) using this command:

`pip install -U "jax[cuda12]"`

Things are working for me. 

Setup: Cuda 11.8.0, Alphapulldown 2.0.0b4

**Comment by DimaMolod** [comment]
thank you @jansteinkuehler for your comment! Good to know that installing jax for cuda12 works even for cuda11. 
I will change the README accordingly.
Btw according to the jax site, NVIDIA has released CUDA pip packages only for x86_64 and aarch64; on other platforms you must use a local installation of CUDA.
