### ISSUE TITLE
A question about the seq_index argument in job array mode

### ISSUE THREAD

**Issue by swanss** [KosinskiLab/AlphaPulldown#43]
Hi,

Is it possible to use job arrays, but assign more than one prediction per job? I have ~400 interacting pairs and I would like to be able to request an array of 10 nodes to each predict complexes for 40 of them. If this doesn't already exist and you don't mind,  I could implement the feature myself and make a pull request.

Best,
Sebastian

**Comment by henrywotton** [comment]
Hi,

Sorry we haven't included this feature in the programme and it could help users with similar needs. Please feel free to create a PR. Thanks in advance. 

Yours
Dingquan
