### ISSUE TITLE
Shouldn't tests be run for user installation too?

### ISSUE THREAD

**Issue by jkosinski** [KosinskiLab/AlphaPulldown#438]
https://github.com/KosinskiLab/AlphaPulldown/blob/51849fc1874be9906f6439664917029dff74a7bd/.github/workflows/github_actions.yml#L63

Do I understand correctly that we only run tests for the developer installation but not for the user?

**Comment by DimaMolod** [comment]
Done in https://github.com/KosinskiLab/AlphaPulldown/commit/e73beba9b2dcf4c362b5e582501d9499bbadc337
