### ISSUE TITLE
Update PyPi version for the Biopython fix?

### ISSUE THREAD

**Issue by jkosinski** [KosinskiLab/AlphaPulldown#443]
Currently this is run in the tests:
https://github.com/KosinskiLab/AlphaPulldown/blob/a282ff8fbb03d8bbaf7fbf5cf1c90e7718942fb9/.github/workflows/github_actions.yml#L45
but it is not in the user instructions:
https://github.com/KosinskiLab/AlphaPulldown/tree/main?tab=readme-ov-file#02-installation-using-pip
so installing according to the documentation crashes on that `ImportError: cannot import name 'SCOPData' from 'Bio.Data'` error. Could you update the PyPi version or update the documentation to downgrade Biopython?

PS. In general, ideally the 'user' github action in the tests should reflect the procedure in the documentation as close as possible.

**Comment by DimaMolod** [comment]
Fixed in 4e4c86be2de0fca53f0eac1611f5af8f64a2e8fd and 5dae35b2e849221bf94e6b1950b6b548b5885845
