### ISSUE TITLE
Why limiting output directory to 100?

### ISSUE THREAD

**Issue by jkosinski** [KosinskiLab/AlphaPulldown#454]
Why limiting to 100 here?
https://github.com/KosinskiLab/AlphaPulldown/blob/f6085e25ba2aa9ab0d1897510aa816113df7e27c/alphapulldown/scripts/run_structure_prediction.py#L227

I have a job like this:
`P32349;P32910;P17890;P47076;P35718;P04051,1-550,872-927,1083-1139,1317-1560;P22276,1028-1149;P20435`
I can't shorten it and filesystem can handle this name...

Would the following code work better? (from chatgpt):
```python
import os

# Specify the directory path you want to check
directory_path = '/'

# Get the maximum length of directory names in the specified directory
max_dir_name_length = os.pathconf(directory_path, 'PC_NAME_MAX')

```

PS. We may need to address how to accept even longer names in the future with some alternative folder naming convention...

**Comment by DimaMolod** [comment]
I don't think it's a good idea to use very long output dir names in general, I would rather use `--output_directory` flag for `run_structure_prediction.py` and created a note with the complex specification as a text file there (or maybe it's already hidden there, need to check)

**Comment by DimaMolod** [comment]
so, as a possible solution: when using old AP style and name length>100 -> call output dir e.g. `prediction_1` and put a txt file with description inside

**Comment by jkosinski** [comment]
I agree and some short name scheme (just maybe more informative eg. first 50 characters plus random string) with description inside would be good but we should not be changing this for the version 2. I need this specific job for the TrueMultimer EMBO course but let me see if I can run a longer fragment (longer fragment -> less ranges -> shorter name)

**Comment by jkosinski** [comment]
OK, won't work even with `P32349+P32910+P17890+P47076+P35718+P04051+P22276+P20435` which is 55 characters. Isn't the code accidentally checking the full path while it should check just the basename?

**Comment by jkosinski** [comment]
OK, will you be able to still fix it this week? Would need it to proceed with the course prep...
