### ISSUE TITLE
Incorrect if statement causing to crash when using compressed pickles?

### ISSUE THREAD

**Issue by jkosinski** [KosinskiLab/AlphaPulldown#457]
Hi,

Currently the snakemake pipeline crashes in prediction when using compressed pickles:
```
Traceback (most recent call last):
  File "/opt/conda/bin/run_structure_prediction.py", line 283, in <module>
    app.run(main)
  File "/opt/conda/lib/python3.10/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/opt/conda/lib/python3.10/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/opt/conda/bin/run_structure_prediction.py", line 253, in main
    parsed_input = parse_fold(FLAGS.input, FLAGS.features_directory, FLAGS.protein_delimiter)
  File "/opt/conda/lib/python3.10/site-packages/alphapulldown/utils/modelling_setup.py", line 81, in parse_fold
    raise FileNotFoundError(
FileNotFoundError: {'P17890', 'P32349', 'P32910'} not found in ['/scratch/kosinski/IntegrativeCourse2024/AlphaPulldown/snakemake/features']
```
I think this is due to incorrect if statement here:
https://github.com/KosinskiLab/AlphaPulldown/blob/dd10f455c0f52304de41bc2410844295950c30b5/alphapulldown/utils/modelling_setup.py#L73
which evaluates to False if pkl.xz file exists but pkl does not. Note:
```python
>>> not(any([False, True]))
False
```

**Comment by DimaMolod** [comment]
Good catch! I think this line can be simplified:
```python
if not any(exists(join(monomer_dir, f"{name}{ext}")) 
           for monomer_dir in features_directory 
           for ext in [".pkl", ".pkl.xz"]):
    missing_features.append(name)
``` 
but because of snakemake we currently can't mix .pkl and .pkl.xz so then here we should forbid mixing too?
One idea that Valentin had is to get rid of extension at all (or use smth unique e.g. *.ftr), then determine type of archive using magic bytes and decompress using standard python libraries.

**Comment by jkosinski** [comment]
It's not because of mixing but rather wrong "if" statement (all my pkls are compressed)

**Comment by jkosinski** [comment]
> Good catch! I think this line can be simplified:
> 
> ```python
> if not any(exists(join(monomer_dir, f"{name}{ext}")) 
>            for monomer_dir in features_directory 
>            for ext in [".pkl", ".pkl.xz"]):
>     missing_features.append(name)
> ```
> 
> but because of snakemake we currently can't mix .pkl and .pkl.xz so then here we should forbid mixing too? One idea that Valentin had is to get rid of extension at all (or use smth unique e.g. *.ftr), then determine type of archive using magic bytes and decompress using standard python libraries.

The modified code still would evaluate wrong: 
```python
from os.path import join, exists
from typing import List


def check_missing_features(names: List[str], features_directory: List[str]) -> List[str]:
    """
    Check for missing features in the given directories.

    Args:
        names (List[str]): List of feature names to check.
        features_directory (List[str]): List of directories to search.

    Returns:
        List[str]: Names of missing features.
    """
    missing_features = []

    for name in names:
        if not any(exists(join(monomer_dir, f"{name}{ext}")) 
                for monomer_dir in features_directory 
                for ext in [".pkl", ".pkl.xz"]):
            missing_features.append(name)

    return missing_features


# Unit test
import unittest
from unittest.mock import patch


class TestCheckMissingFeatures(unittest.TestCase):

    @patch("os.path.exists")
    def test_missing_features(self, mock_exists):
        # Mock setup: Assume certain files exist
        mock_exists.side_effect = lambda path: {
            "dir1/feature1.pkl": False,
            "dir1/feature1.pkl.xz": True
        }.get(path, False)

        # Input data
        names = ["feature1"]
        features_directory = ["dir1"]

        # Expected result that nothing is missing
        expected_missing = []

        # Function call
        result = check_missing_features(names, features_directory)

        # Assert
        self.assertEqual(result, expected_missing)

if __name__ == "__main__":
    unittest.main()

```

**Comment by DimaMolod** [comment]
> It's not because of mixing but rather wrong "if" statement (all my pkls are compressed)

of course, I mean that we can solve this plus make it possible to mix if we use magic bytes

**Comment by jkosinski** [comment]
ah, ok, I think the below works, but I haven't tested well - the key is that the entire loop needs to be within the any() statement:
```
    for name in names:
        if not any([exists(join(monomer_dir, f"{name}{ext}")) 
                    for ext in [".pkl", ".pkl.xz"]] 
                        for monomer_dir in features_directory):
            missing_features.append(name)
```

**Comment by DimaMolod** [comment]
> ah, ok, I think the below works, but I haven't tested well - the key is that the entire loop needs to be within the any() statement:
> 
> ```
>     for name in names:
>         if not any([exists(join(monomer_dir, f"{name}{ext}")) 
>                     for ext in [".pkl", ".pkl.xz"]] 
>                         for monomer_dir in features_directory):
>             missing_features.append(name)
> ```

Thank you Jan, I'll test and commit ASAP!

**Comment by jkosinski** [comment]
> > ah, ok, I think the below works, but I haven't tested well - the key is that the entire loop needs to be within the any() statement:
> > ```
> >     for name in names:
> >         if not any([exists(join(monomer_dir, f"{name}{ext}")) 
> >                     for ext in [".pkl", ".pkl.xz"]] 
> >                         for monomer_dir in features_directory):
> >             missing_features.append(name)
> > ```
> 
> Thank you Jan, I'll test and commit ASAP!

But please double-check and maybe add a unittest later ;-)

**Comment by jkosinski** [comment]
Still doesn't work for me ... Does it work for you in the snakemake pipeline run?

FYI I deployed anew with 
```
snakedeploy deploy-workflow \
  https://github.com/KosinskiLab/AlphaPulldownSnakemake \
  AlphaPulldownSnakemake \
  --branch main
```

**Comment by DimaMolod** [comment]
it might be not enough. Try to delete the old directory and deploy again?.. 
I didn't try snakemake, only pytests

**Comment by jkosinski** [comment]
Yes, it's all rerun from scratch and new images got downloaded. Maybe you test next week when time. Example data and config is here: 
```
/g/kosinski/kosinski/IntegrativeCourse2024/AlphaPulldown/AlphaPulldownSnakemake
```

**Comment by DimaMolod** [comment]
@jkosinski I ran your example and it worked for me as expected.
Maybe you forgot to mount `/g/alphafold` when running snakemake? If so, then symlink points to a non-existing drive and features can't be reached. 
My full command for the reference:
`snakemake   --use-singularity   --singularity-args "-B /scratch:/scratch \
    -B /scratch_cached:/scratch_cached -B /g/alphafold/ \
    --nv "   --jobs 5   --restart-times 3   --profile slurm_noSidecar   --rerun-incomplete   --rerun-triggers mtime   --latency-wait 60 --keep-going`

**Comment by jkosinski** [comment]
Yeah, "-B /g/alphafold/" fixes the issue, thanks! Could you add it to the documentation that every disk that is used should be bound link this? Maybe the error message could be also more informative but we can think about it later how to check what's the reason for missing files.

**Comment by DimaMolod** [comment]
Closing...
