### ISSUE TITLE
CUDA out of memory error when running multimer 

### ISSUE THREAD

**Issue by kdneuro** [KosinskiLab/AlphaPulldown#48]
Hi, 

I'm running run_multimer_jobs.py in pulldown mode with one bait protein and 100 candidate proteins. The bait is 300 amino acids and candidates are each 150 amino acids. I've been getting `RuntimeError: INTERNAL: Failed to load in-memory CUBIN: CUDA_ERROR_OUT_OF_MEMORY: out of memory` every time I run the script after about 6-12 bait-candidate pairs. I can manually delete the completed runs and resume, but it's time-consuming to have to watch the script. Is there a memory leak somewhere that can be remedied? 

I have an RTX 3090 with 24GB of GPU RAM.

**Comment by henrywotton** [comment]
Hi,

Based on your description, I suppose all these 100 predictions are running one after another on your GPU? I'm afraid the memory is not enough for this case. As our package is built upon AlphaFold's own prediction pipeline which doesn't free up RAM occupied by tensors when they are no longer needed, AlphaPulldown doesn't free up RAM, either. 

I'm sorry we haven't anticipated scenarios like this and only optimised the programme for running predictions in an array fashion. We will add features and avoid piling up unused data in future releases. 

Yours,
Dingquan

**Comment by henrywotton** [comment]
Hi,

Just writing to check if it's solved now/

Cheers
Dingquan
