### ISSUE TITLE
Create requirements.txt

### ISSUE THREAD

**Issue by gezmi** [KosinskiLab/AlphaPulldown#50]
Hi,

nice application of AF2. For me, conda installation did not work, so I would like to try an other virtual environment. Could you please provide a requirements.txt file for installation?

Thank you very much!

**Comment by henrywotton** [comment]
Hi,

Thanks for your interest in our package. Could you tell us what kind of error you got when you tried the conda installation? The requirements are pretty much there in this command:
`conda create -n AlphaPulldown -c omnia -c bioconda -c conda-forge python==3.7 openmm pdbfixer kalign2=2.04 cctbx-base
`
only requires python3.7, openmm etc. as listed in this command and I don't see a particular need for a requirements.txt

If you still need such a text file, I can prepare one later, but it will only contain the same dependencies as the above command. Installation by the command or the requirement file won't make a difference I believe. 

Yours
Dingquan

**Comment by henrywotton** [comment]
Hi,

Sorry just checking if the installation error is resolved? 

Yours
Dingquan
