### ISSUE TITLE
Interpretation of output

### ISSUE THREAD

**Issue by nduan1** [KosinskiLab/AlphaPulldown#54]
Hi,

Thanks for your help! I was successfully running the pipeline with pulldown mode followed the example1 with one bait sequence against 30,000 candidates sequences. There are multiple pdb file as output. I am wondering if all these pdb are the structure of interaction between the bait and candidates? No pdb is only for the bait or candidate? Do I need to run alphafold again to get the structure for each candidates?

Thanks,

Ning

**Comment by henrywotton** [comment]
Hi,

Glad it helped! Yea the pulldown mode predicts all combinations, in your case, between that one bait and the rest of 30K candidates. I supposed you ended up having 30K subfolders. Each of them will have a multimeric model of the bait and the corresponding candidate. Sorry pulldown mode won't give a monomeric structure for the bait or the candidates individually. 

If you'd like to predict the monomeric structures, homo-oligomer mode would be helpful. Simply add nothing or 1 after protein's name  would give you the monomeric structure.

Yours
Dingquan

**Comment by henrywotton** [comment]
Hi,

Just writing to check if it's resolved?

Cheers
Dingquan

**Comment by nduan1** [comment]
Hi Dingquan,

Thanks for your clarification on the questions! It totally make sense. I have got the result from the pipeline. It works so well!

Best,

Ning
