### ISSUE TITLE
modeling of higher-order oligomers question

### ISSUE THREAD

**Issue by pillepalle123** [KosinskiLab/AlphaPulldown#56]
I was wondering how to use the high throughput modeling of higher-order oligomers?
is this part of the custom mode?
It reads like it would be possible to circumvent the AF-multimer size limitation by using AlphaPulldown, just not sure if I misunderstood it.
Thx!

**Comment by henrywotton** [comment]
Hi,

Sorry what kind of oligomers would you like to model? Hetero-oligomer or homo-oligomer? If it's a homo-oligomer, then homo-oligomer mode would be suitable and easy to use. If it's hetero-oligomer, then I agree with you that custom mode suits better. 

Hope it helps.

Yours 
Dingquan

**Comment by DillyOh** [comment]
Hi, 

in the same vein, I would love to be able to make a pulldown not only with single proteins, but with previously calculated multimers (in my case a 1-1-2 heterotetramer). 

Certainly a heterotretramer will open up other interaction platforms as a monomer and this is surely happening in "reality"

Is there currently any way to do this? Costum mode has a rather stringent AA cut off.

Thanks!

**Comment by jkosinski** [comment]
Hi,

Yes, this is a common request and we're working on it. But it would likely still have same "AA cut off" as AlphaFold.

Best,
Jan

**Comment by DillyOh** [comment]
Hi Jan, 

thanks for the info - I'll make sure to check back regularily!

Best
Lukas

**Comment by DimaMolod** [comment]
Hi @DillyOh! 
This can be done using multimeric templates and the TrueMultimer mode. Please refer to the documentation for the details:
https://github.com/KosinskiLab/AlphaPulldown?tab=readme-ov-file#14-run-with-custom-templates-truemultimer
https://github.com/KosinskiLab/AlphaPulldown?tab=readme-ov-file#25-run-with-custom-templates-truemultimer
