### ISSUE TITLE
--max_template_date with MMSeqs2

### ISSUE THREAD

**Issue by jkosinski** [KosinskiLab/AlphaPulldown#58]
Is the MMSeqs2 mode using --max_template_date ?

**Comment by henrywotton** [comment]
Not at all. They didn’t use it in Colabfold, either.

**Comment by jkosinski** [comment]
OK, could we then have the script return error and exit if the user tries to use --max_template_date  along with --mseqs2 option? So the user does not believe the option actually has an effect.

**Comment by henrywotton** [comment]
I think I'll simply add a warning message instead of an error
