### ISSUE TITLE
Add a warning of not overloading the remote server

### ISSUE THREAD

**Issue by jkosinski** [KosinskiLab/AlphaPulldown#60]
Add a warning like:
"To not overload the remote server, do not submit a large number of jobs at the same time. If you want to calculate MSAs for many sequences, use Option 2 below."

https://github.com/KosinskiLab/AlphaPulldown/blob/4be1ecd028ea78bcf95eaf29c86fcece297c8662/mmseqs2_manual.md?plain=1#L3

**Comment by dingquanyu** [comment]
Related to #177
