### ISSUE TITLE
data_dir really not needed?

### ISSUE THREAD

**Issue by jkosinski** [KosinskiLab/AlphaPulldown#62]
Have you tested data_dir is not needed? Isn't data_dir used to locate hhsearch database for template search? 

https://github.com/KosinskiLab/AlphaPulldown/blob/4be1ecd028ea78bcf95eaf29c86fcece297c8662/mmseqs2_manual.md?plain=1#L24

**Comment by henrywotton** [comment]
No not at all. If run mmseqs2 remotely, each protein will have their own XXX_env (with XXX being the protein's name) then hhsearch will search for template within this XXX_env folder. I've tested the command written in the manual without --data_dir and it finished without crashing.

**Comment by jkosinski** [comment]
Ah, I see, OK!
