### ISSUE TITLE
Where does it read template alignments?

### ISSUE THREAD

**Issue by jkosinski** [KosinskiLab/AlphaPulldown#63]
Nothing happens after this line?
https://github.com/KosinskiLab/AlphaPulldown/blob/6f5b7d0f5623307a4d88b084b8a37786410ee6ae/alphapulldown/objects.py#L189

**Comment by henrywotton** [comment]
I followed the logic from ColabFold's own script here but it is indeed a problem as you pointed out. If the a3m file already exists and the programme has successfully parse the alignments from the a3m file, then it will create a mock template as in here:https://github.com/KosinskiLab/AlphaPulldown/blob/6f5b7d0f5623307a4d88b084b8a37786410ee6ae/alphapulldown/objects.py#L193-L200

That means, if there is no a3m file in the outputdir, meaning the use hasn't run or successfully run mmseqs remotely for the sequence, the programme will submit the job to the mmseq server and run everything.

**Comment by jkosinski** [comment]
OK, so I guess the logging info should be removed?

**Comment by henrywotton** [comment]
yea that's right
