### ISSUE TITLE
Adding templates for local mmseqs2 mode here?

### ISSUE THREAD

**Issue by jkosinski** [KosinskiLab/AlphaPulldown#64]
In principle, you could save msa_lines as a3m or sto after this line
https://github.com/KosinskiLab/AlphaPulldown/blob/6f5b7d0f5623307a4d88b084b8a37786410ee6ae/alphapulldown/objects.py#L200

and the run local hmmer run like in the original AlphaFold:
https://github.com/deepmind/alphafold/blob/5cb2f8c480aa8314c02a93c6fbfc3f48f0ce8af0/alphafold/data/pipeline.py#L179

Or just use ColabFold hhsearch using mk_template?:
https://github.com/sokrypton/ColabFold/blob/8771fa10ce233e02efe0191ea5fb83ce3e1ca5f8/colabfold/batch.py#L149
just using the full PDB70 database from AlphaFold?

**Comment by henrywotton** [comment]
This is actually a really good idea. I think using colabfold's own template search would be neater and solve some of the key issues.

**Comment by jkosinski** [comment]
OK, so let's try with ColabFold template search. It is different to AF-multimer (HHSearch vs hmmsearch) but anyway MSAs  are different, and in principle, ColabFold pipeline has been tested only with HHSearch.
