### ISSUE TITLE
A small typo ;-)

### ISSUE THREAD

**Issue by jkosinski** [KosinskiLab/AlphaPulldown#65]
https://github.com/KosinskiLab/AlphaPulldown/blob/47036047d461f4eae10d09275a24a4f149e72fbe/alphapulldown/objects.py#L168

**Comment by henrywotton** [comment]
Is there anything wrong? it's called HhsearchHitFeaturizer in alphafold's script:
https://github.com/deepmind/alphafold/blob/5cb2f8c480aa8314c02a93c6fbfc3f48f0ce8af0/alphafold/data/templates.py#L870
Have you got an error because of this?

**Comment by henrywotton** [comment]
I see
