### ISSUE TITLE
Permission  denied. I do not know why always put this error?

### ISSUE THREAD

**Issue by yaober** [KosinskiLab/AlphaPulldown#73]
![image](https://user-images.githubusercontent.com/61397007/197723970-d2b074b7-a1cb-4b77-8c8c-3aae99cd6be2.png)

**Comment by henrywotton** [comment]
Hi,

Sorry it looks like you are trying to write directly to "/", to which we don't usually have access as a standard user on a cluster. I suggest providing ```output_dir``` with a directory owned by yourself instead. 

Hope it helps.

Yours
Dingquan

**Comment by jkosinski** [comment]
Perhaps we could change the default output_dir to current directory.
