### ISSUE TITLE
When I create predictions_with_good_interpae.csv, there is some problems

### ISSUE THREAD

**Issue by yaober** [KosinskiLab/AlphaPulldown#74]
I have 3 files, but there is just 1 results in my csv? could you help me deal with it?
![image](https://user-images.githubusercontent.com/61397007/197933967-f372261d-3910-484c-80e9-bac93d01e381.png)

![image](https://user-images.githubusercontent.com/61397007/197933934-d8dfa09d-c38b-406e-8138-5de5cab550e5.png)

![image](https://user-images.githubusercontent.com/61397007/197933898-85e650fe-7c96-42fc-8586-8a763c3d115d.png)
![image](https://user-images.githubusercontent.com/61397007/197934040-34a2fcec-2b0a-425e-999d-415e18e72d61.png)
![image](https://user-images.githubusercontent.com/61397007/197934084-4952d042-29eb-42ef-a723-020ecdb10fbd.png)

**Comment by henrywotton** [comment]
Hi,

That's because only one of those jobs satisfied the cutoff value. If you wish to include all of your jobs, you could set the cutoff to some insanely high number such as 50 then you should have all of them in the table.

Cheers
