### ISSUE TITLE
unable to execute create_individual_features.py to compute MSA

### ISSUE THREAD

**Issue by sarbanid** [KosinskiLab/AlphaPulldown#76]
Hello,

I would like to say that I was trying to run both the examples (1 and 2) as described on the Readme file, but I see a common error on both of them while attempting step 1 to compute MSA using create_individual_features.py script. I am sharing the screenshots of my terminal here. 

@henrywotton @jkosinski would you be able to help me if I am missing something while executing the script create_individual_features.py.

1.  https://github.com/KosinskiLab/AlphaPulldown/blob/main/example_1.md
Stuck at 1st step: compute multiple sequence alignment (MSA) and template features (run on CPUs) 

 
![Issue1](https://user-images.githubusercontent.com/70623767/199658368-f246b673-f847-4e2b-8583-a9cd42d636cd.png)

2. https://github.com/KosinskiLab/AlphaPulldown/blob/main/example_2.md
Stuck at 1st step: compute multiple sequence alignment (MSA) and template features (run on CPUs) 

 
![Issue2](https://user-images.githubusercontent.com/70623767/199658378-62c69bc5-168f-4d5d-b30a-5535d30cacf4.png)

Thanks in advance,
Sarbani

**Comment by henrywotton** [comment]
Hi,

Really sorry but the screenshots you sent come with really low resolution and the words on it cannot be read at all. Could you please sent us the tests of the errors instead?

Cheers

**Comment by sarbanid** [comment]
@henrywotton, I am extremely sorry for the previous screenshots, here am sending again with larger fonts.
![Issue1](https://user-images.githubusercontent.com/70623767/200297952-410be5f6-5217-47ce-8ecb-b3b12a426d3d.PNG)
![Issue2](https://user-images.githubusercontent.com/70623767/200298917-f77e54d7-e7a4-4d10-98c6-b1f1270b18a0.PNG)

**Comment by henrywotton** [comment]
Hi,

Thanks it looks much better now. This is simply because jackhammer is not installed in your environment. I guess you can solve it by running the command written in our manual:
```
source activate AlphaPulldown
conda install -c bioconda hmmer hhsuite
```
then try again.

Cheers

**Comment by henrywotton** [comment]
Hi,

Just writing to check if your problem has been solved ?

Cheers

**Comment by sarbanid** [comment]
Thank you for asking. I apologize to reply late.
That is correct I might have missed the step to install hhsuite, which I assumed I installed it while following the installing steps.

However, now I see a different issue. While executing singularity image (while following example 1), the generated report shows only PI score and not the other confidence scores like pDock/mpDock, iptm, not sure why. Should I create another thread for that.

**Comment by DimaMolod** [comment]
The singularity container was updated multiple times since then, so this issue does not seem to be relevant any more. 
Please feel free to open a new issue if you encounter any problems. 
Closing...
