### ISSUE TITLE
Error with run_multimer_jobs.py when using MMseqs2

### ISSUE THREAD

**Issue by gretabellinzona** [KosinskiLab/AlphaPulldown#77]
Hi, 

I was trying to use AlphaPulldown in the pulldown mode on my own dataset (one bait, two candidates). When I run it using the default AlphaFold databases (slower) for the 1st part all works perfectly fine, I'm able to run the 2nf and 3rd parts and I can get all the exptected results. 

However, when I try to run the 1st part using the MMseqs2 and ColabFold databases (faster option), I get an output without any warning or error, the folder has a correct structure, the files are not empty, but when I run the 2 part using the output directory as input for the --monomer_objects_dir it throws this error: 

``
2022-11-08 15:09:13.829515: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
I1108 15:09:15.153132 140580598216512 utils.py:169] checking if output_dir exists fast_models
Traceback (most recent call last):
  File "/mnt/bunnydisk/greta/miniconda3/envs/AlphaPulldown/bin/run_multimer_jobs.py", line 372, in <module>
    app.run(main)
  File "/mnt/bunnydisk/greta/miniconda3/envs/AlphaPulldown/lib/python3.7/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/mnt/bunnydisk/greta/miniconda3/envs/AlphaPulldown/lib/python3.7/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/mnt/bunnydisk/greta/miniconda3/envs/AlphaPulldown/bin/run_multimer_jobs.py", line 342, in main
    multimers = create_multimer_objects(data, FLAGS.monomer_objects_dir, not FLAGS.no_pair_msa)
  File "/mnt/bunnydisk/greta/miniconda3/envs/AlphaPulldown/bin/run_multimer_jobs.py", line 177, in create_multimer_objects
    multimer = MultimericObject(interactors=interactors,pair_msa=pair_msa)
  File "/mnt/bunnydisk/greta/miniconda3/envs/AlphaPulldown/lib/python3.7/site-packages/alphapulldown/objects.py", line 452, in __init__
    self.create_all_chain_features()
  File "/mnt/bunnydisk/greta/miniconda3/envs/AlphaPulldown/lib/python3.7/site-packages/alphapulldown/objects.py", line 522, in create_all_chain_features
    chain_features, chain_id
  File "/mnt/bunnydisk/greta/miniconda3/envs/AlphaPulldown/lib/python3.7/site-packages/alphafold/data/pipeline_multimer.py", line 88, in convert_monomer_features
    feature = np.argmax(feature, axis=-1).astype(np.int32)
  File "<__array_function__ internals>", line 6, in argmax
  File "/mnt/bunnydisk/greta/miniconda3/envs/AlphaPulldown/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 1195, in argmax
    return _wrapfunc(a, 'argmax', axis=axis, out=out)
  File "/mnt/bunnydisk/greta/miniconda3/envs/AlphaPulldown/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 57, in _wrapfunc
    return bound(*args, **kwds)
ValueError: attempt to get argmax of an empty sequence
``

Hope I'm just missing something
Thank you for all the work behind AlphaPulldown!

Greta

**Comment by gretabellinzona** [comment]
Hello, 
this was the output folder structure: 
`
drwxrwxr-x 5 greta greta     4096 nov  8 15:01 ./
drwxrwxr-x 8 greta greta     4096 nov  8 18:59 ../
-rw-rw-r-- 1 greta greta     6213 nov  8 15:00 D0_MT_TRINITY_DN10521_c0_g1_i6_orf6.a3m
drwxrwxr-x 2 greta greta     4096 nov  8 15:00 D0_MT_TRINITY_DN10521_c0_g1_i6_orf6_env/
-rw-rw-r-- 1 greta greta     1705 nov  8 15:00 D0_MT_TRINITY_DN10521_c0_g1_i6_orf6_feature_metadata_2022-11-08.txt
-rw-rw-r-- 1 greta greta    61422 nov  8 15:01 D0_MT_TRINITY_DN10521_c0_g1_i6_orf6.pkl
-rw-rw-r-- 1 greta greta    12668 nov  8 15:01 D0_MT_TRINITY_DN10538_c0_g2_i3_orf7.a3m
drwxrwxr-x 2 greta greta     4096 nov  8 15:01 D0_MT_TRINITY_DN10538_c0_g2_i3_orf7_env/
-rw-rw-r-- 1 greta greta     1705 nov  8 15:01 D0_MT_TRINITY_DN10538_c0_g2_i3_orf7_feature_metadata_2022-11-08.txt
-rw-rw-r-- 1 greta greta    83048 nov  8 15:01 D0_MT_TRINITY_DN10538_c0_g2_i3_orf7.pkl
-rw-rw-r-- 1 greta greta  3790266 nov  8 14:58 FliC.a3m
drwxrwxr-x 2 greta greta     4096 nov  8 14:58 FliC_env/
-rw-rw-r-- 1 greta greta     1705 nov  8 14:58 FliC_feature_metadata_2022-11-08.txt
-rw-rw-r-- 1 greta greta 36575019 nov  8 15:00 FliC.pkl
`

**Comment by henrywotton** [comment]
Thanks,

It seems the output folder has correct structure but maybe something wrong within the .pkl files. Would you mind uploading one of the pkl file to owncloud or google drive or something alike then I can download it and have a look?

Cheers

**Comment by gretabellinzona** [comment]
Sure! 
Thank you for your time
https://drive.google.com/drive/folders/1QwC10AKDWPycplE46dkdvdeni4aGCRXL?usp=sharing 

Cheers

**Comment by henrywotton** [comment]
Hi Greta,

Thanks for sharing the pickle file. I think based on your error log this ```multimers = create_multimer_objects(data, FLAGS.monomer_objects_dir, not FLAGS.no_pair_msa) ``` caused the issue.  Thus, I have used your FliC.pkl and modelled a homo-dimer from it just to test the ```multimers = create_multimer_objects(data, FLAGS.monomer_objects_dir, not FLAGS.no_pair_msa) ``` command but I finished without any error. Maybe you were modelling it with something else? if so, could you maybe share the pickle file for the other protein(s) or send us the command you used for running the 2nd stage? I couldn't replicate the error with this pickle file. 

Cheers

**Comment by gretabellinzona** [comment]
Hi, 
I was sure to have wrote it down in the first message (but no).
`
run_multimer_jobs.py --mode=pulldown --num_cycle=3 --num_predictions_per_model=1 --output_path=fastmsa --protein_lists=bait.txt,tick_proteins.txt --monomer_objects_dir=outdirmsa_2 --data_dir=/mnt/bunnydisk/AlphaFold_DB --job_index=1
`
Thank you a lot once again for your time

Kind regards
Greta

**Comment by henrywotton** [comment]
Hi Greta,

Sorry for the late reply and I have checked the pickle file you sent me but that one seems to be fine. Having the checked the similar issue #80 raised by Matt, I believe yours is also caused by some particular sequence(s) that does not have any suitable template in PDB70 database. Could you maybe send me all the pickle files you used? The one you sent was fine but I'm confident that at least one of the other proteins cannot find any templates in PDB70.

Cheers

**Comment by gretabellinzona** [comment]
Hey!

It was just a test and I've used only one baits and two candidate sequences that are the ones that I've previously uploaded on google drive (https://drive.google.com/drive/folders/1QwC10AKDWPycplE46dkdvdeni4aGCRXL?usp=sharing), nothing else

Cheers, 
Greta

**Comment by henrywotton** [comment]
Hi Greta,

Sorry I misunderstood and now I have figured out the source of the error. It was the same reason that caused #80 If you check the feature matrices corresponding to template in your ```D0_MT_TRINITY_DN10538_c0_g2_i3_orf7.pkl``` and ```D0_MT_TRINITY_DN10521_c0_g1_i6_orf6.pkl```, e.g. ```template_all_atom_positions``` and ```template_all_atom_positions```, they all are empty. That means these two sequences cannot be aligned to any structural templates in pdb70 database by HHSearch. 

I'm sorry that we never encountered this kind of sequences while developing the package but I will now work on handling this kind of exceptions from now. 

I hope it's all cleared up?

Yours
Dingquan

**Comment by gretabellinzona** [comment]
Dear Dingquan, 

That's all clear, thank you a lot for your attention and time. I look forward to use AlphaPulldown soon in the fast version ;)

Kind regards
Greta
