### ISSUE TITLE
Modeling entire protein chain based on fragment multimer model

### ISSUE THREAD

**Issue by mpm896** [KosinskiLab/AlphaPulldown#79]
Hello,

I'm curious if this feature is available that I haven't figured out yet. If I want to identify an interaction site between two proteins, and I input fragments of each protein to model in all_vs_all mode, is there a way to get an output of the modeled fragments with the remaining part of the protein that wasn't included in the interaction screen?

For example, protein A is 400 amino acids and protein B is 300 amino acids. The highest quality model was produced between aa 1-250 of protein A and aa 200-300 of protein B, which are the only two fragments shown in the .pdb. Is it possible to model the remaining structure on top of this, to get a model of this interaction with both full length proteins?

Thanks for your help,
Matt

**Comment by jkosinski** [comment]
Dear Matt,

At the moment it is not possible with AlphaPulldown. What you could try is to model the A and B as monomers separately, superpose them onto the A-B dimer fragment using e.g. UCSF ChimeraX and merge the non-overlapping part. This may work if the extra domains clash. Probably you could do merging with ChimeraX, I don't know - we would use scripts from our pdb_utils https://git.embl.de/grp-kosinski/pdb_utils like this:
1.  Superpose the monomers in ChimeraX
2. Save superposed monomers as new pdb files
3. cut out non-overlapping fragments  using the cut_pdb.py script
4. Merge pdb files using the merge.py script.

Best,
Jan
