### ISSUE TITLE
Error with run_multimer_jobs.py

### ISSUE THREAD

**Issue by mpm896** [KosinskiLab/AlphaPulldown#80]
Hello,

I've been trying to run run_multimer_job.py in pulldown mode with medium-sized lists of bait and candidate proteins. When I run it, however, similar to issue #77, I get the following error:

**Traceback (most recent call last):
  File "/home/spuser/.conda/envs/AlphaPulldown/bin/run_multimer_jobs.py", line 372, in <module>
    app.run(main)
  File "/home/spuser/.conda/envs/AlphaPulldown/lib/python3.7/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/home/spuser/.conda/envs/AlphaPulldown/lib/python3.7/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "/home/spuser/.conda/envs/AlphaPulldown/bin/run_multimer_jobs.py", line 342, in main
    multimers = create_multimer_objects(data, FLAGS.monomer_objects_dir, not FLAGS.no_pair_msa)
  File "/home/spuser/.conda/envs/AlphaPulldown/bin/run_multimer_jobs.py", line 175, in create_multimer_objects
    interactors = create_interactors(data, monomer_objects_dir, job_idx)
  File "/home/spuser/.conda/envs/AlphaPulldown/lib/python3.7/site-packages/alphapulldown/utils.py", line 159, in create_interactors
    chopped_object.prepare_final_sliced_feature_dict()
  File "/home/spuser/.conda/envs/AlphaPulldown/lib/python3.7/site-packages/alphapulldown/objects.py", line 412, in prepare_final_sliced_feature_dict
    self.feature_dict, start_point, end_point
  File "/home/spuser/.conda/envs/AlphaPulldown/lib/python3.7/site-packages/alphapulldown/objects.py", line 364, in prepare_individual_sliced_feature_dict
    feature_dict, start_point, end_point
  File "/home/spuser/.conda/envs/AlphaPulldown/lib/python3.7/site-packages/alphapulldown/objects.py", line 333, in prepare_new_template_feature_dict
    :, start_point:end_point, :
IndexError: too many indices for array: array is 1-dimensional, but 3 were indexed**

My input command was the following:

**run_multimer_jobs.py --mode=pulldown \
--output_path=/data/matt/AlphaPulldown/Output/TgPCR/predictions \
--num_cycle=3 \
--num_predictions_per_model=1 \
--protein_lists=PCR_baits.txt,PCR_fragments.txt \
--monomer_objects_dir=/data/matt/AlphaPulldown/Output/TgPCR/features \
--data_dir=/data/AFDB**

Similar to an attempt to find the issue that was done in #77, I ran homo-oligomer mode to predict 2-mers of the first 3 proteins in the baits list and didn't run into any issues. I also ran the example pulldown with the Z and L proteins and had no problems. I did however get the same error when using either the baits or the candidates list for all_vs_all mode. 

Here is the directory structure of the output directory with the protein features:

**-rw-rw-r--. 1 spuser spuser   2642920 Nov 11 10:17 TgAKMT.a3m
drwxrwxr-x. 2 spuser spuser         7 Nov 11 10:17 TgAKMT_env
-rw-rw-r--. 1 spuser spuser      1677 Nov 11 10:16 TgAKMT_feature_metadata_2022-11-11.txt
-rw-rw-r--. 1 spuser spuser  28545773 Nov 11 10:18 TgAKMT.pkl
-rw-rw-r--. 1 spuser spuser   3607615 Nov 11 10:19 TgCen2.a3m
drwxrwxr-x. 2 spuser spuser         7 Nov 11 10:19 TgCen2_env
-rw-rw-r--. 1 spuser spuser      1677 Nov 11 10:18 TgCen2_feature_metadata_2022-11-11.txt
-rw-rw-r--. 1 spuser spuser  22678774 Nov 11 10:20 TgCen2.pkl
-rw-rw-r--. 1 spuser spuser   1052657 Nov 11 10:26 TgCGP.a3m
drwxrwxr-x. 2 spuser spuser         7 Nov 11 10:26 TgCGP_env
-rw-rw-r--. 1 spuser spuser      1677 Nov 11 10:20 TgCGP_feature_metadata_2022-11-11.txt
-rw-rw-r--. 1 spuser spuser   8752366 Nov 11 10:33 TgCGP.pkl
-rw-rw-r--. 1 spuser spuser    461839 Nov 11 10:33 TgDIP13.a3m
drwxrwxr-x. 2 spuser spuser         7 Nov 11 10:33 TgDIP13_env
-rw-rw-r--. 1 spuser spuser      1677 Nov 11 10:33 TgDIP13_feature_metadata_2022-11-11.txt
-rw-rw-r--. 1 spuser spuser   4632397 Nov 11 10:34 TgDIP13.pkl
-rw-rw-r--. 1 spuser spuser   7682236 Nov 11 10:40 TgFRM1.a3m
drwxrwxr-x. 2 spuser spuser         7 Nov 11 10:40 TgFRM1_env
-rw-rw-r--. 1 spuser spuser      1677 Nov 11 10:34 TgFRM1_feature_metadata_2022-11-11.txt
-rw-rw-r--. 1 spuser spuser  60503122 Nov 11 10:48 TgFRM1.pkl
-rw-rw-r--. 1 spuser spuser    285803 Nov 11 10:51 TgGAC.a3m
drwxrwxr-x. 2 spuser spuser         7 Nov 11 10:51 TgGAC_env
-rw-rw-r--. 1 spuser spuser      1677 Nov 11 10:48 TgGAC_feature_metadata_2022-11-11.txt
-rw-rw-r--. 1 spuser spuser  38367867 Nov 11 10:55 TgGAC.pkl
-rw-rw-r--. 1 spuser spuser     25941 Nov 11 10:56 TGGT1_209200.a3m
drwxrwxr-x. 2 spuser spuser         7 Nov 11 10:56 TGGT1_209200_env
-rw-rw-r--. 1 spuser spuser      1677 Nov 11 10:55 TGGT1_209200_feature_metadata_2022-11-11.txt
-rw-rw-r--. 1 spuser spuser   3323886 Nov 11 10:57 TGGT1_209200.pkl
-rw-rw-r--. 1 spuser spuser  19515725 Nov 11 11:00 TGGT1_219070.a3m
drwxrwxr-x. 2 spuser spuser         7 Nov 11 11:00 TGGT1_219070_env
-rw-rw-r--. 1 spuser spuser      1677 Nov 11 10:57 TGGT1_219070_feature_metadata_2022-11-11.txt
-rw-rw-r--. 1 spuser spuser 173177314 Nov 11 11:05 TGGT1_219070.pkl
-rw-rw-r--. 1 spuser spuser     60667 Nov 11 11:09 TGGT1_284620.a3m
drwxrwxr-x. 2 spuser spuser         7 Nov 11 11:09 TGGT1_284620_env
-rw-rw-r--. 1 spuser spuser      1677 Nov 11 11:05 TGGT1_284620_feature_metadata_2022-11-11.txt
-rw-rw-r--. 1 spuser spuser    668711 Nov 11 11:13 TGGT1_284620.pkl
-rw-rw-r--. 1 spuser spuser    116301 Nov 11 11:14 TGGT1_306350.a3m
drwxrwxr-x. 2 spuser spuser         7 Nov 11 11:14 TGGT1_306350_env
-rw-rw-r--. 1 spuser spuser      1677 Nov 11 11:13 TGGT1_306350_feature_metadata_2022-11-11.txt
-rw-rw-r--. 1 spuser spuser  11139571 Nov 11 11:17 TGGT1_306350.pkl
-rw-rw-r--. 1 spuser spuser    134986 Nov 11 11:18 TgICAP16.a3m
drwxrwxr-x. 2 spuser spuser         7 Nov 11 11:18 TgICAP16_env
-rw-rw-r--. 1 spuser spuser      1677 Nov 11 11:17 TgICAP16_feature_metadata_2022-11-11.txt
-rw-rw-r--. 1 spuser spuser   1958374 Nov 11 11:20 TgICAP16.pkl
-rw-rw-r--. 1 spuser spuser     23490 Nov 11 11:21 TgPCR1.a3m
drwxrwxr-x. 2 spuser spuser         7 Nov 11 11:21 TgPCR1_env
-rw-rw-r--. 1 spuser spuser      1677 Nov 11 11:20 TgPCR1_feature_metadata_2022-11-11.txt
-rw-rw-r--. 1 spuser spuser   7315175 Nov 11 11:23 TgPCR1.pkl
-rw-rw-r--. 1 spuser spuser     18453 Nov 11 11:23 TgPCR2.a3m
drwxrwxr-x. 2 spuser spuser         7 Nov 11 11:23 TgPCR2_env
-rw-rw-r--. 1 spuser spuser      1677 Nov 11 11:23 TgPCR2_feature_metadata_2022-11-11.txt
-rw-rw-r--. 1 spuser spuser   1742488 Nov 11 11:25 TgPCR2.pkl
-rw-rw-r--. 1 spuser spuser     55340 Nov 11 11:26 TgPCR3.a3m
drwxrwxr-x. 2 spuser spuser         7 Nov 11 11:26 TgPCR3_env
-rw-rw-r--. 1 spuser spuser      1677 Nov 11 11:25 TgPCR3_feature_metadata_2022-11-11.txt
-rw-rw-r--. 1 spuser spuser   3697689 Nov 11 11:27 TgPCR3.pkl
-rw-rw-r--. 1 spuser spuser   2705574 Nov 11 11:28 TgPCR4.a3m
drwxrwxr-x. 2 spuser spuser         7 Nov 11 11:27 TgPCR4_env
-rw-rw-r--. 1 spuser spuser      1677 Nov 11 11:27 TgPCR4_feature_metadata_2022-11-11.txt
-rw-rw-r--. 1 spuser spuser  27030093 Nov 11 11:29 TgPCR4.pkl
-rw-rw-r--. 1 spuser spuser   2932555 Nov 11 11:30 TgPCR5.a3m
drwxrwxr-x. 2 spuser spuser         7 Nov 11 11:30 TgPCR5_env
-rw-rw-r--. 1 spuser spuser      1677 Nov 11 11:29 TgPCR5_feature_metadata_2022-11-11.txt
-rw-rw-r--. 1 spuser spuser  35795639 Nov 11 11:32 TgPCR5.pkl
-rw-rw-r--. 1 spuser spuser    138774 Nov 11 11:33 TgPCR6.a3m
drwxrwxr-x. 2 spuser spuser         7 Nov 11 11:33 TgPCR6_env
-rw-rw-r--. 1 spuser spuser      1677 Nov 11 11:32 TgPCR6_feature_metadata_2022-11-11.txt
-rw-rw-r--. 1 spuser spuser   1042101 Nov 11 11:34 TgPCR6.pkl
-rw-rw-r--. 1 spuser spuser    339597 Nov 11 11:36 TgPCR7.a3m
drwxrwxr-x. 2 spuser spuser         7 Nov 11 11:36 TgPCR7_env
-rw-rw-r--. 1 spuser spuser      1677 Nov 11 11:34 TgPCR7_feature_metadata_2022-11-11.txt
-rw-rw-r--. 1 spuser spuser  15990946 Nov 11 11:39 TgPCR7.pkl**

And finally, here's compressed file with the output directory and the input files:

[Pulldown_Error.tar.gz](https://github.com/KosinskiLab/AlphaPulldown/files/9992896/Pulldown_Error.tar.gz)

Thank you in advance for any help!

Matt

**Comment by henrywotton** [comment]
Thanks a lot for the updates Matt. I'm going through your files now and my initial guess is: these 4 proteins you mentioned above may have incomplete a3m files or some other issues with the mmseqs2 results so that some of their feature matrices are not properly constructed. Please give me some time and I aim to get back to you soon.

Cheers

**Comment by mpm896** [comment]
Hi Dingquan,

Thanks so much for looking into this! I notices when running mmseqs2 that it showed little to no results for these proteins. I've previously run pieces of these proteins through ColabFold using the monomer model and have also seen that the MSAs don't find anything, which usually results in disordered structural predictions. I wasn't aware that would cause an error when running with this- it would be great if in the future these sorts of sequences could be run through AlphaPulldown! Thank you again for clearing this up for me.

Best,
Matt

**Comment by henrywotton** [comment]
Now will handle proteins with empty template features.
