### ISSUE TITLE
Very slow compile error

### ISSUE THREAD

**Issue by mpm896** [KosinskiLab/AlphaPulldown#81]
Hello,

As I had previously mentioned in issue #80, I'm trying to run >600 jobs with AlphaPulldown. Every 2 or 3 predictions, something seems to crash however the job isn't killed, so it gets stuck at a standstill with this message:

*******************************
Very slow compile?  If you want to file a bug, run with envvar XLA_FLAGS=--xla_dump_to=/tmp/foo and attach the results.
Compiling module jit_apply_fn.45
*******************************

I've been working on writing a shell script to run in the background that will kill and restart the AlpaPulldown job when this message pops up in the terminal, but then when restarting it spends a lot of time creating the multimer models again and looking through what has already been completed. Have you ever encountered this sort of error? I can't seem to find much about it. Thanks for any help!

Best,
Matt

**Comment by henrywotton** [comment]
Hi Matt,

Thanks for pointing it out and indeed I have seen this message quite often. However, I haven't found any solution yet. I guess this is related to the design of Jax itself as seen in the issue here: google/jax#11271 I'm afraid it might be beyond the scope of our package. 

Even though this warning pops up a lot, the jobs are still able to finished eventually. I personally don't see this as a crash but rather a warning instead.

Cheers

**Comment by henrywotton** [comment]
Hi Matt,

Now I see why that can kill your jobs. Really sorry in our cases, SLURM schedules and distributed each job to each individual GPU node. Thus, even though this warning pops up quite often, the jobs are still gonna run. Our package did not take care of requiring and distributing on multiple GPUs directly, either. We'll look into the issue and try to address it in the future. 

Besides, maybe you could try running ```run_multimer_jobs.py``` in a bash loop and each iteration of the loop, you use a different ```job_index``` parameter? I'm not sure if it will solve the problem as I guess the script cannot automatically be allocated to the rest of freely available GPUs?

Cheers

**Comment by mpm896** [comment]
Hi again,

I've gotten Slurm installed on our workstation with multiple GPUs and have written a script to submit the slurm job. I followed the example's given in Example_1 to setup the Sbatch parameters. The job exits after a few seconds, and in the _out.txt file (for the MSA calculation) I get the following:

ERROR: Unable to locate a modulefile for 'HMMER/3.3.2-gompic-2020b'
ERROR: Unable to locate a modulefile for 'HH-suite/3.3.0-gompic-2020b'
ERROR: Unable to locate a modulefile for 'Anaconda3'

I'm not sure how to add modulefiles for these? Running "module list" doesn't show any of these. Thanks for any help!

Best,
Matt

**Comment by henrywotton** [comment]
Hi Matt

Sorry but in our cases, these modules were built via easybuild by the other experts in this topic. I'm afraid it is beyond the scope of this package. Since we are not experts in building modules, I'm really sorry that we couldn't provide too much help in these cases. Please refer to Slurm's or easybuild's manuals for their instructions. 

Yours
Dingquan

**Comment by jkosinski** [comment]
Hi Matt,

Just to add - the "modules" come from EasyBuild https://easybuild.io/, which "is a software build and installation framework that allows you to manage (scientific) software on High Performance Computing (HPC) systems in an efficient way.". It might be not available on your computer so you need to install Anaconda3 differently and install; HMMER and HH-suite using Anaconda as described in our installation guide. And you should remove the "module load" commands.

Best,
Jan

**Comment by mpm896** [comment]
Got it, thanks. I had removed the module load commands the other day and it works fine. Also to add to my initial issue that I opened, we've gotten SLURM installed and I've created the SLURM scripts that run the multimer jobs and it seems to be running great with no problems. Thanks for all your help!

Best,
Matt
