### ISSUE TITLE
GPU usage in create_individual_features.py

### ISSUE THREAD

**Issue by phpeters** [KosinskiLab/AlphaPulldown#84]
Hej,

first of all: Thanks for this pipeline and the nice examples! 
I have a question about using create_individual_features.py as described in the [example](https://github.com/KosinskiLab/AlphaPulldown/blob/main/example_1.md): In the sbatch script you're reserving a GPU but I only see CPU-related commands. I probably miss something but can't I simply skip the GPU-node reservation?

Thanks a lot and best!
Philipp

**Comment by henrywotton** [comment]
Hi Philipp,

Sorry but in the example you pointed out, the bash script we provided for running create_individual_features.py does not contain any header that require GPU resources.  Maybe you have mistaken it with the other bash script example we provided for run_multimer_jobs.py ?

Yours,
Dingquan

**Comment by phpeters** [comment]
Hej Dingquan,

Thanks for your quick reply and sorry for my stupid question. Indeed, somehow I got the script wrong. I formerly withdraw my question. Have a great day!
Philipp
