### ISSUE TITLE
Pvalue in output csv table

### ISSUE THREAD

**Issue by nduan1** [KosinskiLab/AlphaPulldown#85]
Hi,

The pipeline is so helpful! Could you explain a little about the pvalue from the output? Should I filter out the results based on p<0.05? I can't find related information from paper.

Thanks,

Ning

![Screen Shot 2022-11-22 at 1 18 09 PM](https://user-images.githubusercontent.com/37407138/203391754-8c90eb53-732f-4495-9fb3-85a7dbb07ca5.png)

**Comment by henrywotton** [comment]
Hi Ning,

Sorry for that confusing column I thought I have removed it from my singularity image. That p-value is completely different from a p-value in a statistical test; its value shouldn't be interpreted the same way. Frankly speaking, it wasn't supposed to be there but I'm sorry there could be something wrong with my version control. I'll get back to you once I figured it out and please ignore this column for now. 

Cheers
Dingquan

**Comment by nduan1** [comment]
Hi Dingquan,

Thanks for your clarification. No worries, I will remove the columns from the output. 

Have a great week!

Best,

Ning
