### ISSUE TITLE
TypeError: cannot unpack non-iterable DataPipeline object while using create_individual_features.py

### ISSUE THREAD

**Issue by lorethan22** [KosinskiLab/AlphaPulldown#86]
The call of "create_individual_features.py" aborts with the following error message:
"I1128 12:24:16.870391 23456247859008 templates.py:857] Using precomputed obsolete pdbs /data/a/alphafold_db/pdb_mmcif/obsolete.dat.
Traceback (most recent call last):
File "/data/a/anaconda3/envs/AlphaPulldown0.22.2/bin/create_individual_features.py", line 286, in
app.run(main)
File "/data/a/anaconda3/envs/AlphaPulldown0.22.2/lib/python3.7/site-packages/absl/app.py", line 312, in run
_run_main(main, args)
File "/data/a/anaconda3/envs/AlphaPulldown0.22.2/lib/python3.7/site-packages/absl/app.py", line 258, in _run_main
sys.exit(main(argv))
File "/data/a/anaconda3/envs/AlphaPulldown0.22.2/bin/create_individual_features.py", line 252, in main
pipeline, flags_dict = create_pipeline()
TypeError: cannot unpack non-iterable DataPipeline object"

Here ist the full call of create_individual_features.py
(AlphaPulldown0.22.2) [user@apd_usertest]$ create_individual_features.py --fasta_paths=baits.fasta,example_1_sequences_shorter.fasta --data_dir=/data/a/alphafold_db --save_msa_files=True --output_dir=/data/a/user/apd_usertest --use_precomputed_msas=False --max_template_date=2022-10-01 --skip_existing=False

With AlphaPulldown 0.22.1 there was no issue with create_individual_features.py. Wenn I replace the old version of create_individual_features.py it still works.

**Comment by lorethan22** [comment]
In version 0.22.2 of create_individual_features.py, line 252 "pipeline, flags_dict = create_pipeline()" expects 2 values for one for pipeline and one for flags_dict, but the function now only returns one. So the solution is to remove flags_dict from this line, like this "pipeline = create_pipeline()".

**Comment by jkosinski** [comment]
Ups, sorry and thanks, @henrywotton  will fix it when he's back - for now, can you try with --mmseqs2 option?https://github.com/KosinskiLab/AlphaPulldown/blob/main/example_1.md#run-using-mmseqs2-and-colabfold-databases-faster

**Comment by henrywotton** [comment]
Already fixed. Close issue now
