### ISSUE TITLE
run_get_good_pae.sh "jobs" data missing when computing pi_score

### ISSUE THREAD

**Issue by SchwarzMarek** [KosinskiLab/AlphaPulldown#87]
Hello,
Thanks for a nice pipeline.

I'm having an issue when running the "alpha-analysis". As far as I was able to check, the interaction appears to be predicted and all files with structures and model pickle files appear to be present. However I obtain following error (`tail` of stderr and stdout attached).  I'm not sure what part of computation failed so the `jobs` data is not available. Should I recompute the features and the multimer prediction?

On a side note, the evaluation takes rather long time, can I specify to "run_get_good_pae.sh" to use more cores or to save intermediate results, so I don't have to recompute the whole thing when it crashes?

Thank you for any input

tail STDERR
```
I1130 23:34:56.916176 22833771701440 get_good_inter_pae.py:65] pi_score output for XXX_and_BSU_22530 will be stored at /mnt/pi_score_outputs/XXX_and_BSU_22530
/software/pi_score/utils.py:305: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  topredict_1 = sc.transform(topredict_1)
Traceback (most recent call last):
  File "/app/programme_notebook/get_good_inter_pae.py", line 149, in <module>
    app.run(main)
  File "/opt/conda/lib/python3.9/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/opt/conda/lib/python3.9/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/app/programme_notebook/get_good_inter_pae.py", line 138, in main
    pi_score_df = run_and_summarise_pi_score(FLAGS.output_dir,good_jobs,FLAGS.surface_thres)
  File "/app/programme_notebook/get_good_inter_pae.py", line 91, in run_and_summarise_pi_score
    filtered_df=pd.merge(filtered_df,pi_score,on='jobs')
  File "/opt/conda/lib/python3.9/site-packages/pandas/core/reshape/merge.py", line 107, in merge
    op = _MergeOperation(
  File "/opt/conda/lib/python3.9/site-packages/pandas/core/reshape/merge.py", line 700, in __init__
    ) = self._get_merge_keys()
  File "/opt/conda/lib/python3.9/site-packages/pandas/core/reshape/merge.py", line 1097, in _get_merge_keys
    right_keys.append(right._get_label_or_level_values(rk))
  File "/opt/conda/lib/python3.9/site-packages/pandas/core/generic.py", line 1840, in _get_label_or_level_values
    raise KeyError(key)
KeyError: 'jobs'
```
tail STDOUT
```
 ... session 'name' Created
 ... structure read and understood
 ... structural equivalence analysed
 ... molecular surfaces analysed
 ... 1 potential contacts identified, now processing:
     |
 ... total 1 interfaces calculated
 ... assembly analysis: not performed as no crystal data were found.
 ... results written

 +++ session 'name' erased

Checking local paths
*****Selecting model for training*****
*****Setting output directory for results*****
*****Setting input for assessment*****
*****Iterating over each structure to assess*****
*****Making results subdirectory specific to each structure in output directory*****
/mnt/pi_score_outputs/XXX_and_BSU_22530/ranked_0
*****Doing PDB, ranked_0.pdb  *****
*****Calculating interface*****
*****Calculating contacts*****
*****Iterating over interfaces in structure*****
*****Calculating interface features*****
*****Calculating shape complementarity*****
Writing sc script ['C', 'B']
ranked_0_clean.pdb_C_B_sc_infle.sh OUTFLE for SC
*****Calculating pisa *****
*****Writing CSV file with features *****
*****Calculating PI-score*****
```

**Comment by jkosinski** [comment]
@henrywotton will have a look when he is back, in the meantime could you send the command you used?

**Comment by SchwarzMarek** [comment]
Thanks for the response.

I'm using the singularity container.

The command to run it was:
```
singularity exec \
    --no-home \
    --bind $ROOTDIR/models:/mnt \
    --bind $SCRATCHDIR/tmp:/tmp \
    $ROOTDIR/alpha-analysis.sif \
    run_get_good_pae.sh \
    --output_dir=/mnt \
    --cutoff=10
```

Or do you mean other commands used to run the pipeline?

**Comment by henrywotton** [comment]
Hi,

I'm sorry for such an error. There is a small difference though between the command you used and the one written in our manual. Could you remove the ```--bind $SCRATCHDIR/tmp:/tmp``` from it and try again perhaps? I managed to reproduce the error when I included this mounting parameter and the error was gone once I removed it. 

Another possible cause is that your ```$ROOTDIR/models/pi_score_outputs``` contains many versions of outputs after several attempts. Perhaps you could ```rm -rf $ROOTDIR/models/pi_score_outputs``` and run the command again without the ```--bind $SCRATCHDIR/tmp:/tmp``` mounting. 

Hope it helps.

Yours
Dingquan

**Comment by gretabellinzona** [comment]
Hi, 
I'm also facing the same error, however I'm new to singularity and maybe the command is wrong:
`singularity exec --no-home --bind /mnt/pallasdisk/celine/15seq.output /mnt/pallasdisk/celine/alpha-analysis.sif run_get_good_pae.sh --output_dir=/mnt/pallasdisk/celine/csv.output --cutoff=10
`

Thank u, 
Greta

**Comment by henrywotton** [comment]
Hi Greta,

Sorry but I'm afraid there are a couple of things wrong in your command. 

- It should be ```--bind /mnt/pallasdisk/celine/15seq.output:/mnt``` and then ```--output_dir=/mnt```
- Is you 15seq.output a file or a directory?

Cheers

**Comment by gretabellinzona** [comment]
Thank you Henry,

we edited the command `singularity exec --no-home --bind /mnt/pallasdisk/celine/15seq.output:/mnt /mnt/pallasdisk/celine/alpha-analysis.sif run_get_good_pae.sh --output_dir=/mnt --cutoff=10` and now it's working but at some point still throwing the same error as before:
`I1207 11:26:32.168874 140548959052992 get_good_inter_pae.py:110] now processing FliC_Candidatus_Midichloria_mitochondrii_IricVA_GCA_000219355.1_and_D0_MT_TRINITY_DN165_c1_g1_i10_orf2

I1207 11:26:48.110092 140548959052992 get_good_inter_pae.py:131] done for FliC_Candidatus_Midichloria_mitochondrii_IricVA_GCA_000219355.1_and_D0_MT_TRINITY_DN165_c1_g1_i10_orf2 1 out of 15 finished.

I1207 11:26:48.110235 140548959052992 get_good_inter_pae.py:110] now processing FliC_Candidatus_Midichloria_mitochondrii_IricVA_GCA_000219355.1_and_D0_MT_TRINITY_DN1043_c0_g2_i1_orf1

I1207 11:27:00.829239 140548959052992 get_good_inter_pae.py:131] done for FliC_Candidatus_Midichloria_mitochondrii_IricVA_GCA_000219355.1_and_D0_MT_TRINITY_DN1043_c0_g2_i1_orf1 2 out of 15 finished.

I1207 11:27:00.829378 140548959052992 get_good_inter_pae.py:110] now processing FliC_Candidatus_Midichloria_mitochondrii_IricVA_GCA_000219355.1_and_D0_MT_TRINITY_DN1465_c0_g1_i14_orf2

I1207 11:27:23.126010 140548959052992 get_good_inter_pae.py:131] done for FliC_Candidatus_Midichloria_mitochondrii_IricVA_GCA_000219355.1_and_D0_MT_TRINITY_DN1465_c0_g1_i14_orf2 3 out of 15 finished.

I1207 11:27:23.126147 140548959052992 get_good_inter_pae.py:110] now processing pallasdisk

I1207 11:27:23.126226 140548959052992 get_good_inter_pae.py:110] now processing FliC_Candidatus_Midichloria_mitochondrii_IricVA_GCA_000219355.1_and_D0_MT_TRINITY_DN1536_c0_g1_i5_orf2

I1207 11:27:36.255345 140548959052992 get_good_inter_pae.py:131] done for FliC_Candidatus_Midichloria_mitochondrii_IricVA_GCA_000219355.1_and_D0_MT_TRINITY_DN1536_c0_g1_i5_orf2 4 out of 15 finished.

I1207 11:27:36.255486 140548959052992 get_good_inter_pae.py:110] now processing FliC_Candidatus_Midichloria_mitochondrii_IricVA_GCA_000219355.1_and_D0_MT_TRINITY_DN1026_c0_g1_i16_orf3

I1207 11:27:55.705780 140548959052992 get_good_inter_pae.py:131] done for FliC_Candidatus_Midichloria_mitochondrii_IricVA_GCA_000219355.1_and_D0_MT_TRINITY_DN1026_c0_g1_i16_orf3 5 out of 15 finished.

I1207 11:27:55.705919 140548959052992 get_good_inter_pae.py:110] now processing FliC_Candidatus_Midichloria_mitochondrii_IricVA_GCA_000219355.1_and_D0_MT_TRINITY_DN1006_c0_g1_i6_orf1

I1207 11:28:07.647872 140548959052992 get_good_inter_pae.py:131] done for FliC_Candidatus_Midichloria_mitochondrii_IricVA_GCA_000219355.1_and_D0_MT_TRINITY_DN1006_c0_g1_i6_orf1 6 out of 15 finished.

I1207 11:28:07.648010 140548959052992 get_good_inter_pae.py:110] now processing FliC_Candidatus_Midichloria_mitochondrii_IricVA_GCA_000219355.1_and_D0_MT_TRINITY_DN1572_c4_g1_i14_orf1

I1207 11:28:28.290255 140548959052992 get_good_inter_pae.py:131] done for FliC_Candidatus_Midichloria_mitochondrii_IricVA_GCA_000219355.1_and_D0_MT_TRINITY_DN1572_c4_g1_i14_orf1 7 out of 15 finished.

I1207 11:28:28.290409 140548959052992 get_good_inter_pae.py:110] now processing FliC_Candidatus_Midichloria_mitochondrii_IricVA_GCA_000219355.1_and_D0_MT_TRINITY_DN1026_c0_g1_i16_orf2

I1207 11:28:39.045822 140548959052992 get_good_inter_pae.py:131] done for FliC_Candidatus_Midichloria_mitochondrii_IricVA_GCA_000219355.1_and_D0_MT_TRINITY_DN1026_c0_g1_i16_orf2 8 out of 15 finished.

I1207 11:28:39.045972 140548959052992 get_good_inter_pae.py:110] now processing FliC_Candidatus_Midichloria_mitochondrii_IricVA_GCA_000219355.1_and_D0_MT_TRINITY_DN1211_c0_g1_i4_orf3

I1207 11:28:57.510720 140548959052992 get_good_inter_pae.py:131] done for FliC_Candidatus_Midichloria_mitochondrii_IricVA_GCA_000219355.1_and_D0_MT_TRINITY_DN1211_c0_g1_i4_orf3 9 out of 15 finished.

I1207 11:28:57.510860 140548959052992 get_good_inter_pae.py:110] now processing FliC_Candidatus_Midichloria_mitochondrii_IricVA_GCA_000219355.1_and_D0_MT_TRINITY_DN1379_c0_g1_i33_orf2

I1207 11:29:12.233931 140548959052992 get_good_inter_pae.py:131] done for FliC_Candidatus_Midichloria_mitochondrii_IricVA_GCA_000219355.1_and_D0_MT_TRINITY_DN1379_c0_g1_i33_orf2 10 out of 15 finished.

I1207 11:29:12.234085 140548959052992 get_good_inter_pae.py:110] now processing FliC_Candidatus_Midichloria_mitochondrii_IricVA_GCA_000219355.1_and_D0_MT_TRINITY_DN1089_c0_g1_i6_orf5

I1207 11:29:36.115083 140548959052992 get_good_inter_pae.py:131] done for FliC_Candidatus_Midichloria_mitochondrii_IricVA_GCA_000219355.1_and_D0_MT_TRINITY_DN1089_c0_g1_i6_orf5 11 out of 15 finished.

I1207 11:29:36.115238 140548959052992 get_good_inter_pae.py:110] now processing FliC_Candidatus_Midichloria_mitochondrii_IricVA_GCA_000219355.1_and_D0_MT_TRINITY_DN1536_c0_g1_i4_orf2

I1207 11:29:48.969176 140548959052992 get_good_inter_pae.py:131] done for FliC_Candidatus_Midichloria_mitochondrii_IricVA_GCA_000219355.1_and_D0_MT_TRINITY_DN1536_c0_g1_i4_orf2 12 out of 15 finished.

I1207 11:29:48.969318 140548959052992 get_good_inter_pae.py:110] now processing FliC_Candidatus_Midichloria_mitochondrii_IricVA_GCA_000219355.1_and_D0_MT_TRINITY_DN10_c4_g1_i3_orf1

I1207 11:30:00.885354 140548959052992 get_good_inter_pae.py:131] done for FliC_Candidatus_Midichloria_mitochondrii_IricVA_GCA_000219355.1_and_D0_MT_TRINITY_DN10_c4_g1_i3_orf1 13 out of 15 finished.

I1207 11:30:00.885495 140548959052992 get_good_inter_pae.py:110] now processing FliC_Candidatus_Midichloria_mitochondrii_IricVA_GCA_000219355.1_and_D0_MT_TRINITY_DN1465_c0_g1_i14_orf6

I1207 11:30:24.016020 140548959052992 get_good_inter_pae.py:131] done for FliC_Candidatus_Midichloria_mitochondrii_IricVA_GCA_000219355.1_and_D0_MT_TRINITY_DN1465_c0_g1_i14_orf6 14 out of 15 finished.

Traceback (most recent call last):

  File "/app/programme_notebook/get_good_inter_pae.py", line 149, in <module>

    app.run(main)

  File "/opt/conda/lib/python3.9/site-packages/absl/app.py", line 308, in run

    _run_main(main, args)

  File "/opt/conda/lib/python3.9/site-packages/absl/app.py", line 254, in _run_main

    sys.exit(main(argv))

  File "/app/programme_notebook/get_good_inter_pae.py", line 139, in main

    pi_score_df=pd.merge(pi_score_df,other_measurements_df,on="jobs")

  File "/opt/conda/lib/python3.9/site-packages/pandas/core/reshape/merge.py", line 107, in merge

    op = _MergeOperation(

  File "/opt/conda/lib/python3.9/site-packages/pandas/core/reshape/merge.py", line 700, in __init__

    ) = self._get_merge_keys()

  File "/opt/conda/lib/python3.9/site-packages/pandas/core/reshape/merge.py", line 1110, in _get_merge_keys

    left_keys.append(left._get_label_or_level_values(lk))

  File "/opt/conda/lib/python3.9/site-packages/pandas/core/generic.py", line 1840, in _get_label_or_level_values

    raise KeyError(key)

KeyError: 'jobs'`

Cheers,
Greta

**Comment by henrywotton** [comment]
Hi,

Sorry it occurred again and I haven't been able to reproduce the error myself recently. Could you please try ```rm -rf /mnt/pallasdisk/celine/15seq.output/pi_score_outputs```and then rerun the command? I fear if ```pi_score_outputs``` has too many files left from previous attempts, it may cause trouble.

Cheers

**Comment by gretabellinzona** [comment]
I rerun the command after removing the directory `pi_score_outputs` but it still return the error, I tried also on a different folder with other predictions and the result was the same. In each case it always happen before processing the last folder. I also noticed the creation of a folder called with the name of the disk on which I am, I don't know if it is supposed to be in this way.
Hope I can help :)

Thank u 
Greta

**Comment by henrywotton** [comment]
Hi,

Thanks for the details. Could you pls try removing the last folder and that particular folder with the name of the disk then rerun the command? Perhaps it might help?

Cheers

**Comment by gretabellinzona** [comment]
Hey Henry!

Problem solved: I was running the command on a very small batch of result while I'm waiting for the models prediction and the `cutoff` was too low for all of them (and so pandas couldn't perform the final merge on empty dfs), by increasing it I was able to obtain the final table. 

Thanks a lot once again for your help!

Greta
