### ISSUE TITLE
Improve flags handling?

### ISSUE THREAD

**Issue by jkosinski** [KosinskiLab/AlphaPulldown#91]
Can one do FLAGS assignment like: `FLAGS.name = some_value`?

If yes, you can simplify FLAGS management significantly in this script:
https://github.com/KosinskiLab/AlphaPulldown/blob/d1ab519ad3fecc775899c4d4adf1dc7bc0c86ed7/alphapulldown/create_individual_features.py#L88

e.g. changing blocks like this:
```python
    if FLAGS.uniref90_database_path is None: 
        uniref90_database_path = os.path.join(
            FLAGS.data_dir, "uniref90", "uniref90.fasta"
        )
    else:
        uniref90_database_path = FLAGS.uniref90_database_path
```
into

```python
    FLAGS.uniref90_database_path = FLAGS.uniref90_database_path or os.path.join(FLAGS.data_dir, "uniref90", "uniref90.fasta")
```
or if the above doesn't work (i think it should) into

```python
    if FLAGS.uniref90_database_path is None: 
        FLAGS.uniref90_database_path = os.path.join(
            FLAGS.data_dir, "uniref90", "uniref90.fasta"
        )
```

Do it for every block and also then remove all these global statements.

**Comment by DimaMolod** [comment]
Fixed in 4cb45c4c5a6336804caf4b9d5fff812f61d6bbc7
