### ISSUE TITLE
Feature request: only run 1 set of model params instead of all 5?

### ISSUE THREAD

**Issue by rlawr** [KosinskiLab/AlphaPulldown#93]
ColabFold allows you to choose how many models to run (ie 1-5). Despite the caveats this would be desirable for higher throughput screening.

**Comment by henrywotton** [comment]
Hi,

Sorry I misunderstood. So far out package uses all 5 of them. We'll think about whether to add this feature in the future.

Cheers

**Comment by XK4959** [comment]
@dingquanyu Hello, has this feature been added?
In addition, in pulldown mode, is mmseq2 used to generate complex msa based on monomer msa? Why not use AFM3 to predict the structure later, but AFM2?
I tested the 10*10 pulldown mode and the software took four days, while the colabfold Direct Prediction Complex didn't take as long! Why is it slower to use existing monomers as input than to predict complexes directly?

With best wishes

**Comment by DimaMolod** [comment]
Hi,
yes, this feature has been added. There is a new flag for run_multimer_jobs.py **--model_name**s where you can specify the models you want to run separated by coma, e.g. 
`--model_names=model_2_multimer_v3,model_3_multimer_v3` to run multimer models 2 and 3
Cheers

**Comment by XK4959** [comment]
@DimaMolod 
Hello, I have two more questions
1. How to specify that only one template is generated at a time, instead of five; Can modl_names be used to do this?
2. In structure prediction, since we input monomer msa, we should generate complex msa during operation, right? Is AF or mmseq2 used in this process? As far as I know, mmseq2 local version is faster, can I specify it?

Cheers

**Comment by DimaMolod** [comment]
Hello @XK4959 
1. Not sure what you mean by 'templates'. If you want to generate only 1 prediction by 1 model you need to specify the model name by the _--model-names_ flag and use _--num_predictions_per_model=1_
2. Yes, AF Multimer combines MSAs. It simply duplicates for homomeric complexes and pair sequences between the MSAs for each chain for heterocomplexes. AF can use several tools to produce MSAs, including mmseqs2. You can use _--mmseqs2_ remote API by specifying _--mmseqs=True_ flag when generating features.

**Comment by XK4959** [comment]
@DimaMolod 
Hello, thank you for your prompt reply!

The template here means model, I'm sorry.

Your reply basically solved my question, thank you for this ~

Cheers
