### ISSUE TITLE
Error with create_indivisual_features.py

### ISSUE THREAD

**Issue by YyMsd** [KosinskiLab/AlphaPulldown#97]
Hi

I've installed the AlphaPulldown and tried to run create_indivisual_features.py along to the example_1 with my target protein, but been prevented by the following error.
I've already checked the permission, paths and so on.
It is possible that I am missing something.
Thank you in advance for any help!

input 
```
create_individual_features.py \
  --fasta_paths="target protein's seq".fasta,example_1_sequences.fasta \
  --data_dir=/path/to/database \
  --save_msa_files=False \
  --output_dir=./AlphaP_results \
  --use_precomputed_msas=False \
  --max_template_date=2050-01-05 \
  --skip_existing=False \

```
output
```
2022-12-16 15:55:46.893817: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
FATAL Flags parsing error: flag --max_template_date=None: Flag --max_template_date must have a value other than None.
Pass --helpshort or --helpfull to see help on flags.
>
```

or additionally,
`--use_precomputed_msas=False: command not found`

**Comment by sophiaaredas** [comment]
I am also having this issue if anyone knows how to solve!
